//! Integration tests for the generated-artifact ownership manifest and
//! drift detection (issue #21). Every test runs the real pipeline over a
//! numbered sandbox under `target/` addressed with a relative selector —
//! never a canonicalized temp path, which the accepted selection policy
//! denies on Windows (the 8.3-alias lesson).

use serde_json::{json, Value};
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU32, Ordering};

use lekalo_core::artifacts::{
    ArtifactFailure, DriftVerdict, GenerateService, GENERATED_ROOT, MANIFEST_DIR, MANIFEST_NAME,
};
use lekalo_core::loader::LoadSelection;
use lekalo_core::lockfile::plan::LockService;
use lekalo_core::lockfile::resolution::CandidateSet;
use lekalo_core::lockfile::LockRequirement;
use lekalo_core::versioning::plan::sha256_hex;

const REFERENCE_PROJECT: &str = "../../tests/fixtures/artifacts/project";
const ARTIFACT_DIR: &str = "apps/api/src/planner";
const ARTIFACT_NAME: &str = "focus-task.ts";
const ARTIFACT_CONTENT: &str = "export function focusTask() {\n  return planner.createTask();\n}\n";

static NEXT_ROOT: AtomicU32 = AtomicU32::new(0);

struct Sandbox {
    selector: String,
    root: PathBuf,
}

impl Drop for Sandbox {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.root);
    }
}

fn copy_dir(from: &Path, to: &Path) {
    std::fs::create_dir_all(to).expect("create sandbox dir");
    for entry in std::fs::read_dir(from).expect("read reference") {
        let entry = entry.expect("reference entry");
        let target = to.join(entry.file_name());
        if entry.file_type().expect("entry type").is_dir() {
            copy_dir(&entry.path(), &target);
        } else {
            std::fs::copy(entry.path(), &target).expect("copy reference file");
        }
    }
}

fn with_project(body: impl FnOnce(&Sandbox)) {
    let id = NEXT_ROOT.fetch_add(1, Ordering::SeqCst);
    let relative = format!("target/artifact-tests/case-{}-{}", std::process::id(), id);
    let root = PathBuf::from(&relative);
    let _ = std::fs::remove_dir_all(&root);
    copy_dir(Path::new(REFERENCE_PROJECT), &root);
    let sandbox = Sandbox {
        selector: relative.replace('\\', "/"),
        root,
    };
    body(&sandbox);
    // Drop also removes the tree when the test panics: a leftover
    // sandbox project must never leak into other suites' scans.
    drop(sandbox);
}

impl Sandbox {
    fn selection(&self) -> LoadSelection {
        LoadSelection {
            project: Some(self.selector.clone()),
        }
    }

    fn create_lock(&self) -> String {
        let receipt = LockService::lock(
            &self.selection(),
            CandidateSet::empty(),
            LockRequirement::Optional,
            true,
        )
        .expect("lock created");
        assert_eq!(receipt.mode, "create");
        receipt.lock_digest
    }

    fn write_artifact(&self, content: &str) -> String {
        let dir = self.root.join(ARTIFACT_DIR);
        std::fs::create_dir_all(&dir).expect("artifact dir");
        std::fs::write(dir.join(ARTIFACT_NAME), content).expect("artifact bytes");
        lekalo_core::versioning::plan::sha256_hex(content.as_bytes())
    }

    fn manifest_path(&self) -> PathBuf {
        self.root.join(MANIFEST_DIR).join(MANIFEST_NAME)
    }

    fn write_generated(&self, content: &str) -> String {
        let path = self.root.join(GENERATED_ROOT).join("scratch.txt");
        std::fs::create_dir_all(path.parent().expect("generated parent")).expect("generated dir");
        std::fs::write(&path, content).expect("generated bytes");
        ".lekalo/generated/scratch.txt".to_owned()
    }
}

/// One closed wire artifact entry with the exact digest of `content`.
fn artifact_value(owner: &str, path: &str, kind: &str, lifecycle: &str, content: &str) -> Value {
    let policy = match lifecycle {
        "generated" => "on-input-change",
        "scaffolded" => "once",
        "checked" => "validate-only",
        "external" => "reference-only",
        _ => "manual-only",
    };
    json!({
        "semantic_owner": owner,
        "path": path,
        "artifact_kind": kind,
        "lifecycle": lifecycle,
        "content": {
            "algorithm": "sha256",
            "digest": format!("sha256:{}", sha256_hex(content.as_bytes())),
            "canonicalization": "exact-file-bytes",
        },
        "input_refs": [owner],
        "regeneration_policy": policy,
    })
}

/// One adapter-bound entry: refused against a lock whose target protocol
/// is still unpublished.
fn adapter_bound_value(owner: &str, path: &str, content: &str) -> Value {
    let mut entry = artifact_value(owner, path, "source", "generated", content);
    entry["adapter_ref"] = json!({
        "id": "node-typescript",
        "version": "0.1.2",
        "digest": format!("sha256:{}", sha256_hex(b"adapter-package")),
        "artifacts": [{"platform": "any", "digest": format!("sha256:{}", sha256_hex(b"adapter-any"))}],
        "protocol_version": null,
    });
    entry["generator_ref"] = json!({"id": "planner-gen", "version": "0.3.0"});
    entry
}

/// Author the canonical manifest for one sandbox from the live inputs.
fn author_manifest(sandbox: &Sandbox, artifacts: Vec<Value>, source_maps: Vec<Value>) {
    let inputs = GenerateService::inputs(&sandbox.selection()).expect("inputs receipt");
    let mut document = json!({
        "schema_version": "lekalo/artifact-manifest/v1.0.0",
        "identity": "dev.lekalo.artifact-manifest@1.0.0",
        "project_ref": "planner",
        "lock_ref": {
            "schema_version": "lekalo/lock/v1.0.0",
            "digest": inputs.lock_digest,
        },
        "inputs": {
            "model": {"version": inputs.model_version, "digest": inputs.model_digest},
            "ir": {"version": inputs.ir_version, "digest": inputs.ir_digest},
        },
        "artifacts": artifacts,
        "source_maps": source_maps,
    });
    // Stamp the non-self-referential digest over the payload without it.
    let stamp = |document: &Value| -> String {
        let mut draft = document.clone();
        draft
            .as_object_mut()
            .expect("object")
            .remove("manifest_digest");
        format!(
            "sha256:{}",
            sha256_hex(&serde_json::to_vec(&draft).expect("wire"))
        )
    };
    let digest = stamp(&document);
    document["manifest_digest"] = json!(digest);
    let path = sandbox.manifest_path();
    std::fs::create_dir_all(path.parent().expect("manifest parent")).expect("manifest dir");
    std::fs::write(
        &path,
        serde_json::to_vec(&document).expect("canonical wire"),
    )
    .expect("manifest bytes");
}

/// Overwrite the manifest keeping its declared digest (integrity tamper).
fn tamper_manifest_digest(sandbox: &Sandbox) {
    let bytes = std::fs::read(sandbox.manifest_path()).expect("manifest");
    let mut document: Value = serde_json::from_slice(&bytes).expect("wire");
    document["inputs"]["ir"]["digest"] = json!(format!("sha256:{}", sha256_hex(b"other")));
    std::fs::write(
        sandbox.manifest_path(),
        serde_json::to_vec(&document).expect("wire"),
    )
    .expect("rewrite");
}

fn reason_codes(failure: &ArtifactFailure) -> Vec<String> {
    let result = lekalo_core::DomainResult::from(failure);
    result
        .reason_codes()
        .iter()
        .map(|code| code.as_str().to_owned())
        .collect()
}

fn exit_of(failure: &ArtifactFailure) -> u8 {
    lekalo_core::DomainResult::from(failure).exit_code()
}

// ---------------------------------------------------------------------------
// Wire and binding behavior.
// ---------------------------------------------------------------------------

#[test]
fn absent_manifest_and_empty_generated_root_is_a_clean_vacuous_check() {
    with_project(|sandbox| {
        sandbox.create_lock();
        let receipt = GenerateService::check(&sandbox.selection()).expect("vacuous check");
        assert_eq!(receipt.status, "valid");
        assert_eq!(receipt.verdict, "clean");
        assert_eq!(receipt.counts.artifacts, 0);
        assert_eq!(receipt.manifest_digest, None);
    });
}

#[test]
fn check_refuses_a_project_without_a_lock() {
    with_project(|sandbox| {
        let failure = GenerateService::check(&sandbox.selection()).expect_err("no lock");
        assert_eq!(reason_codes(&failure), vec!["lock.missing".to_owned()]);
        assert_eq!(exit_of(&failure), 1);
    });
}

#[test]
fn inputs_receipt_is_deterministic_and_binds_the_created_lock() {
    with_project(|sandbox| {
        let lock_digest = sandbox.create_lock();
        let first = GenerateService::inputs(&sandbox.selection()).expect("inputs");
        let second = GenerateService::inputs(&sandbox.selection()).expect("inputs");
        assert_eq!(first, second);
        assert_eq!(first.lock_digest, lock_digest);
        assert_eq!(first.model_version, "1.0.0");
        assert_eq!(first.ir_version, "0.1.0");
        assert!(first.model_digest.starts_with("sha256:"));
        assert!(first.revision.starts_with("sha256:"));
    });
}

#[test]
fn valid_manifest_with_matching_bytes_checks_clean() {
    with_project(|sandbox| {
        let lock_digest = sandbox.create_lock();
        let content_digest = sandbox.write_artifact(ARTIFACT_CONTENT);
        author_manifest(
            sandbox,
            vec![artifact_value(
                "planner.create_task",
                "apps/api/src/planner/focus-task.ts",
                "source",
                "generated",
                ARTIFACT_CONTENT,
            )],
            vec![],
        );
        let receipt = GenerateService::check(&sandbox.selection()).expect("clean check");
        assert_eq!(receipt.verdict, "clean");
        assert_eq!(receipt.counts.artifacts, 1);
        assert_eq!(receipt.counts.clean, 1);
        assert!(receipt.manifest_digest.as_deref().is_some());
        let _ = (content_digest, lock_digest);
    });
}

#[test]
fn repeated_checks_are_byte_identical() {
    with_project(|sandbox| {
        sandbox.create_lock();
        sandbox.write_artifact(ARTIFACT_CONTENT);
        author_manifest(
            sandbox,
            vec![artifact_value(
                "planner.create_task",
                "apps/api/src/planner/focus-task.ts",
                "source",
                "generated",
                ARTIFACT_CONTENT,
            )],
            vec![],
        );
        let first = GenerateService::check(&sandbox.selection()).expect("check");
        let second = GenerateService::check(&sandbox.selection()).expect("check");
        assert_eq!(
            serde_json::to_string_pretty(&first).expect("wire"),
            serde_json::to_string_pretty(&second).expect("wire")
        );
    });
}

#[test]
fn manifest_bytes_authored_in_any_key_order_parse_identically() {
    with_project(|sandbox| {
        sandbox.create_lock();
        sandbox.write_artifact(ARTIFACT_CONTENT);
        author_manifest(
            sandbox,
            vec![artifact_value(
                "planner.create_task",
                "apps/api/src/planner/focus-task.ts",
                "source",
                "generated",
                ARTIFACT_CONTENT,
            )],
            vec![],
        );
        let bytes = std::fs::read(sandbox.manifest_path()).expect("manifest bytes");
        let document: Value = serde_json::from_slice(&bytes).expect("wire");
        // Re-serialize with a permuted key order: the value tree is a
        // BTreeMap, so the bytes stay the canonical spelling.
        let again = serde_json::to_vec(&document).expect("re-canonical");
        assert_eq!(bytes, again);
        let manifest = lekalo_core::artifacts::ArtifactManifest::parse_canonical(&bytes);
        assert!(manifest.is_ok());
    });
}

// ---------------------------------------------------------------------------
// Verdicts.
// ---------------------------------------------------------------------------

#[test]
fn manual_drift_on_a_generated_file_blocks_with_the_source_changed_rule() {
    with_project(|sandbox| {
        sandbox.create_lock();
        sandbox.write_artifact(ARTIFACT_CONTENT);
        author_manifest(
            sandbox,
            vec![artifact_value(
                "planner.create_task",
                "apps/api/src/planner/focus-task.ts",
                "source",
                "generated",
                ARTIFACT_CONTENT,
            )],
            vec![],
        );
        sandbox.write_artifact("export const drifted = true;\n");
        let failure = GenerateService::check(&sandbox.selection()).expect_err("drift");
        assert!(reason_codes(&failure).contains(&"lock.source-changed".to_owned()));
        assert_eq!(exit_of(&failure), 1);
        match &failure {
            ArtifactFailure::Drift(findings) => {
                assert_eq!(findings.len(), 1);
                assert_eq!(findings[0].verdict, DriftVerdict::ManualDrift.as_str());
            }
            other => panic!("expected drift, got {other:?}"),
        }
    });
}

#[test]
fn stale_inputs_block_the_whole_manifest() {
    with_project(|sandbox| {
        sandbox.create_lock();
        sandbox.write_artifact(ARTIFACT_CONTENT);
        author_manifest(
            sandbox,
            vec![artifact_value(
                "planner.create_task",
                "apps/api/src/planner/focus-task.ts",
                "source",
                "generated",
                ARTIFACT_CONTENT,
            )],
            vec![],
        );
        // Regenerate the manifest under different inputs by editing the
        // project model, then re-stamping against the OLD inputs is
        // equivalent to tampering the inputs pins.
        tamper_manifest_digest(sandbox);
        let failure = GenerateService::check(&sandbox.selection()).expect_err("tampered");
        assert_eq!(
            reason_codes(&failure),
            vec!["lock.digest-mismatch".to_owned()]
        );
        assert_eq!(exit_of(&failure), 3);
    });
}

#[test]
fn stale_lock_revision_blocks_with_the_stale_rule() {
    with_project(|sandbox| {
        sandbox.create_lock();
        sandbox.write_artifact(ARTIFACT_CONTENT);
        author_manifest(
            sandbox,
            vec![artifact_value(
                "planner.create_task",
                "apps/api/src/planner/focus-task.ts",
                "source",
                "generated",
                ARTIFACT_CONTENT,
            )],
            vec![],
        );
        // Point the manifest at another (well-formed) lock revision.
        let bytes = std::fs::read(sandbox.manifest_path()).expect("manifest");
        let mut document: Value = serde_json::from_slice(&bytes).expect("wire");
        document["lock_ref"]["digest"] = json!(format!("sha256:{}", sha256_hex(b"other-lock")));
        let mut draft = document.clone();
        draft
            .as_object_mut()
            .expect("object")
            .remove("manifest_digest");
        document["manifest_digest"] = json!(format!(
            "sha256:{}",
            sha256_hex(&serde_json::to_vec(&draft).expect("wire"))
        ));
        std::fs::write(
            sandbox.manifest_path(),
            serde_json::to_vec(&document).expect("wire"),
        )
        .expect("rewrite");
        let failure = GenerateService::check(&sandbox.selection()).expect_err("stale lock");
        assert_eq!(reason_codes(&failure), vec!["lock.stale".to_owned()]);
        assert_eq!(exit_of(&failure), 1);
    });
}

#[test]
fn missing_generated_file_blocks_with_the_document_missing_rule() {
    with_project(|sandbox| {
        sandbox.create_lock();
        author_manifest(
            sandbox,
            vec![artifact_value(
                "planner.create_task",
                "apps/api/src/planner/focus-task.ts",
                "source",
                "generated",
                ARTIFACT_CONTENT,
            )],
            vec![],
        );
        let failure = GenerateService::check(&sandbox.selection()).expect_err("missing");
        assert!(reason_codes(&failure).contains(&"structure.document-missing".to_owned()));
        assert_eq!(exit_of(&failure), 1);
        match &failure {
            ArtifactFailure::Drift(findings) => {
                assert_eq!(findings[0].verdict, DriftVerdict::Missing.as_str());
                assert_eq!(findings[0].path, "apps/api/src/planner/focus-task.ts");
            }
            other => panic!("expected drift, got {other:?}"),
        }
    });
}

#[test]
fn scaffolded_and_checked_drift_is_reported_without_blocking() {
    with_project(|sandbox| {
        sandbox.create_lock();
        std::fs::create_dir_all(sandbox.root.join(ARTIFACT_DIR)).expect("artifact dir");
        std::fs::write(
            sandbox.root.join(ARTIFACT_DIR).join("scaffolded.ts"),
            "owned by the implementation\n",
        )
        .expect("scaffolded bytes");
        std::fs::write(
            sandbox.root.join(ARTIFACT_DIR).join(ARTIFACT_NAME),
            "owned by the implementation\n",
        )
        .expect("checked bytes");
        author_manifest(
            sandbox,
            vec![
                artifact_value(
                    "planner.task_checked",
                    "apps/api/src/planner/focus-task.ts",
                    "source",
                    "checked",
                    "never written\n",
                ),
                artifact_value(
                    "planner.task_scaffolded",
                    "apps/api/src/planner/scaffolded.ts",
                    "source",
                    "scaffolded",
                    "owned by the implementation\n",
                ),
            ],
            vec![],
        );
        let receipt = GenerateService::check(&sandbox.selection()).expect("reported check");
        assert_eq!(receipt.verdict, "reported");
        assert_eq!(receipt.counts.reported, 1);
        assert_eq!(receipt.counts.clean, 1);
        assert_eq!(
            receipt.findings[0].verdict,
            DriftVerdict::ManualDrift.as_str()
        );
    });
}

#[test]
fn an_adapter_ref_under_an_unpublished_protocol_is_stale_never_silent() {
    with_project(|sandbox| {
        sandbox.create_lock();
        sandbox.write_artifact(ARTIFACT_CONTENT);
        author_manifest(
            sandbox,
            vec![adapter_bound_value(
                "planner.create_task",
                "apps/api/src/planner/focus-task.ts",
                ARTIFACT_CONTENT,
            )],
            vec![],
        );
        let failure = GenerateService::check(&sandbox.selection()).expect_err("stale");
        assert!(reason_codes(&failure).contains(&"lock.stale".to_owned()));
        match &failure {
            ArtifactFailure::Drift(findings) => {
                assert_eq!(findings[0].verdict, DriftVerdict::Stale.as_str());
            }
            other => panic!("expected drift, got {other:?}"),
        }
    });
}

#[test]
fn orphan_under_the_generated_root_blocks_and_outside_files_are_ignored() {
    with_project(|sandbox| {
        sandbox.create_lock();
        sandbox.write_artifact(ARTIFACT_CONTENT);
        author_manifest(
            sandbox,
            vec![artifact_value(
                "planner.create_task",
                "apps/api/src/planner/focus-task.ts",
                "source",
                "generated",
                ARTIFACT_CONTENT,
            )],
            vec![],
        );
        // Untracked file outside the managed root: ignored entirely.
        std::fs::write(sandbox.root.join("untracked.txt"), b"hello").expect("untracked");
        let receipt = GenerateService::check(&sandbox.selection()).expect("still clean");
        assert_eq!(receipt.verdict, "clean");
        // Unclaimed file inside the managed root: blocking orphan.
        let orphan = sandbox.write_generated("orphaned bytes\n");
        let failure = GenerateService::check(&sandbox.selection()).expect_err("orphan");
        assert!(reason_codes(&failure).contains(&"structure.runtime-unexpected-entry".to_owned()));
        assert_eq!(exit_of(&failure), 1);
        match &failure {
            ArtifactFailure::Drift(findings) => {
                assert_eq!(findings.len(), 1);
                assert_eq!(findings[0].verdict, DriftVerdict::Orphan.as_str());
                assert_eq!(findings[0].path, orphan);
            }
            other => panic!("expected drift, got {other:?}"),
        }
    });
}

#[test]
fn manifest_bookkeeping_itself_is_never_an_orphan() {
    with_project(|sandbox| {
        sandbox.create_lock();
        sandbox.write_artifact(ARTIFACT_CONTENT);
        author_manifest(
            sandbox,
            vec![artifact_value(
                "planner.create_task",
                "apps/api/src/planner/focus-task.ts",
                "source",
                "generated",
                ARTIFACT_CONTENT,
            )],
            vec![],
        );
        // The manifest document lives under the managed root but is
        // bookkeeping, not generated output: the check stays clean and a
        // clean plan enumerates nothing but real orphans.
        let receipt = GenerateService::check(&sandbox.selection()).expect("clean");
        assert_eq!(receipt.verdict, "clean");
        let plan = GenerateService::clean_plan(&sandbox.selection()).expect("plan");
        assert_eq!(plan.count, 0);
    });
}

// ---------------------------------------------------------------------------
// Wire refusals.
// ---------------------------------------------------------------------------

#[test]
fn noncanonical_manifest_bytes_are_refused_and_never_rewritten() {
    with_project(|sandbox| {
        sandbox.create_lock();
        author_manifest(
            sandbox,
            vec![artifact_value(
                "planner.create_task",
                "apps/api/src/planner/focus-task.ts",
                "source",
                "generated",
                ARTIFACT_CONTENT,
            )],
            vec![],
        );
        // Pretty-print the same document: semantically equal, noncanonical.
        let bytes = std::fs::read(sandbox.manifest_path()).expect("manifest");
        let document: Value = serde_json::from_slice(&bytes).expect("wire");
        let pretty = serde_json::to_string_pretty(&document).expect("pretty");
        let before = pretty.clone();
        std::fs::write(sandbox.manifest_path(), pretty).expect("rewrite");
        let failure = GenerateService::check(&sandbox.selection()).expect_err("noncanonical");
        assert_eq!(reason_codes(&failure), vec!["lock.noncanonical".to_owned()]);
        assert_eq!(exit_of(&failure), 1);
        let after = std::fs::read(sandbox.manifest_path()).expect("manifest after");
        assert_eq!(after, before.as_bytes(), "the checker never rewrites");
    });
}

#[test]
fn unsupported_manifest_schema_version_maps_to_exit_five() {
    with_project(|sandbox| {
        sandbox.create_lock();
        let path = sandbox.manifest_path();
        std::fs::create_dir_all(path.parent().expect("manifest dir")).expect("dir");
        std::fs::write(
            &path,
            "{\"schema_version\":\"lekalo/artifact-manifest/v9.0.0\"}\n",
        )
        .expect("future manifest");
        let failure = GenerateService::check(&sandbox.selection()).expect_err("future");
        assert_eq!(
            reason_codes(&failure),
            vec!["lock.unsupported-schema-version".to_owned()]
        );
        assert_eq!(exit_of(&failure), 5);
    });
}

#[test]
fn unsorted_or_duplicate_artifacts_are_reference_invalid() {
    with_project(|sandbox| {
        sandbox.create_lock();
        // "create_task" sorts before "render_task": this authored array is
        // already in violation of the closed sort order, so the parse
        // itself refuses before any file is touched.
        let one = artifact_value(
            "planner.render_task",
            "apps/api/src/planner/a.ts",
            "source",
            "generated",
            ARTIFACT_CONTENT,
        );
        let two = artifact_value(
            "planner.create_task",
            "apps/api/src/planner/b.ts",
            "source",
            "generated",
            ARTIFACT_CONTENT,
        );
        author_manifest(sandbox, vec![one, two], vec![]);
        let failure = GenerateService::check(&sandbox.selection()).expect_err("unsorted");
        assert_eq!(
            reason_codes(&failure),
            vec!["lock.reference-invalid".to_owned()]
        );
        assert_eq!(exit_of(&failure), 1);
    });
}

#[test]
fn source_map_revision_and_range_bounds_fail_closed() {
    with_project(|sandbox| {
        sandbox.create_lock();
        let content = ARTIFACT_CONTENT.repeat(3);
        sandbox.write_artifact(&content);
        let inputs = GenerateService::inputs(&sandbox.selection()).expect("inputs");
        let good_map = json!({
            "artifact": {
                "semantic_owner": "planner.create_task",
                "path": "apps/api/src/planner/focus-task.ts",
                "artifact_kind": "source",
            },
            "input_revision": inputs.revision,
            "entries": [
                {"semantic_id": "planner.create_task", "start": 0, "end": 16},
                {"semantic_id": "planner.task", "start": 16, "end": 17},
            ],
        });
        author_manifest(
            sandbox,
            vec![artifact_value(
                "planner.create_task",
                "apps/api/src/planner/focus-task.ts",
                "source",
                "generated",
                &content,
            )],
            vec![good_map],
        );
        GenerateService::check(&sandbox.selection()).expect("valid map");

        // A foreign input revision refuses the whole map.
        let bytes = std::fs::read(sandbox.manifest_path()).expect("manifest");
        let mut document: Value = serde_json::from_slice(&bytes).expect("wire");
        document["source_maps"][0]["input_revision"] =
            json!(format!("sha256:{}", sha256_hex(b"foreign")));
        restamp_and_write(sandbox, &document);
        let failure = GenerateService::check(&sandbox.selection()).expect_err("foreign revision");
        assert_eq!(
            reason_codes(&failure),
            vec!["lock.reference-invalid".to_owned()]
        );

        // Re-author with a good revision and an out-of-range end instead.
        let inputs = GenerateService::inputs(&sandbox.selection()).expect("inputs");
        let bad_map = json!({
            "artifact": {
                "semantic_owner": "planner.create_task",
                "path": "apps/api/src/planner/focus-task.ts",
                "artifact_kind": "source",
            },
            "input_revision": inputs.revision,
            "entries": [{"semantic_id": "planner.create_task", "start": 0, "end": 999_999}],
        });
        author_manifest(
            sandbox,
            vec![artifact_value(
                "planner.create_task",
                "apps/api/src/planner/focus-task.ts",
                "source",
                "generated",
                &content,
            )],
            vec![bad_map],
        );
        let failure = GenerateService::check(&sandbox.selection()).expect_err("range bound");
        assert_eq!(
            reason_codes(&failure),
            vec!["lock.reference-invalid".to_owned()]
        );
    });
}

fn restamp_and_write(sandbox: &Sandbox, document: &Value) {
    let mut draft = document.clone();
    draft
        .as_object_mut()
        .expect("object")
        .remove("manifest_digest");
    let mut final_doc = document.clone();
    final_doc["manifest_digest"] = json!(format!(
        "sha256:{}",
        sha256_hex(&serde_json::to_vec(&draft).expect("wire"))
    ));
    std::fs::write(
        sandbox.manifest_path(),
        serde_json::to_vec(&final_doc).expect("wire"),
    )
    .expect("rewrite");
}

// ---------------------------------------------------------------------------
// Safe clean.
// ---------------------------------------------------------------------------

#[test]
fn clean_plan_and_confirmed_apply_delete_only_the_enumerated_orphan() {
    with_project(|sandbox| {
        sandbox.create_lock();
        sandbox.write_artifact(ARTIFACT_CONTENT);
        author_manifest(
            sandbox,
            vec![artifact_value(
                "planner.create_task",
                "apps/api/src/planner/focus-task.ts",
                "source",
                "generated",
                ARTIFACT_CONTENT,
            )],
            vec![],
        );
        let orphan_path = sandbox.write_generated("orphaned bytes\n");

        let plan = GenerateService::clean_plan(&sandbox.selection()).expect("plan");
        assert_eq!(plan.count, 1);
        assert_eq!(plan.files[0].path, orphan_path);
        assert!(plan.plan_id.starts_with("sha256:"));
        // The preview wrote nothing and the orphan is still there.
        assert!(sandbox.root.join(&orphan_path).is_file());

        // A plain mutating clean is refused.
        let failure = GenerateService::clean_apply(&sandbox.selection(), "").expect_err("refused");
        let _ = failure;

        let receipt =
            GenerateService::clean_apply(&sandbox.selection(), &plan.plan_id).expect("applied");
        assert_eq!(receipt.deleted, 1);
        assert!(receipt.changed);
        assert!(!sandbox.root.join(&orphan_path).exists());
    });
}

#[test]
fn altered_orphan_aborts_with_zero_deletes() {
    with_project(|sandbox| {
        sandbox.create_lock();
        let orphan_path = sandbox.write_generated("first bytes\n");
        let plan = GenerateService::clean_plan(&sandbox.selection()).expect("plan");
        std::fs::write(sandbox.root.join(&orphan_path), b"changed bytes").expect("alter");
        let failure =
            GenerateService::clean_apply(&sandbox.selection(), &plan.plan_id).expect_err("race");
        assert!(matches!(failure, ArtifactFailure::PlanChanged));
        assert!(sandbox.root.join(&orphan_path).is_file(), "zero deletes");
        assert_eq!(exit_of(&failure), 1);
    });
}

#[test]
fn foreign_plan_identity_yields_plan_changed_with_zero_deletes() {
    with_project(|sandbox| {
        sandbox.create_lock();
        let orphan_path = sandbox.write_generated("orphan\n");
        let _plan = GenerateService::clean_plan(&sandbox.selection()).expect("plan");
        let other_id = format!("sha256:{}", sha256_hex(b"foreign-plan"));
        let failure =
            GenerateService::clean_apply(&sandbox.selection(), &other_id).expect_err("foreign");
        assert!(matches!(failure, ArtifactFailure::PlanChanged));
        assert!(sandbox.root.join(&orphan_path).is_file());
    });
}

#[test]
fn empty_plan_applies_to_an_unchanged_receipt() {
    with_project(|sandbox| {
        sandbox.create_lock();
        let plan = GenerateService::clean_plan(&sandbox.selection()).expect("empty plan");
        assert_eq!(plan.count, 0);
        let receipt =
            GenerateService::clean_apply(&sandbox.selection(), &plan.plan_id).expect("apply");
        assert_eq!(receipt.deleted, 0);
        assert!(!receipt.changed);
    });
}

// ---------------------------------------------------------------------------
// Adversarial paths and privacy.
// ---------------------------------------------------------------------------

#[test]
#[cfg(unix)]
fn symlink_inside_the_managed_root_is_a_denied_path_refusal() {
    with_project(|sandbox| {
        sandbox.create_lock();
        let target = sandbox.write_generated("real bytes\n");
        let link = sandbox.root.join(GENERATED_ROOT).join("link.txt");
        std::os::unix::fs::symlink(sandbox.root.join(&target), &link).expect("symlink");
        let failure = GenerateService::check(&sandbox.selection()).expect_err("link");
        assert!(matches!(
            failure,
            ArtifactFailure::Structure { denied: true, .. }
        ));
        assert_eq!(exit_of(&failure), 3);
    });
}

#[test]
fn artifact_paths_from_the_wire_pass_the_accepted_path_policy() {
    // Absolute, traversal, device, and backslash spellings can never form
    // an ArtifactPath, so a manifest carrying them is a shape refusal.
    with_project(|sandbox| {
        sandbox.create_lock();
        for hostile in [
            "/etc/passwd",
            "../outside.ts",
            "apps/api/C:\\evil.ts",
            "apps/api/CON.ts",
        ] {
            let _ = std::fs::remove_file(sandbox.manifest_path());
            let _ = sandbox.write_artifact(ARTIFACT_CONTENT);
            author_manifest(
                sandbox,
                vec![artifact_value(
                    "planner.create_task",
                    hostile,
                    "source",
                    "generated",
                    "",
                )],
                vec![],
            );
            let failure = GenerateService::check(&sandbox.selection()).expect_err(hostile);
            assert!(
                matches!(failure, ArtifactFailure::ManifestInvalid)
                    || matches!(failure, ArtifactFailure::Structure { .. })
                    || matches!(failure, ArtifactFailure::Drift(_)),
                "hostile path {hostile} produced {failure:?}"
            );
        }
    });
}

#[test]
fn receipts_and_diagnostics_carry_no_native_paths() {
    with_project(|sandbox| {
        sandbox.create_lock();
        sandbox.write_artifact(ARTIFACT_CONTENT);
        author_manifest(
            sandbox,
            vec![artifact_value(
                "planner.create_task",
                "apps/api/src/planner/focus-task.ts",
                "source",
                "generated",
                ARTIFACT_CONTENT,
            )],
            vec![],
        );
        let receipt = GenerateService::check(&sandbox.selection()).expect("check");
        let wire = serde_json::to_string(&receipt).expect("wire");
        let absolute = sandbox.root.canonicalize().expect("absolute root");
        assert!(!wire.contains(&absolute.to_string_lossy().to_string()));
        assert!(!wire.contains('\\'), "logical paths only: {wire}");
    });
}
