<?php
/**
 * The operations emitter (issue #59): the mapped operations inventory
 * becomes deterministic PHP bytes — handler classes with exactly one
 * public business entrypoint, narrow per-operation ports, typed error
 * classes, shared ActorContext/TransactionPort/OperationError support,
 * the classmap, and the custody sidecar. Pure: no filesystem, no
 * clock, no environment. Identical inputs and pins emit identical
 * bytes across roots.
 */

/** The file header of one emitted operations artifact. */
function php_operations_file_header(array $context, string $namespace, string $semanticId): string
{
    $lines = [
        '<?php',
        '',
        'declare(strict_types=1);',
        '',
        '// Generated by ' . ADAPTER_ID . '@' . ADAPTER_VERSION . ' (operations generator, issue #59).',
        '// From dev.lekalo.ir@0.2.16 input ' . $context['irDigest'] . '.',
        '// Semantic id: ' . $semanticId . '.',
        '// Do not edit: regenerate with `lekalo generate`.',
        '',
        'namespace ' . $namespace . ';',
    ];
    return implode("\n", $lines);
}

/** One operations shared-support class text. */
function php_operations_actor_context_text(array $context): string
{
    $lines = [
        php_operations_file_header($context, $context['namespacePrefix'], 'php-operations/actor-context'),
        '',
        'final readonly class ActorContext',
        '{',
        '    /** @var array<string, string> */',
        '    private array $scopes;',
        '',
        '    /**',
        '     * @param array<string, string> $scopes the declared tenant/owner',
        '     *     dimensions; request payloads never become authority',
        '     */',
        '    public function __construct(',
        '        public readonly string $actorId,',
        '        array $scopes = [],',
        '    ) {',
        '        $this->scopes = $scopes;',
        '    }',
        '',
        '    /** The declared scope dimension, or null when absent. */',
        '    public function scope(string $key): ?string',
        '    {',
        '        return $this->scopes[$key] ?? null;',
        '    }',
        '',
        '    /** @return array<string, string> */',
        '    public function scopes(): array',
        '    {',
        '        return $this->scopes;',
        '    }',
        '',
        '    /** One derived context with one more declared scope dimension. */',
        '    public function with(string $key, string $value): self',
        '    {',
        '        $next = $this->scopes;',
        '        $next[$key] = $value;',
        '        return new self($this->actorId, $next);',
        '    }',
        '}',
    ];
    return implode("\n", $lines) . "\n";
}

/** The shared transaction port text. */
function php_operations_transaction_port_text(array $context): string
{
    $lines = [
        php_operations_file_header($context, $context['namespacePrefix'], 'php-operations/transaction-port'),
        '',
        'interface TransactionPort',
        '{',
        '    /**',
        '     * Run the body inside exactly one transaction of the bound',
        '     * connection: commit on a normal return, roll back and rethrow',
        '     * on any throwable. A typed OperationError thrown inside the',
        '     * body must surface as the rolled-back domain failure, never as',
        '     * a committed half-state.',
        '     */',
        '    public function run(callable $body): mixed;',
        '}',
    ];
    return implode("\n", $lines) . "\n";
}

/** The shared typed-error base class text. */
function php_operations_operation_error_text(array $context): string
{
    $lines = [
        php_operations_file_header($context, $context['namespacePrefix'], 'php-operations/operation-error'),
        '',
        'abstract class OperationError extends \\RuntimeException',
        '{',
        '}',
    ];
    return implode("\n", $lines) . "\n";
}

/**
 * Emit every artifact of one mapped operations inventory. `$input` is
 * `{projectId, mapped, context, root, namespacePrefix, definitions,
 * typesIndex}`. Returns `{files, sidecar}`; every file row carries
 * path/text/digest/role/fqn/lifecycle.
 */
function php_emit_operations(array $input): array
{
    $context = $input['context'];
    $mapped = $input['mapped'];
    $definitions = $input['definitions'];
    $typesIndex = $input['typesIndex'];
    $prefix = $input['namespacePrefix'];
    $root = $input['root'];
    $files = [];
    foreach ($mapped['files'] as $file) {
        if (($file['role'] ?? '') === 'errors' && !isset($file['text'])) {
            // The typed error class: owned by its first declaring
            // operation, in the module's Errors namespace.
            $fqn = (string) $file['fqn'];
            $namespace = substr($fqn, 0, (int) strrpos($fqn, '\\'));
            $text = php_operations_error_text(
                ['id' => (string) ($file['operation'] ?? 'php-operations')],
                ['fqn' => $fqn],
                $namespace,
                $context,
            );
            $files[] = array_merge($file, [
                'text' => $text,
                'digest' => 'sha256:' . hash('sha256', $text),
            ]);
            continue;
        }
        $files[] = $file;
    }
    foreach ($mapped['operations'] as $operation) {
        foreach (php_operations_record_texts($operation, $context, $definitions, $typesIndex, $prefix, $root) as $file) {
            $files[] = $file;
        }
    }
    $classmapText = php_operations_classmap_text($files, $context, $root);
    $files[] = [
        'path' => $root . '/classmap.php',
        'text' => $classmapText,
        'digest' => 'sha256:' . hash('sha256', $classmapText),
        'role' => 'classmap',
        'lifecycle' => $root === PHP_OPERATIONS_SCAFFOLD_ROOT ? 'scaffolded' : 'generated',
    ];
    $sidecarText = php_operations_sidecar_text($input['projectId'], $mapped, $files, $context, $root);
    $files[] = [
        'path' => $root . '/operations.map.json',
        'text' => $sidecarText,
        'digest' => 'sha256:' . hash('sha256', $sidecarText),
        'role' => 'sidecar',
        'lifecycle' => $root === PHP_OPERATIONS_SCAFFOLD_ROOT ? 'scaffolded' : 'generated',
    ];
    usort($files, static fn (array $left, array $right): int => strcmp((string) $left['path'], (string) $right['path']));
    return ['files' => $files];
}

/** Every emitted text of one mapped operation record. */
function php_operations_record_texts(
    array $operation,
    array $context,
    array $definitions,
    array $typesIndex,
    string $prefix,
    string $root,
): array {
    $files = [];
    $lifecycle = $root === PHP_OPERATIONS_SCAFFOLD_ROOT ? 'scaffolded' : 'generated';
    $moduleSegment = ucfirst(php_types_module_of($operation['id']));
    $namespace = $prefix . '\\' . $moduleSegment;
    foreach ($operation['artifacts'] as $artifact) {
        if ($artifact['role'] === 'declared') {
            continue;
        }
        $artifactNamespace = $artifact['role'] === 'errors'
            ? $prefix . '\\' . $moduleSegment . '\\Errors'
            : $namespace;
        $text = match ($artifact['role']) {
            'handler' => php_operations_handler_text($operation, $context, $definitions, $typesIndex, $namespace, $artifact),
            'ports' => php_operations_port_text($operation, $artifact, $definitions, $typesIndex, $artifactNamespace, $context),
            'repository' => php_operations_repository_text($operation, $artifact, $definitions, $typesIndex, $namespace, $context),
            'errors' => php_operations_error_text($operation, $artifact, $artifactNamespace, $context),
            default => null,
        };
        if ($text === null) {
            continue;
        }
        $files[] = [
            'path' => $artifact['path'],
            'text' => $text,
            'digest' => 'sha256:' . hash('sha256', $text),
            'role' => $artifact['role'],
            'fqn' => $artifact['fqn'],
            'lifecycle' => $lifecycle,
            'operation' => $operation['id'],
        ];
    }
    return $files;
}

/** The handler class text of one mapped record. */
function php_operations_handler_text(
    array $operation,
    array $context,
    array $definitions,
    array $typesIndex,
    string $namespace,
    array $artifact,
): string {
    $actor = '\\' . $context['namespacePrefix'] . '\\ActorContext';
    $inputFqn = '\\' . $operation['input']['fqn'];
    $returnType = $operation['result'] === null ? 'void' : '\\' . $operation['result']['fqn'];
    $lines = [
        php_operations_file_header($context, $namespace, $operation['id']),
        '',
        'final readonly class ' . php_types_entry_class(['fqn' => (string) $artifact['fqn']]),
        '{',
        '    public function __construct(',
    ];
    foreach ($operation['ports'] as $port) {
        $lines[] = '        private readonly \\' . $port['fqn'] . ' $' . $port['slot'] . ',';
    }
    $lines[] = '    ) {';
    $lines[] = '    }';
    $lines[] = '';
    $lines[] = '    /** The one public business entrypoint of this operation. */';
    $lines[] = '    public function handle(' . $inputFqn . ' $input, ' . $actor . ' $actor): ' . $returnType;
    $lines[] = '    {';
    foreach (php_operations_body_lines($operation, $definitions, $typesIndex, $context) as $line) {
        $lines[] = $line;
    }
    $lines[] = '    }';
    $lines[] = '}';
    return implode("\n", $lines) . "\n";
}

/** The indented body lines of one handler. */
function php_operations_body_lines(array $operation, array $definitions, array $typesIndex, array $context): array
{
    $recipe = $operation['recipe'];
    if ($operation['mode'] === 'scaffold-once') {
        return [
            '        // The scaffold is the explicit unimplemented failure: the',
            '        // signature and dependencies are generated, the body is',
            '        // maintained from here on (issue #59).',
            "        throw new \\LogicException('" . $operation['id'] . ": the maintained operation body is not implemented yet (issue #59).');",
        ];
    }
    if (($recipe['kind'] ?? '') === 'port-delegation') {
        $delegateSlot = php_operations_slot_of((string) $recipe['port']);
        $call = '$this->' . $delegateSlot . '->' . (string) $recipe['method'] . '($input, $actor)';
        if ($operation['result'] === null) {
            return ['        ' . $call . ';'];
        }
        return ['        return ' . $call . ';'];
    }
    // The bounded single-entity-update recipe.
    $entityId = (string) $recipe['entity'];
    $entityVar = '$' . lcfirst(php_types_stem_of($entityId, 'plain'));
    $repositorySlot = php_operations_slot_of(php_types_stem_of($entityId, 'plain') . 'Repository');
    $body = [];
    $unit = $operation['result'] === null;
    $body[] = '        ' . ($unit ? '' : 'return ') . '$this->transactions->run(function () use ($input, $actor)' . ($unit ? ': void' : ': mixed') . ' {';
    if ($operation['policyId'] !== null) {
        $body[] = '            $this->' . php_operations_slot_of(php_types_stem_of($operation['id'], 'plain') . 'Policy')
            . '->authorize($input, $actor);';
    }
    $body[] = '            ' . $entityVar . ' = $this->' . $repositorySlot . '->find($input->'
        . php_types_property_of((string) $recipe['key']) . ');';
    $body[] = '            if (' . $entityVar . ' === null) {';
    $body[] = '                throw new ' . php_operations_error_class_of((string) $recipe['missingBehavior']['error'], $operation) . '();';
    $body[] = '            }';
    foreach ($recipe['preconditions'] as $precondition) {
        $body[] = '            ' . php_operations_precondition_statement(
            $precondition,
            $recipe,
            $definitions,
            $typesIndex,
            $entityVar,
            $operation,
            $context,
        );
        $body[] = '                throw new ' . php_operations_error_class_of((string) $precondition['error'], $operation) . '();';
        $body[] = '            }';
    }
    $body[] = '            ' . $entityVar . 'Updated = ' . php_operations_rebuild_expr($recipe, $definitions, $typesIndex, $entityVar, $operation, $context) . ';';
    $body[] = '            $this->' . $repositorySlot . '->save(' . $entityVar . 'Updated);';
    foreach ($recipe['emit'] as $emission) {
        $slot = php_operations_slot_of(php_types_stem_of($operation['id'], 'plain') . 'Events');
        $method = lcfirst(php_types_stem_of((string) $emission['event'], 'plain'));
        $body[] = '            $this->' . $slot . '->' . $method . '('
            . php_operations_event_expr($emission, $recipe, $definitions, $typesIndex, $entityVar, $operation, $context) . ');';
    }
    if (!$unit) {
        $body[] = '            return null;';
    }
    $body[] = '        });';
    return $body;
}

/**
 * The fully-qualified spelling of one declared error id within one
 * record: the typed error classes live in the module's `Errors`
 * namespace, so the handler body must qualify them — an unqualified
 * reference inside the operation namespace would resolve to a class
 * that does not exist.
 */
function php_operations_error_class_of(string $errorId, array $operation): string
{
    foreach ($operation['errors'] as $error) {
        if ($error['id'] === $errorId) {
            return '\\' . (string) $error['fqn'];
        }
    }
    // The join guarantees membership; this is a kernel bug guard.
    throw new LogicException('undeclared error: ' . $errorId);
}

/** The leaf ref id of one closed IR type expression, or null. */
function php_operations_leaf_ref(mixed $typeExpr): ?string
{
    if (is_array($typeExpr) && isset($typeExpr['ref'])) {
        return (string) $typeExpr['ref'];
    }
    if (is_array($typeExpr) && isset($typeExpr['optional'])) {
        return php_operations_leaf_ref($typeExpr['optional']);
    }
    if (is_array($typeExpr) && isset($typeExpr['list'])) {
        return php_operations_leaf_ref($typeExpr['list']);
    }
    return null;
}

/** One typed comparison statement for one precondition. */
function php_operations_precondition_statement(
    array $precondition,
    array $recipe,
    array $definitions,
    array $typesIndex,
    string $entityVar,
    array $operation,
    array $context,
): string {
    $field = (string) $precondition['field'];
    $targetExpr = php_operations_entity_field_expr((string) $recipe['entity'], $field, $definitions);
    $leaf = php_operations_leaf_ref($targetExpr);
    $kind = $leaf !== null ? (string) ($definitions[$leaf]['kind'] ?? '') : '';
    $actual = $entityVar . '->' . php_types_property_of($field);
    $expected = php_operations_operand_expr(
        $precondition['equals'],
        $targetExpr,
        $definitions,
        $typesIndex,
        $recipe,
        $operation,
        $context,
    );
    $compare = $kind === 'enum'
        ? $actual . ' !== ' . $expected
        : '!' . $actual . '->equals(' . $expected . ')';
    return 'if (' . $compare . ') {';
}

/** The assignment/rebuild expression of the update recipe. */
function php_operations_rebuild_expr(
    array $recipe,
    array $definitions,
    array $typesIndex,
    string $entityVar,
    array $operation,
    array $context,
): string {
    $entityId = (string) $recipe['entity'];
    $entityFqn = (string) $typesIndex[$entityId]['fqn'];
    $args = [];
    foreach ($definitions[$entityId]['fields'] as $field) {
        $name = (string) $field['name'];
        $handled = false;
        foreach ($recipe['assignments'] as $assignment) {
            if ($assignment['field'] === $name) {
                $args[] = php_operations_operand_expr(
                    $assignment['value'],
                    $field['type'],
                    $definitions,
                    $typesIndex,
                    $recipe,
                    $operation,
                    $context,
                );
                $handled = true;
                break;
            }
        }
        if ($handled) {
            continue;
        }
        // The identity and every kept field carry over from the read.
        $args[] = $entityVar . '->' . php_types_property_of($name);
    }
    return 'new \\' . $entityFqn . '(' . implode(', ', $args) . ')';
}

/** One event construction expression. */
function php_operations_event_expr(
    array $emission,
    array $recipe,
    array $definitions,
    array $typesIndex,
    string $entityVar,
    array $operation,
    array $context,
): string {
    $eventId = (string) $emission['event'];
    $args = [];
    foreach ($definitions[$eventId]['payload'] as $field) {
        $name = (string) $field['name'];
        $args[] = php_operations_operand_expr(
            $emission['payload'][$name],
            $field['type'],
            $definitions,
            $typesIndex,
            $recipe,
            $operation,
            $context,
        );
    }
    return 'new \\' . (string) $typesIndex[$eventId]['fqn'] . '(' . implode(', ', $args) . ')';
}

/**
 * One closed operand expression. `$targetExpr` is the target field's
 * IR type expression; it types literal operands exactly.
 */
function php_operations_operand_expr(
    array $operand,
    mixed $targetExpr,
    array $definitions,
    array $typesIndex,
    array $recipe,
    array $operation,
    array $context,
): string {
    if (isset($operand['fromInput'])) {
        return '$input->' . php_types_property_of((string) $operand['fromInput']);
    }
    if (isset($operand['fromEntity'])) {
        $entityVar = '$' . lcfirst(php_types_stem_of((string) $recipe['entity'], 'plain'));
        return $entityVar . '->' . php_types_property_of((string) $operand['fromEntity']);
    }
    if (isset($operand['enumCase'])) {
        $enumId = (string) $operand['enumCase']['type'];
        $value = (string) $operand['enumCase']['value'];
        return '\\' . $typesIndex[$enumId]['fqn'] . '::' . php_operations_enum_case_of($definitions[$enumId], $value);
    }
    // A literal wraps in the exact scalar wrapper of the target leaf.
    $leaf = php_operations_leaf_ref($targetExpr);
    $fqn = $leaf !== null ? ($typesIndex[$leaf]['fqn'] ?? null) : null;
    if (is_string($fqn)) {
        $literal = $operand['literal'];
        $spelling = is_string($literal) ? php_types_string_literal($literal) : var_export($literal, true);
        return '\\' . $fqn . '::from(' . $spelling . ')';
    }
    // The join guarantees a typed scalar target; kernel bug guard.
    throw new LogicException('literal operand without a typed scalar target');
}

/** The declared case name of one enum value, derived exactly like the type map. */
function php_operations_enum_case_of(array $definition, string $value): string
{
    foreach ($definition['values'] as $candidate) {
        if ((string) $candidate['value'] === $value) {
            return ucfirst((string) preg_replace('/[^a-zA-Z0-9]/', '_', $value));
        }
    }
    throw new LogicException('undeclared enum value: ' . $value);
}

/** The type expression of one entity field. */
function php_operations_entity_field_expr(string $entityId, string $field, array $definitions): mixed
{
    foreach ($definitions[$entityId]['fields'] as $candidate) {
        if ((string) $candidate['name'] === $field) {
            return $candidate['type'];
        }
    }
    throw new LogicException('unknown entity field: ' . $field);
}

/** One narrow port interface (or query input DTO) text. */
function php_operations_port_text(
    array $operation,
    array $artifact,
    array $definitions,
    array $typesIndex,
    string $namespace,
    array $context,
): string {
    $actor = '\\' . $context['namespacePrefix'] . '\\ActorContext';
    $inputFqn = '\\' . $operation['input']['fqn'];
    $class = php_types_entry_class(['fqn' => (string) $artifact['fqn']]);
    // The query input DTO: an explicit empty input, never a silent null.
    if ($operation['kind'] === 'query' && str_ends_with((string) $artifact['fqn'], 'Input')) {
        $lines = [
            php_operations_file_header($context, $namespace, $operation['id']),
            '',
            'final readonly class ' . $class,
            '{',
            '    public function __construct()',
            '    {',
            '    }',
            '}',
        ];
        return implode("\n", $lines) . "\n";
    }
    $role = null;
    foreach ($operation['ports'] as $port) {
        if ($port['fqn'] === $artifact['fqn']) {
            $role = $port['role'];
        }
    }
    $lines = [
        php_operations_file_header($context, $namespace, $operation['id']),
        '',
        'interface ' . $class,
        '{',
    ];
    if ($role === 'policy') {
        $lines[] = '    /** The declared authorization gate; a denial throws one typed error. */';
        $lines[] = '    public function authorize(' . $inputFqn . ' $input, ' . $actor . ' $actor): void;';
    } elseif ($role === 'events') {
        foreach ($operation['recipe']['emit'] ?? [] as $emission) {
            $eventFqn = '\\' . $typesIndex[(string) $emission['event']]['fqn'];
            $method = lcfirst(php_types_stem_of((string) $emission['event'], 'plain'));
            $lines[] = '    public function ' . $method . '(' . $eventFqn . ' $event): void;';
        }
    } elseif ($role === 'delegation') {
        $returnType = $operation['result'] === null ? 'void' : '\\' . $operation['result']['fqn'];
        $method = (string) $operation['recipe']['method'];
        $lines[] = '    /** The one maintained body this managed wrapper delegates to. */';
        $lines[] = '    public function ' . $method . '(' . $inputFqn . ' $input, ' . $actor . ' $actor): ' . $returnType . ';';
    }
    $lines[] = '}';
    return implode("\n", $lines) . "\n";
}

/** One narrow repository interface text. */
function php_operations_repository_text(
    array $operation,
    array $artifact,
    array $definitions,
    array $typesIndex,
    string $namespace,
    array $context,
): string {
    $repository = $operation['repository'];
    $entityFqn = '\\' . $repository['entityFqn'];
    $keyId = php_operations_leaf_ref(
        php_operations_entity_field_expr((string) $repository['entity'], (string) $repository['identity'], $definitions),
    );
    $keyFqn = '\\' . $typesIndex[(string) $keyId]['fqn'];
    $lines = [
        php_operations_file_header($context, $namespace, $operation['id']),
        '',
        'interface ' . php_types_entry_class(['fqn' => (string) $artifact['fqn']]),
        '{',
        '    public function find(' . $keyFqn . ' $key): ?' . $entityFqn . ';',
        '',
        '    public function save(' . $entityFqn . ' $entity): void;',
        '}',
    ];
    return implode("\n", $lines) . "\n";
}

/** One typed error class text. */
function php_operations_error_text(
    array $operation,
    array $artifact,
    string $namespace,
    array $context,
): string {
    $lines = [
        php_operations_file_header($context, $namespace, $operation['id']),
        '',
        'final class ' . php_types_entry_class(['fqn' => (string) $artifact['fqn']]),
        '    extends \\' . $context['namespacePrefix'] . '\\OperationError',
        '{',
        '}',
    ];
    return implode("\n", $lines) . "\n";
}

/** The deterministic classmap text over the collected files. */
function php_operations_classmap_text(array $files, array $context, string $root): string
{
    $entries = [];
    foreach ($files as $file) {
        if (!isset($file['fqn']) || $file['role'] === 'sidecar') {
            continue;
        }
        $relative = substr((string) $file['path'], strlen($root) + 1);
        $entries[(string) $file['fqn']] = $relative;
    }
    ksort($entries);
    $lines = [
        '<?php',
        '',
        'declare(strict_types=1);',
        '',
        '// Generated by ' . ADAPTER_ID . '@' . ADAPTER_VERSION . ' (operations generator, issue #59).',
        '// The deterministic class map: fully-qualified name => root-relative path.',
        '// The loading authority of the generated operations tree - no runtime',
        '// registration magic, no Composer scan.',
        '',
        'return [',
    ];
    foreach ($entries as $fqn => $relative) {
        $lines[] = '    ' . php_types_string_literal($fqn) . ' => ' . php_types_string_literal($relative) . ',';
    }
    $lines[] = '];';
    return implode("\n", $lines) . "\n";
}

/** The canonical sidecar bytes over the complete inventory. */
function php_operations_sidecar_text(
    string $projectId,
    array $mapped,
    array $files,
    array $context,
    string $root,
): string {
    $operations = [];
    foreach ($mapped['operations'] as $operation) {
        $entry = [
            'id' => $operation['id'],
            'kind' => $operation['kind'],
            'mode' => $operation['mode'],
        ];
        if ($operation['mode'] === 'managed') {
            $entry['recipe'] = $operation['recipeKind'];
        }
        $entry['entry'] = [
            'fqn' => $operation['entry']['fqn'],
            'method' => $operation['entry']['method'],
            'path' => $operation['entry']['path'],
        ];
        $entry['input'] = ['fqn' => $operation['input']['fqn']];
        if ($operation['result'] !== null) {
            $entry['result'] = ['fqn' => $operation['result']['fqn']];
        }
        if ($operation['errors'] !== []) {
            $entry['errors'] = array_map(
                static fn (array $error): array => ['id' => $error['id'], 'fqn' => $error['fqn']],
                $operation['errors'],
            );
        }
        if ($operation['ports'] !== []) {
            $entry['ports'] = array_map(
                static fn (array $port): array => array_filter([
                    'name' => $port['name'],
                    'role' => $port['role'],
                    'entity' => $port['entity'] ?? null,
                ], static fn (mixed $value): bool => $value !== null),
                $operation['ports'],
            );
        }
        if ($operation['policyId'] !== null) {
            $entry['policy'] = $operation['policyId'];
        }
        $entry['transaction'] = $operation['transaction'];
        $entry['effects'] = $operation['effects'];
        $operations[] = $entry;
    }
    $artifacts = [];
    foreach ($mapped['operations'] as $operation) {
        foreach ($operation['artifacts'] as $artifact) {
            if ($artifact['role'] !== 'declared') {
                continue;
            }
            $artifacts[] = [
                'path' => $artifact['path'],
                'role' => 'declared',
                'lifecycle' => 'checked',
            ];
        }
    }
    foreach ($files as $file) {
        $row = [
            'path' => substr((string) $file['path'], strlen($root) + 1),
            'role' => $file['role'],
            'lifecycle' => $file['lifecycle'],
        ];
        if (isset($file['operation'])) {
            $row['operation'] = $file['operation'];
        }
        if (isset($file['digest'])) {
            $row['digest'] = $file['digest'];
        }
        $artifacts[] = $row;
    }
    usort($artifacts, static fn (array $left, array $right): int => strcmp((string) $left['path'], (string) $right['path']));
    $document = [
        'schemaVersion' => PHP_OPERATIONS_MAP_SCHEMA_VERSION,
        'identity' => PHP_OPERATIONS_MAP_IDENTITY,
        'projectId' => $projectId,
        'adapter' => [
            'id' => ADAPTER_ID,
            'version' => ADAPTER_VERSION,
            'digest' => sha256_digest(ADAPTER_ID . '@' . ADAPTER_VERSION),
        ],
        'digests' => [
            'ir' => $context['irDigest'],
            'input' => $context['inputDigest'],
            'typesInput' => $context['typesInputDigest'],
        ],
        'operations' => $operations,
        'artifacts' => $artifacts,
    ];
    return php_types_canonical_json($document) . "\n";
}
