<?php

/**
 * The routes emitter (issue #60): the mapped routes inventory becomes
 * deterministic PHP bytes — the route registrations, thin
 * decode/delegate/encode controllers, typed request bindings, the
 * shared envelope and validation primitives, the explicit error-to-HTTP
 * map, the digest-bound OpenAPI projection, the classmap, and the
 * custody sidecar. Pure: no filesystem, no clock, no environment.
 * Identical inputs and pins emit identical bytes across roots.
 *
 * The controllers are thin wrappers and nothing else: they decode the
 * transport surface into the #58 typed input, bind the actor, invoke
 * the one operation entrypoint, encode the success projection, and map
 * exactly the declared typed errors through the declared table. There
 * is no catch-all: any throwable outside the declared table propagates
 * to the application's own exception handling, unmodified.
 */

/** The file header of one emitted routes artifact. */
function php_routes_file_header(array $context, string $namespace, string $semanticId): string
{
    $lines = [
        '<?php',
        '',
        'declare(strict_types=1);',
        '',
        '// Generated by ' . ADAPTER_ID . '@' . ADAPTER_VERSION . ' (routes generator, issue #60).',
        '// From dev.lekalo.ir@0.2.16 input ' . $context['irDigest'] . '.',
        '// Semantic id: ' . $semanticId . '.',
        '// Do not edit: regenerate with `lekalo generate`.',
        '',
        'namespace ' . $namespace . ';',
    ];
    return implode("\n", $lines);
}

/**
 * Emit every artifact of one mapped routes inventory. `$input` is
 * `{projectId, mapped, context, openapiBytes, root}`. Returns `files`;
 * every file row carries path/text/digest/role/fqn/lifecycle.
 */
function php_emit_routes(array $input): array
{
    $context = $input['context'];
    $mapped = $input['mapped'];
    $root = $input['root'];
    $namespace = $context['namespacePrefix'];
    $files = [];

    // The shared boundary primitives: the canonical envelope encoder,
    // the typed validation refusal, and the declared error-to-HTTP map.
    $shared = [
        ['http-envelope.php', 'HttpEnvelope', 'envelope', php_routes_http_envelope_text($context, $namespace, (string) $context['operationsNamespacePrefix'])],
        ['request-validation-error.php', 'RequestValidationError', 'validation-error', php_routes_validation_error_text($context, $namespace)],
        ['error-http-map.php', 'ErrorHttpMap', 'error-map', php_routes_error_http_map_text($context, $namespace, $mapped['routes'])],
    ];
    foreach ($shared as [$fileName, $class, $role, $text]) {
        $files[] = [
            'path' => $root . '/' . $fileName,
            'text' => $text,
            'digest' => 'sha256:' . hash('sha256', $text),
            'role' => $role,
            'fqn' => $namespace . '\\' . $class,
            'lifecycle' => 'generated',
        ];
    }

    // The per-route wrappers: request binding plus thin controller.
    foreach ($mapped['routes'] as $route) {
        if ($route['mode'] !== 'managed') {
            continue;
        }
        if ($route['request'] !== null) {
            $text = php_routes_request_text($context, $namespace, $route);
            $files[] = [
                'path' => $route['request']['path'],
                'text' => $text,
                'digest' => 'sha256:' . hash('sha256', $text),
                'role' => 'request',
                'fqn' => $route['request']['fqn'],
                'lifecycle' => 'generated',
            ];
        }
        $text = php_routes_controller_text($context, $namespace, $route);
        $files[] = [
            'path' => $route['controller']['path'],
            'text' => $text,
            'digest' => 'sha256:' . hash('sha256', $text),
            'role' => 'controller',
            'fqn' => $route['controller']['fqn'],
            'lifecycle' => 'generated',
        ];
    }

    // The route registrations: one block per managed route, verbatim
    // from the joined authorities. No discovery, no glob, no magic.
    $routesText = php_routes_registrations_text($context, $mapped['routes']);
    $files[] = [
        'path' => $root . '/routes.php',
        'text' => $routesText,
        'digest' => 'sha256:' . hash('sha256', $routesText),
        'role' => 'routes-file',
        'lifecycle' => 'generated',
    ];

    // The OpenAPI projection: the staged evidence bytes, verbatim and
    // digest-bound — code and document are projections of one join.
    $openapiBytes = (string) $input['openapiBytes'];
    $files[] = [
        'path' => $root . '/openapi.json',
        'text' => $openapiBytes,
        'digest' => 'sha256:' . hash('sha256', $openapiBytes),
        'role' => 'openapi',
        'lifecycle' => 'generated',
    ];

    $classmapText = php_routes_classmap_text($files, $root);
    $files[] = [
        'path' => $root . '/classmap.php',
        'text' => $classmapText,
        'digest' => 'sha256:' . hash('sha256', $classmapText),
        'role' => 'classmap',
        'lifecycle' => 'generated',
    ];

    $sidecarText = php_routes_sidecar_text($input['projectId'], $mapped, $files, $context);
    $files[] = [
        'path' => $root . '/routes.map.json',
        'text' => $sidecarText,
        'digest' => 'sha256:' . hash('sha256', $sidecarText),
        'role' => 'map',
        'lifecycle' => 'generated',
    ];

    usort($files, static fn (array $left, array $right): int => strcmp((string) $left['path'], (string) $right['path']));
    return ['files' => $files];
}

/** The canonical envelope encoder text. */
function php_routes_http_envelope_text(array $context, string $namespace, string $operationsPrefix): string
{
    $actorFqn = '\\' . $operationsPrefix . '\\ActorContext';
    $lines = [
        php_routes_file_header($context, $namespace, 'php-routes/http-envelope'),
        '',
        '/**',
        ' * The canonical-v1 wire envelope of the route boundary (issue #60).',
        ' * The error shape is the declared identity quadruple with the public',
        ' * payload members only; the actor binding carries the declared scope',
        ' * dimensions of the authenticated principal.',
        ' */',
        'final class HttpEnvelope',
        '{',
        '    /**',
        '     * The request attribute the authentication middleware binds the',
        '     * ActorContext under. An auth-bound route without it is an',
        '     * infrastructure misconfiguration, never an anonymous fallback.',
        '     */',
        "    public const ACTOR_ATTRIBUTE = 'lekalo.actor';",
        '',
        '    /**',
        '     * One canonical error envelope: the declared identity members',
        '     * plus the public payload. An empty payload stays an empty JSON',
        '     * object, never an array.',
        '     *',
        '     * @param array<string, mixed> $payload',
        '     * @return array<string, mixed>',
        '     */',
        '    public static function error(string $id, string $code, string $category, array $payload): array',
        '    {',
        "        return ['ok' => false, 'error' => ['id' => \$id, 'code' => \$code, 'category' => \$category, 'payload' => \$payload === [] ? new \\stdClass() : \$payload]];",
        '    }',
        '',
        '    /**',
        '     * The actor binding of one request: the middleware-bound context',
        '     * on an auth-bound route, the declared anonymous context on a',
        '     * public one.',
        '     */',
        '    public static function actor(\\Illuminate\\Http\\Request $request, bool $authRequired): ' . $actorFqn,
        '    {',
        '        if (!$authRequired) {',
        '            return new ' . $actorFqn . "('anonymous');",
        '        }',
        '        $actor = $request->attributes->get(self::ACTOR_ATTRIBUTE);',
        '        if (!$actor instanceof ' . $actorFqn . ') {',
        "            throw new \\RuntimeException('the auth middleware never bound the actor context');",
        '        }',
        '        return $actor;',
        '    }',
        '}',
    ];
    return implode("\n", $lines) . "\n";
}

/** The typed validation-refusal text. */
function php_routes_validation_error_text(array $context, string $namespace): string
{
    $lines = [
        php_routes_file_header($context, $namespace, 'php-routes/request-validation-error'),
        '',
        '/**',
        ' * The typed refusal of one request binding: the decoded surface',
        ' * violates the declared decode plan. The boundary maps it to the',
        ' * declared validation error and status — never to a guessed id.',
        ' */',
        'final class RequestValidationError extends \\RuntimeException',
        '{',
        '    /**',
        '     * @param list<string> $fields the declared member names that',
        '     *     refused (the failing body members or required headers)',
        '     */',
        '    public function __construct(',
        '        public readonly array $fields,',
        '    ) {',
        "        parent::__construct('request validation: ' . implode(',', \$fields));",
        '    }',
        '',
        '    /** The first refused member: the declared `field` payload. */',
        '    public function field(): string',
        '    {',
        '        return $this->fields[0] ?? \'\';',
        '    }',
        '}',
    ];
    return implode("\n", $lines) . "\n";
}

/** The snake-const spelling of one semantic id for const-table names. */
function php_routes_const_of(string $semanticId): string
{
    return 'TABLE_' . strtoupper((string) preg_replace('/[^A-Za-z0-9]/', '_', $semanticId));
}

/**
 * The explicit error-to-HTTP map text: one const table per governed
 * route with the declared status, category, and code per error id,
 * plus the declared category defaults and the validation error id.
 */
function php_routes_error_http_map_text(array $context, string $namespace, array $routes): string
{
    $lines = [
        php_routes_file_header($context, $namespace, 'php-routes/error-http-map'),
        '',
        '/**',
        ' * The explicit error-to-HTTP projection of the governed routes',
        ' * (issue #60): the declared per-error table and the category',
        ' * defaults, exactly as the transport attachment and the OpenAPI',
        ' * projection declare them. An undeclared error id is never mapped:',
        ' * the boundary throws, and the application exception handling owns',
        ' * the failure.',
        ' */',
        'final class ErrorHttpMap',
        '{',
    ];
    foreach ($routes as $route) {
        $const = php_routes_const_of((string) $route['id']);
        $lines[] = '    private const ' . $const . ' = [';
        foreach ($route['errors'] as $error) {
            $lines[] = '        ' . php_types_string_literal((string) $error['error']) . ' => ['
                . "'status' => " . (int) $error['status'] . ', '
                . "'category' => " . php_types_string_literal((string) $error['category']) . ', '
                . "'code' => " . php_types_string_literal((string) $error['code']) . '],';
        }
        $lines[] = '    ];';
    }
    $lines[] = '';
    $lines[] = '    /** @var array<string, array<string, int>> */';
    $lines[] = '    private const ROUTE_DEFAULTS = [';
    foreach ($routes as $route) {
        $lines[] = '        ' . php_types_string_literal((string) $route['id']) . ' => [';
        foreach ($route['errorDefaults'] as $category => $status) {
            $lines[] = '            ' . php_types_string_literal((string) $category) . ' => ' . (int) $status . ',';
        }
        $lines[] = '        ],';
    }
    $lines[] = '    ];';
    $lines[] = '';
    $lines[] = '    /** @var array<string, string> the validation-category error of every body-carrying route. */';
    $lines[] = '    private const VALIDATION_ERRORS = [';
    foreach ($routes as $route) {
        if (isset($route['validationError'])) {
            $lines[] = '        ' . php_types_string_literal((string) $route['id']) . ' => '
                . php_types_string_literal((string) $route['validationError']) . ',';
        }
    }
    $lines[] = '    ];';
    $lines[] = '';
    $lines[] = '    /** @var array<string, array<string, array{status: int, category: string, code: string}>> */';
    $lines[] = '    private const ROUTE_ERRORS = [';
    foreach ($routes as $route) {
        $lines[] = '        ' . php_types_string_literal((string) $route['id']) . ' => self::' . php_routes_const_of((string) $route['id']) . ',';
    }
    $lines[] = '    ];';
    $lines[] = '';
    $lines[] = '    /**';
    $lines[] = '     * One mapped domain failure: the declared envelope of one declared';
    $lines[] = '     * error id, with the wire-encoded public payload members.';
    $lines[] = '     *';
    $lines[] = '     * @param array<string, mixed> $payload';
    $lines[] = '     * @return array{ok: bool, error: array<string, mixed>}|null';
    $lines[] = '     */';
    $lines[] = '    public static function domain(string $endpoint, string $errorId, array $payload): ?array';
    $lines[] = '    {';
    $lines[] = '        $declared = self::ROUTE_ERRORS[$endpoint][$errorId] ?? null;';
    $lines[] = '        if ($declared === null) {';
    $lines[] = '            return null;';
    $lines[] = '        }';
    $lines[] = '        return HttpEnvelope::error($errorId, $declared[\'code\'], $declared[\'category\'], $payload);';
    $lines[] = '    }';
    $lines[] = '';
    $lines[] = '    /** The declared HTTP status of one declared error id. */';
    $lines[] = '    public static function status(string $endpoint, string $errorId): int';
    $lines[] = '    {';
    $lines[] = '        $declared = self::ROUTE_ERRORS[$endpoint][$errorId] ?? null;';
    $lines[] = '        if ($declared === null) {';
    $lines[] = '            throw new LogicException(\'undeclared error id: \' . $errorId);';
    $lines[] = '        }';
    $lines[] = '        return $declared[\'status\'];';
    $lines[] = '    }';
    $lines[] = '';
    $lines[] = '    /**';
    $lines[] = '     * One mapped validation refusal: the declared validation error of';
    $lines[] = '     * the route and the declared validation-category status.';
    $lines[] = '     *';
    $lines[] = '     * @param list<string> $fields';
    $lines[] = '     * @return array{ok: bool, error: array<string, mixed>}|null';
    $lines[] = '     */';
    $lines[] = '    public static function validation(string $endpoint, array $fields): ?array';
    $lines[] = '    {';
    $lines[] = '        $errorId = self::VALIDATION_ERRORS[$endpoint] ?? null;';
    $lines[] = '        if ($errorId === null) {';
    $lines[] = '            return null;';
    $lines[] = '        }';
    $lines[] = '        $mapped = self::domain($endpoint, $errorId, [\'field\' => $fields === [] ? \'\' : (string) $fields[0]]);';
    $lines[] = '        return $mapped;';
    $lines[] = '    }';
    $lines[] = '';
    $lines[] = '    /** The declared status of one mapped validation refusal. */';
    $lines[] = '    public static function validationStatus(string $endpoint): int';
    $lines[] = '    {';
    $lines[] = '        $defaults = self::ROUTE_DEFAULTS[$endpoint] ?? [];';
    $lines[] = '        return (int) ($defaults[\'validation\'] ?? 500);';
    $lines[] = '    }';
    $lines[] = '}';
    return implode("\n", $lines) . "\n";
}

/**
 * The wire-encoding expression of one typed value: string-backed enums
 * spell their declared case, string-backed scalars spell their exact
 * string, everything else spells its primitive value.
 *
 * @param array{ref: string, fqn: string, kind: string, base: string} $type
 */
function php_routes_wire_expr(array $type, string $expr): string
{
    if ($type['kind'] === 'enum') {
        return $expr . '->toWire()';
    }
    if ($type['kind'] === 'scalar' && !in_array($type['base'], ['number', 'boolean'], true)) {
        return $expr . '->toString()';
    }
    return $expr . '->value()';
}

/** The typed request-binding text of one managed body-carrying route. */
function php_routes_request_text(array $context, string $namespace, array $route): string
{
    $requestFqn = (string) $route['request']['fqn'];
    $requestNamespace = substr($requestFqn, 0, (int) strrpos($requestFqn, '\\'));
    $requestClass = substr($requestFqn, (int) strlen($requestNamespace) + 1);
    $inputFqn = (string) $route['entry']['inputFqn'];
    $decode = $route['decode'];
    $lines = [
        php_routes_file_header($context, $requestNamespace, (string) $route['id']),
        '',
        '/**',
        ' * The typed request binding of ' . $route['id'] . ': the declared',
        ' * decode plan (path parameters, body projection) becomes the #58',
        ' * typed input. Any refusal is the typed validation error the',
        ' * controller maps through the declared table.',
        ' */',
        'final class ' . $requestClass,
        '{',
        '    /**',
        '     * Decode one HTTP request into the typed operation input.',
        '     */',
        '    public static function fromWire(\\Illuminate\\Http\\Request $request): \\' . $inputFqn,
        '    {',
    ];
    $hasParams = $decode['params'] !== [];
    $hasExplicitBody = $decode['body'] !== null && $decode['body']['mode'] === 'explicit';
    $isWholeBody = $decode['body'] !== null && $decode['body']['mode'] === 'whole-input';
    // The declared required headers are part of the decode plan: the
    // projection documents them, so the binding enforces them.
    $requiredHeaders = [];
    if (($route['idempotency']['required'] ?? false) === true) {
        $requiredHeaders[] = (string) $route['idempotency']['header'];
    }
    foreach ($requiredHeaders as $header) {
        $lines[] = '        if ($request->header(' . php_types_string_literal($header) . ') === null) {';
        $lines[] = '            throw new \\Lekalo\\Generated\\Routes\\RequestValidationError([' . php_types_string_literal($header) . ']);';
        $lines[] = '        }';
    }
    if ($isWholeBody) {
        $lines[] = '        $wire = $request->json()->all();';
        $lines[] = '        if (!is_array($wire)) {';
        $lines[] = "            throw new \\Lekalo\\Generated\\Routes\\RequestValidationError(['body']);";
        $lines[] = '        }';
    } else {
        $lines[] = '        $wire = [];';
        if ($hasParams) {
            $lines[] = '        $route = $request->route();';
        }
        foreach ($decode['params'] as $param) {
            $member = php_routes_input_member_of((string) $param['field']);
            $lines[] = '        $wire[' . php_types_string_literal($member) . '] = $route->parameter(' . php_types_string_literal((string) $param['name']) . ');';
        }
        if ($hasExplicitBody) {
            $lines[] = '        $body = $request->json()->all();';
            $lines[] = '        if (!is_array($body)) {';
            $lines[] = "            throw new \\Lekalo\\Generated\\Routes\\RequestValidationError(['body']);";
            $lines[] = '        }';
            foreach ($decode['body']['fields'] as $field) {
                $member = php_routes_input_member_of((string) $field['field']);
                if ((bool) $field['required']) {
                    $lines[] = '        if (!array_key_exists(' . php_types_string_literal((string) $field['name']) . ', $body)) {';
                    $lines[] = '            throw new \\Lekalo\\Generated\\Routes\\RequestValidationError([' . php_types_string_literal((string) $field['name']) . ']);';
                    $lines[] = '        }';
                    $lines[] = '        $wire[' . php_types_string_literal($member) . '] = $body[' . php_types_string_literal((string) $field['name']) . '];';
                } else {
                    $lines[] = '        if (array_key_exists(' . php_types_string_literal((string) $field['name']) . ', $body)) {';
                    $lines[] = '            $wire[' . php_types_string_literal($member) . '] = $body[' . php_types_string_literal((string) $field['name']) . '];';
                    $lines[] = '        }';
                }
            }
        }
    }
    $lines[] = '        try {';
    $lines[] = '            return \\' . $inputFqn . 'Codec::decode($wire);';
    $lines[] = '        } catch (\\InvalidArgumentException $failure) {';
    $lines[] = '            throw new \\Lekalo\\Generated\\Routes\\RequestValidationError([], $failure);';
    $lines[] = '        }';
    $lines[] = '    }';
    $lines[] = '}';
    return implode("\n", $lines) . "\n";
}

/** The typed input member of one declared field reference. */
function php_routes_input_member_of(string $field): string
{
    return str_starts_with($field, 'input.') ? substr($field, 6) : $field;
}

/** The thin controller text of one managed route. */
function php_routes_controller_text(array $context, string $namespace, array $route): string
{
    $controllerFqn = (string) $route['controller']['fqn'];
    $controllerNamespace = substr($controllerFqn, 0, (int) strrpos($controllerFqn, '\\'));
    $controllerClass = substr($controllerFqn, (int) strlen($controllerNamespace) + 1);
    $action = (string) $route['controller']['action'];
    $entryFqn = (string) $route['entry']['fqn'];
    $inputFqn = (string) $route['entry']['inputFqn'];
    $routeId = (string) $route['id'];
    $authRequired = $route['auth'] !== null;
    $errorBase = (string) $context['operationsNamespacePrefix'];
    $isCommand = $route['operationKind'] === 'command';

    $lines = [
        php_routes_file_header($context, $controllerNamespace, $routeId),
        '',
        'use Symfony\\Component\\HttpFoundation\\Response;',
        'use Illuminate\\Http\\Request;',
        '',
        '/**',
        ' * The thin HTTP wrapper of ' . $routeId . ' (issue #60): decode the',
        ' * declared transport surface, bind the actor, invoke the one',
        ' * operation entrypoint, and encode the declared projections. There',
        ' * is no business logic and no catch-all: only the declared typed',
        ' * errors map; everything else propagates unmodified.',
        ' */',
        'final readonly class ' . $controllerClass,
        '{',
        '    public function __construct(',
        '        private \\' . $entryFqn . ' $handler,',
        '    ) {',
        '    }',
        '',
        '    public function ' . $action . '(Request $request): Response',
        '    {',
    ];
    // The decode: the typed request binding, or the explicit query
    // input constructed directly.
    if ($route['request'] !== null) {
        $lines[] = '        try {';
        $lines[] = '            $input = \\' . (string) $route['request']['fqn'] . '::fromWire($request);';
        $lines[] = '        } catch (\\Lekalo\\Generated\\Routes\\RequestValidationError $failure) {';
        $lines[] = '            return response()->json(';
        $lines[] = '                \\Lekalo\\Generated\\Routes\\ErrorHttpMap::validation(' . php_types_string_literal($routeId) . ', $failure->fields),';
        $lines[] = '                \\Lekalo\\Generated\\Routes\\ErrorHttpMap::validationStatus(' . php_types_string_literal($routeId) . '),';
        $lines[] = '            );';
        $lines[] = '        }';
    } else {
        $lines[] = '        $input = new \\' . $inputFqn . '();';
    }
    $lines[] = '        $actor = \\Lekalo\\Generated\\Routes\\HttpEnvelope::actor($request, ' . ($authRequired ? 'true' : 'false') . ');';
    $lines[] = '        try {';
    $lines[] = $isCommand
        ? '            $this->handler->handle($input, $actor);'
        : '            $result = $this->handler->handle($input, $actor);';
    foreach ($route['errors'] as $error) {
        if (($error['refusal'] ?? false) === true) {
            // The validation-category error maps through the request
            // binding refusal, not a handler catch.
            continue;
        }
        $errorClass = php_routes_error_class_of((string) $error['error'], $errorBase);
        $payloadArgs = [];
        foreach ($error['payload'] as $member) {
            $type = php_routes_field_type($member, $context['definitions'][$route['operation']], $context['typesIndex'], $context['definitions']);
            $property = php_types_property_of((string) $member);
            $payloadArgs[] = php_types_string_literal((string) $member) . ' => ' . php_routes_wire_expr($type, '$input->' . $property);
        }
        $lines[] = '        } catch (' . $errorClass . ' $failure) {';
        $lines[] = '            return response()->json(';
        $lines[] = '                \\Lekalo\\Generated\\Routes\\ErrorHttpMap::domain(' . php_types_string_literal($routeId) . ', ' . php_types_string_literal((string) $error['error']) . ', [' . implode(', ', $payloadArgs) . ']),';
        $lines[] = '                \\Lekalo\\Generated\\Routes\\ErrorHttpMap::status(' . php_types_string_literal($routeId) . ', ' . php_types_string_literal((string) $error['error']) . '),';
        $lines[] = '            );';
    }
    $lines[] = '        }';
    if ($isCommand) {
        $lines[] = '';
        $lines[] = '        return new \\Illuminate\\Http\\Response(\'\', ' . (int) $route['success']['status'] . ');';
    } else {
        // A list-return query encodes through its declared #58 result
        // codec (issue #50): the collection class carries no wire
        // spelling of its own, the codec is the projection.
        $resultCodecFqn = php_routes_result_codec_fqn($route, $context);
        if ($resultCodecFqn !== null) {
            $wire = '\\' . $resultCodecFqn . '::encode($result)';
        } else {
            $resultType = php_routes_result_type($route, $context);
            $wire = $resultType === null ? 'null' : php_routes_wire_expr($resultType, '$result');
        }
        $lines[] = '';
        $lines[] = '        return response()->json(' . $wire . ', ' . (int) $route['success']['status'] . ');';
    }
    $lines[] = '    }';
    $lines[] = '}';
    return implode("\n", $lines) . "\n";
}

/**
 * The typed error class FQN of one declared error id, spelled exactly
 * as the operations family names its typed error classes.
 */
function php_routes_error_class_of(string $errorId, string $operationsPrefix): string
{
    $module = php_types_module_of($errorId);
    $leaf = php_types_leaf_name_of($errorId);
    $parts = explode('_', $leaf);
    $class = implode('', array_map('ucfirst', array_filter($parts, static fn (string $part): bool => $part !== ''))) . 'Error';
    return '\\' . $operationsPrefix . '\\' . ucfirst($module) . '\\Errors\\' . $class;
}

/** The mapped result type of one query route, when it projects a body. */
function php_routes_result_type(array $route, array $context): ?array
{
    $definition = is_array($context['definitions'][$route['operation']] ?? null) ? $context['definitions'][$route['operation']] : null;
    $ref = $definition === null ? null : ($definition['returns']['ref'] ?? null);
    if (!is_string($ref)) {
        return null;
    }
    $entry = is_array($context['typesIndex'][$ref] ?? null) ? $context['typesIndex'][$ref] : null;
    $type = is_array($context['definitions'][$ref] ?? null) ? $context['definitions'][$ref] : null;
    if ($entry === null || $type === null) {
        return null;
    }
    return ['ref' => $ref, 'fqn' => (string) $entry['fqn'], 'kind' => (string) ($type['kind'] ?? ''), 'base' => (string) ($type['base'] ?? '')];
}

/**
 * The #58 result codec of one list-return query route (issue #50): the
 * mapped query entry is the codec; a scalar-ref query or a command
 * carries none.
 */
function php_routes_result_codec_fqn(array $route, array $context): ?string
{
    $definition = is_array($context['definitions'][$route['operation']] ?? null) ? $context['definitions'][$route['operation']] : null;
    if ($definition === null || !isset($definition['returns']['list']['ref'])) {
        return null;
    }
    $entry = is_array($context['typesIndex'][$route['operation']] ?? null) ? $context['typesIndex'][$route['operation']] : null;
    if ($entry === null || !is_string($entry['fqn'] ?? null)) {
        return null;
    }
    return (string) $entry['fqn'];
}

/** The route registrations text: one block per managed route, id-sorted. */
function php_routes_registrations_text(array $context, array $routes): string
{
    $managed = array_values(array_filter($routes, static fn (array $route): bool => $route['mode'] === 'managed'));
    usort($managed, static fn (array $left, array $right): int => strcmp((string) $left['id'], (string) $right['id']));
    $lines = [
        '<?php',
        '',
        'declare(strict_types=1);',
        '',
        '// Generated by ' . ADAPTER_ID . '@' . ADAPTER_VERSION . ' (routes generator, issue #60).',
        '// From dev.lekalo.ir@0.2.16 input ' . $context['irDigest'] . '.',
        '// Do not edit: regenerate with `lekalo generate`.',
        '//',
        '// The managed route registrations of one routes input. This file is',
        '// the whole registration surface of the routes family: manual routes',
        '// outside it are never touched, and the application merges by',
        '// requiring this file from its own route bootstrap.',
        '',
        'use Illuminate\\Support\\Facades\\Route;',
    ];
    $uses = [];
    foreach ($managed as $route) {
        $uses[] = (string) $route['controller']['fqn'];
    }
    sort($uses, SORT_STRING);
    foreach ($uses as $use) {
        $lines[] = 'use ' . $use . ';';
    }
    $lines[] = '';
    foreach ($managed as $route) {
        $method = strtolower((string) $route['method']);
        $chain = [
            'Route::' . $method . '(' . php_types_string_literal((string) $route['pathTemplate']) . ', ['
                . (string) $route['controller']['fqn'] . '::class, ' . php_types_string_literal((string) $route['controller']['action']) . '])',
            '    ->name(' . php_types_string_literal((string) $route['name']) . ')',
        ];
        if (($route['middleware'] ?? []) !== []) {
            $spellings = implode(', ', array_map(
                static fn (string $spelling): string => php_types_string_literal($spelling),
                $route['middleware'],
            ));
            $chain[] = '    ->middleware([' . $spellings . '])';
        }
        $lines[] = implode("\n", $chain) . ';';
    }
    return implode("\n", $lines) . "\n";
}

/** The deterministic classmap text: FQN => root-relative path. */
function php_routes_classmap_text(array $files, string $root): string
{
    $entries = [];
    foreach ($files as $file) {
        if (!isset($file['fqn'])) {
            continue;
        }
        $relative = substr((string) $file['path'], strlen($root) + 1);
        $entries[(string) $file['fqn']] = $relative;
    }
    ksort($entries);
    $lines = [
        '<?php',
        '',
        'declare(strict_types=1);',
        '',
        '// Generated by ' . ADAPTER_ID . '@' . ADAPTER_VERSION . ' (routes generator, issue #60).',
        '// The deterministic class map: fully-qualified name => root-relative path.',
        '// The loading authority of the generated routes tree - no runtime',
        '// registration magic, no Composer scan.',
        '',
        'return [',
    ];
    foreach ($entries as $fqn => $relative) {
        $lines[] = '    ' . php_types_string_literal($fqn) . ' => ' . php_types_string_literal($relative) . ',';
    }
    $lines[] = '];';
    return implode("\n", $lines) . "\n";
}

/** The canonical custody sidecar over the complete routes inventory. */
function php_routes_sidecar_text(string $projectId, array $mapped, array $files, array $context): string
{
    $routes = [];
    foreach ($mapped['routes'] as $route) {
        $entry = [
            'id' => $route['id'],
            'operation' => $route['operation'],
            'operationId' => $route['operationId'],
            'mode' => $route['mode'],
            'method' => $route['method'],
            'pathTemplate' => $route['pathTemplate'],
            'name' => $route['name'],
        ];
        if ($route['mode'] === 'managed') {
            $entry['controller'] = [
                'fqn' => $route['controller']['fqn'],
                'path' => $route['controller']['path'],
                'action' => $route['controller']['action'],
            ];
            if ($route['request'] !== null) {
                $entry['request'] = ['fqn' => $route['request']['fqn'], 'path' => $route['request']['path']];
            }
        }
        $entry['entry'] = ['fqn' => $route['entry']['fqn'], 'method' => $route['entry']['method']];
        $entry['middleware'] = $route['middleware'];
        $success = ['status' => $route['success']['status']];
        if ($route['success']['bodyMode'] !== null) {
            $success['bodyMode'] = $route['success']['bodyMode'];
        }
        $entry['success'] = $success;
        $entry['errors'] = array_map(
            static fn (array $error): array => ['error' => $error['error'], 'status' => $error['status']],
            $route['errors'],
        );
        $entry['errorDefaults'] = $route['errorDefaults'];
        if ($route['auth'] !== null) {
            $entry['auth'] = array_filter([
                'actor' => $route['auth']['actor'],
                'schemes' => $route['auth']['schemes'],
                'policyRef' => $route['auth']['policyRef'],
            ], static fn (mixed $value): bool => $value !== null);
        }
        $entry['links'] = $route['links'];
        $routes[] = $entry;
    }
    $artifacts = [];
    foreach ($files as $file) {
        $row = [
            'path' => substr((string) $file['path'], strlen(PHP_ROUTES_GENERATED_ROOT) + 1),
            'role' => $file['role'],
            'lifecycle' => $file['lifecycle'],
        ];
        if (isset($file['fqn'])) {
            $row['fqn'] = $file['fqn'];
        }
        $row['digest'] = $file['digest'];
        $artifacts[] = $row;
    }
    usort($artifacts, static fn (array $left, array $right): int => strcmp((string) $left['path'], (string) $right['path']));
    $document = [
        'schemaVersion' => PHP_ROUTES_MAP_SCHEMA_VERSION,
        'identity' => PHP_ROUTES_MAP_IDENTITY,
        'projectId' => $projectId,
        'adapter' => [
            'id' => ADAPTER_ID,
            'version' => ADAPTER_VERSION,
            'digest' => sha256_digest(ADAPTER_ID . '@' . ADAPTER_VERSION),
        ],
        'digests' => [
            'ir' => $context['irDigest'],
            'transport' => $context['transportDigest'],
            'input' => $context['inputDigest'],
            'typesInput' => $context['typesInputDigest'],
            'operationsInput' => $context['operationsInputDigest'],
            'openapi' => $context['openapiDigest'],
        ],
        'routes' => $routes,
        'artifacts' => $artifacts,
    ];
    return php_types_canonical_json($document) . "\n";
}

