<?php
/**
 * The emitter of the PHP type generator (issue #58, step 2): the mapped
 * inventory becomes deterministic PHP 8.3 files — final readonly
 * classes, native string-backed enums, typed immutable collections,
 * concrete presence wrappers, and one codec per type — plus the
 * deterministic class map and the authoritative mapping sidecar.
 *
 * Every file declares `strict_types=1`, carries its semantic id, and
 * escapes free wire text through a comment-safe projection. There are
 * no timestamps, absolute paths, environment lookups, or dynamic
 * members anywhere in the output: repeated generations over the same
 * inputs are byte-identical.
 */

if (!function_exists('php_types_leaf_fqn')) {
    require_once __DIR__ . '/type-codec.php';
}

/**
 * One comment-safe single-line projection of free wire text: every
 * line terminator and control character collapses, so a core-valid
 * description can never close a generated comment and inject live code
 * into the emitted class.
 */
function php_types_comment_safe(mixed $text): string
{
    $value = (string) ($text ?? '');
    $value = preg_replace('/\r\n|[\r\n\x{0085}\x{2028}\x{2029}]|\p{Cc}/u', ' ', $value) ?? '';
    $value = preg_replace('/\s+/', ' ', $value) ?? '';
    $value = trim($value);
    // Byte-exact truncation keeps the emitted bytes a pure function of
    // the input bytes (and keeps php -n runtimes safe).
    $value = substr($value, 0, 200);
    // A one-line comment also ends at the mid-line close-tag pair: break
    // it so no projection can re-open PHP mode.
    return str_replace('?>', '? >', $value);
}

/**
 * The canonical JSON spelling of the sidecar documents: sorted object
 * keys, compact separators.
 */
function php_types_canonical_json(mixed $value): string
{
    if (is_array($value)) {
        if ($value !== [] && array_is_list($value)) {
            return '[' . implode(',', array_map(
                static fn ($item): string => php_types_canonical_json($item),
                $value,
            )) . ']';
        }
        $keys = array_keys($value);
        sort($keys, SORT_STRING);
        $members = [];
        foreach ($keys as $key) {
            $members[] = json_encode((string) $key, JSON_UNESCAPED_SLASHES)
                . ':' . php_types_canonical_json($value[$key]);
        }
        return '{' . implode(',', $members) . '}';
    }
    if (is_bool($value)) {
        return $value ? 'true' : 'false';
    }
    if ($value === null) {
        return 'null';
    }
    if (is_int($value) || is_float($value)) {
        return json_encode($value);
    }
    return json_encode((string) $value, JSON_UNESCAPED_SLASHES);
}

/**
 * The provenance header of every emitted file: no timestamp, no
 * absolute path — digests only, so the bytes stay a pure function of
 * the inputs.
 */
function php_types_file_header(array $context, string $namespace, string $semanticId, ?string $description): string
{
    $lines = [
        '<?php',
        '',
        'declare(strict_types=1);',
        '',
        '// Generated by lekalo-target-php-laravel@' . $context['adapterVersion']
            . ' (type generator, issue #58).',
        '// From ' . PHP_TYPES_IR_IDENTITY . ' input ' . $context['irDigest']
            . '. Do not edit: regenerate with `lekalo generate`.',
        '// Semantic id: ' . $semanticId . '.',
    ];
    if ($description !== null && $description !== '') {
        $lines[] = '// Description: ' . php_types_comment_safe($description);
    }
    if ($namespace !== '') {
        $lines[] = '';
        $lines[] = 'namespace ' . $namespace . ';';
    }
    return implode("\n", $lines);
}

/** The bare class name of one mapped entry (the final FQN segment). */
function php_types_entry_class(array $entry): string
{
    $cut = strrpos($entry['fqn'], '\\');
    return $cut === false ? $entry['fqn'] : substr($entry['fqn'], $cut + 1);
}

/**
 * Emit every generated file of one mapped type inventory. `input` is
 * `{projectId, mapped, adapterVersion, root}`; returns path-sorted
 * `{path, text}` records with paths under the declared custody root,
 * plus the sidecar document as `map`.
 */
function php_emit_types(array $input): array
{
    $mapped = $input['mapped'];
    $policy = $mapped['policy'];
    $prefix = $policy['namespacePrefix'];
    $definitions = [];
    foreach ($mapped['types'] as $entry) {
        $definitions[$entry['semanticId']] = $entry;
    }
    $context = [
        'adapterVersion' => $input['adapterVersion'],
        'irDigest' => $mapped['digests']['ir'],
        'projectId' => $input['projectId'],
        'custody' => $policy['custody'],
    ];
    $root = $input['root'];

    $files = [];
    $addFile = static function (string $relative, string $text) use (&$files, $root): void {
        $files[] = ['path' => $root . '/' . $relative, 'text' => $text];
    };

    foreach ($mapped['types'] as $entry) {
        $module = php_types_module_of($entry['semanticId']);
        $namespace = $prefix . '\\' . ucfirst($module);
        $description = php_types_entry_description($definitions, $entry['semanticId']);
        switch ($entry['kind']) {
            case 'scalar':
                $addFile($entry['path'], php_types_scalar_text($entry, $context, $namespace, $description));
                break;
            case 'enum':
                $addFile($entry['path'], php_types_enum_text($entry, $context, $namespace, $description));
                break;
            case 'query':
                $addFile($entry['codecPath'], php_types_query_codec_text(
                    $entry,
                    $definitions,
                    $prefix,
                    $context,
                    $namespace,
                    $description,
                ));
                break;
            default:
                $addFile($entry['path'], php_types_structured_text(
                    $entry,
                    $definitions,
                    $prefix,
                    $context,
                    $namespace,
                    $description,
                ));
                $addFile($entry['codecPath'], php_types_codec_text(
                    $entry,
                    $definitions,
                    $prefix,
                    $context,
                    $namespace,
                    $description,
                ));
                break;
        }
    }
    foreach ($mapped['collections'] as $collection) {
        $module = php_types_module_of($collection['element']);
        $namespace = $prefix . '\\' . ucfirst($module);
        $description = php_types_entry_description($definitions, $collection['element']);
        $addFile($collection['path'], php_types_collection_text(
            $collection,
            $definitions,
            $prefix,
            $context,
            $namespace,
            $description,
        ));
    }
    foreach ($mapped['wrappers'] as $wrapper) {
        $module = php_types_module_of($wrapper['element']);
        $namespace = $prefix . '\\' . ucfirst($module) . '\\Optional';
        $description = php_types_entry_description($definitions, $wrapper['element']);
        $addFile($wrapper['path'], php_types_wrapper_text(
            $wrapper,
            $definitions,
            $prefix,
            $context,
            $namespace,
            $description,
        ));
    }
    if ($policy['classMap']) {
        $addFile('classmap.php', php_types_classmap_text($mapped['artifacts'], $context, $prefix));
    }

    $sidecar = php_types_sidecar_document($input['projectId'], $mapped, $context, $root);
    $addFile('types.map.json', php_types_canonical_json($sidecar) . "\n");

    usort($files, static fn (array $left, array $right): int => strcmp($left['path'], $right['path']));
    return ['files' => $files, 'map' => $sidecar];
}

/** The mapped description of one definition, without internal keys. */
function php_types_entry_description(array $definitions, string $semanticId): ?string
{
    $description = $definitions[$semanticId]['description'] ?? null;
    return is_string($description) && $description !== '' ? $description : null;
}

// ---------------------------------------------------------------------------
// Scalar nominal wrappers.
// ---------------------------------------------------------------------------

/**
 * The validation body of one scalar base: a closed, extension-free
 * check that refuses rather than coerces.
 */
function php_types_scalar_validation(string $base): string
{
    switch ($base) {
        case 'string':
            return "        return is_string(\$raw) && \$raw !== '';";
        case 'boolean':
            return '        return is_bool($raw);';
        case 'number':
            return implode("\n", [
                '        if (is_int($raw)) {',
                '            return true;',
                '        }',
                '        // A JSON integer beyond exact float precision arrives as an',
                '        // integral float: refused, never silently rounded.',
                '        return is_float($raw) && is_finite($raw)',
                '            && !($raw === floor($raw) && abs($raw) >= 9007199254740992);',
            ]);
        case 'uuid':
            return implode("\n", [
                "        return is_string(\$raw)",
                "            && preg_match('/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\$/', \$raw) === 1;",
            ]);
        case 'date':
            return implode("\n", [
                "        if (!is_string(\$raw) || preg_match('/^\\\\d{4}-\\\\d{2}-\\\\d{2}\$/', \$raw) !== 1) {",
                '            return false;',
                '        }',
                '        return checkdate((int) substr($raw, 5, 2), (int) substr($raw, 8, 2), (int) substr($raw, 0, 4));',
            ]);
        case 'datetime':
            return implode("\n", [
                '        if (!is_string($raw)',
                "            || preg_match('/^\\\\d{4}-\\\\d{2}-\\\\d{2}T\\\\d{2}:\\\\d{2}:\\\\d{2}(?:\\\\.\\\\d+)?(?:Z|[+-]\\\\d{2}:\\\\d{2})\$/', \$raw) !== 1) {",
                '            return false;',
                '        }',
                '        return checkdate((int) substr($raw, 5, 2), (int) substr($raw, 8, 2), (int) substr($raw, 0, 4));',
            ]);
        case 'uri':
            return implode("\n", [
                "        return is_string(\$raw) && \$raw !== ''",
                "            && preg_match('/^[A-Za-z][A-Za-z0-9+.\\\\-]*:\\\\S*\$/', \$raw) === 1;",
            ]);
        default:
            // The closed base vocabulary is validated upstream; an
            // unknown base here is a kernel bug, not an emission case.
            throw new LogicException('unknown scalar base: ' . $base);
    }
}

/** The emitted text of one nominal scalar wrapper. */
function php_types_scalar_text(array $entry, array $context, string $namespace, ?string $description): string
{
    $base = $entry['base'];
    $class = php_types_entry_class($entry);
    $stringBacked = !in_array($base, ['number', 'boolean'], true);
    $propertyType = $stringBacked ? 'string' : ($base === 'number' ? 'int|float' : 'bool');
    $fromParameter = $stringBacked ? 'string $value' : ($base === 'number' ? 'int|float $value' : 'bool $value');
    $owner = php_types_string_literal($entry['semanticId']);
    $accessor = $stringBacked
        ? implode("\n", [
            '',
            '    /** The exact declared spelling, never a reformatting. */',
            '    public function toString(): string',
            '    {',
            '        return $this->value;',
            '    }',
        ])
        : implode("\n", [
            '',
            '    /** The exact finite value: no numeric-string coercion exists. */',
            '    public function value(): ' . $propertyType,
            '    {',
            '        return $this->value;',
            '    }',
        ]);
    $lines = [
        php_types_file_header($context, $namespace, $entry['semanticId'], $description),
        '',
        'final readonly class ' . $class,
        '{',
        '    private function __construct(',
        '        public readonly ' . $propertyType . ' $value,',
        '    ) {',
        '    }',
        '',
        '    /**',
        '     * Decode one wire value: the declared spelling is validated,',
        '     * never coerced.',
        '     */',
        '    public static function fromWire(mixed $raw): self',
        '    {',
        '        if (!self::isValid($raw)) {',
        '            throw new \\InvalidArgumentException(' . $owner . ' . \': invalid ' . $base . ' wire value\');',
        '        }',
        '        /** @var ' . $propertyType . ' $raw */',
        '        return new self($raw);',
        '    }',
        '',
        '    /** Construct from an already-typed value with the same validation. */',
        '    public static function from(' . $fromParameter . '): self',
        '    {',
        '        if (!self::isValid($value)) {',
        '            throw new \\InvalidArgumentException(' . $owner . ' . \': invalid ' . $base . ' value\');',
        '        }',
        '        return new self($value);',
        '    }',
        '',
        '    private static function isValid(mixed $raw): bool',
        '    {',
        php_types_scalar_validation($base),
        '    }',
        $accessor,
        '',
        '    public function equals(self $other): bool',
        '    {',
        '        return $this->value === $other->value;',
        '    }',
        '}',
    ];
    return implode("\n", $lines) . "\n";
}

// ---------------------------------------------------------------------------
// String-backed enums.
// ---------------------------------------------------------------------------

/** The emitted text of one string-backed enum in declared order. */
function php_types_enum_text(array $entry, array $context, string $namespace, ?string $description): string
{
    $class = php_types_entry_class($entry);
    $owner = php_types_string_literal($entry['semanticId']);
    $lines = [
        php_types_file_header($context, $namespace, $entry['semanticId'], $description),
        '',
        'enum ' . $class . ': string',
        '{',
    ];
    foreach ($entry['values'] as $value) {
        $lines[] = '    case ' . $value['case'] . ' = ' . php_types_string_literal($value['value']) . ';';
    }
    $lines[] = '';
    $lines[] = '    /**';
    $lines[] = '     * Decode one wire value: the declared members are the closed';
    $lines[] = '     * vocabulary; anything else refuses.';
    $lines[] = '     */';
    $lines[] = '    public static function fromWire(mixed $raw): self';
    $lines[] = '    {';
    $lines[] = '        $case = is_string($raw) ? self::tryFrom($raw) : null;';
    $lines[] = '        if ($case === null) {';
    $lines[] = '            throw new \\InvalidArgumentException(' . $owner . ' . \': unknown enum wire value\');';
    $lines[] = '        }';
    $lines[] = '        return $case;';
    $lines[] = '    }';
    $lines[] = '';
    $lines[] = '    /** The exact declared wire value. */';
    $lines[] = '    public function toWire(): string';
    $lines[] = '    {';
    $lines[] = '        return $this->value;';
    $lines[] = '    }';
    $lines[] = '}';
    return implode("\n", $lines) . "\n";
}

// ---------------------------------------------------------------------------
// Immutable collections.
// ---------------------------------------------------------------------------

/** The emitted text of one typed immutable collection class. */
function php_types_collection_text(
    array $collection,
    array $definitions,
    string $prefix,
    array $context,
    string $namespace,
    ?string $description,
): string {
    $elementFqn = '\\' . php_types_leaf_fqn($definitions, $prefix, $collection['element']);
    $nullableElements = $collection['nullableElements'];
    $docType = $nullableElements ? 'list<null|' . $elementFqn . '>' : 'list<' . $elementFqn . '>';
    $elementCheck = $nullableElements
        ? 'if ($item !== null && !$item instanceof ' . $elementFqn . ') {'
        : 'if (!$item instanceof ' . $elementFqn . ') {';
    $elementEquals = $nullableElements
        ? '            if (($item === null) !== ($other->items[$index] === null)'
        . "\n"
        . '                || ($item !== null && !$item->equals($other->items[$index]))) {'
        : '            if (!$item->equals($other->items[$index])) {';
    $owner = php_types_string_literal($collection['element']);
    $lines = [
        php_types_file_header($context, $namespace, $collection['element'], $description),
        '',
        'final readonly class ' . $collection['class'],
        '{',
        '    /** @var ' . $docType . ' */',
        '    private readonly array $items;',
        '',
        '    /** @param ' . $docType . ' $items */',
        '    private function __construct(array $items)',
        '    {',
        '        $this->items = $items;',
        '    }',
        '',
        '    /**',
        '     * Construct from a homogeneous element list: the element type is',
        '     * validated, never trusted, and order is preserved.',
        '     *',
        '     * @param array<array-key, mixed> $items',
        '     */',
        '    public static function fromList(array $items): self',
        '    {',
        '        foreach ($items as $item) {',
        '            ' . $elementCheck,
        '                throw new \\InvalidArgumentException(' . $owner . ' . \': list element type mismatch\');',
        '            }',
        '        }',
        '        /** @var ' . $docType . ' $items */',
        '        return new self(array_values($items));',
        '    }',
        '',
        '    /** @return ' . $docType . ' */',
        '    public function all(): array',
        '    {',
        '        return $this->items;',
        '    }',
        '',
        '    public function count(): int',
        '    {',
        '        return count($this->items);',
        '    }',
        '',
        '    /** The empty list is a value, never a missing one. */',
        '    public function isEmpty(): bool',
        '    {',
        '        return $this->items === [];',
        '    }',
        '',
        '    public function equals(self $other): bool',
        '    {',
        '        if ($this->items === $other->items) {',
        '            return true;',
        '        }',
        '        if (count($this->items) !== count($other->items)) {',
        '            return false;',
        '        }',
        '        foreach ($this->items as $index => $item) {',
        $elementEquals,
        '                return false;',
        '            }',
        '        }',
        '        return true;',
        '    }',
        '}',
    ];
    return implode("\n", $lines) . "\n";
}

// ---------------------------------------------------------------------------
// Concrete presence wrappers.
// ---------------------------------------------------------------------------

/** The emitted text of one concrete presence wrapper. */
function php_types_wrapper_text(
    array $wrapper,
    array $definitions,
    string $prefix,
    array $context,
    string $namespace,
    ?string $description,
): string {
    $acceptsNull = $wrapper['acceptsNull'];
    $class = $wrapper['class'];
    $valueFqn = $wrapper['ofList']
        ? '\\' . $wrapper['collection']
        : '\\' . php_types_leaf_fqn($definitions, $prefix, $wrapper['element']);
    $owner = php_types_string_literal($wrapper['element']);
    $leafDefinition = $definitions[$wrapper['element']];
    $valueEquals = $leafDefinition['kind'] === 'enum'
        ? 'return $this->value === $other->value;'
        : 'return $this->value->equals($other->value);';
    $lines = [
        php_types_file_header($context, $namespace, $wrapper['element'], $description),
        '',
        'final readonly class ' . $class,
        '{',
        '    private const MODE_ABSENT = 0;',
    ];
    if ($acceptsNull) {
        $lines[] = '    private const MODE_NULL = 1;';
    }
    $lines[] = '    private const MODE_VALUE = 2;';
    $lines[] = '';
    $lines[] = '    private function __construct(';
    $lines[] = '        private readonly int $mode,';
    $lines[] = '        private readonly ?' . $valueFqn . ' $value,';
    $lines[] = '    ) {';
    $lines[] = '    }';
    $lines[] = '';
    $lines[] = '    /** The absent state: the member is not on the wire. */';
    $lines[] = '    public static function absent(): self';
    $lines[] = '    {';
    $lines[] = '        return new self(self::MODE_ABSENT, null);';
    $lines[] = '    }';
    if ($acceptsNull) {
        $lines[] = '';
        $lines[] = '    /** The explicit-null state: distinct from absent, never collapsed. */';
        $lines[] = '    public static function ofNull(): self';
        $lines[] = '    {';
        $lines[] = '        return new self(self::MODE_NULL, null);';
        $lines[] = '    }';
    }
    $lines[] = '';
    $lines[] = '    /** The carried-value state. */';
    $lines[] = '    public static function of(' . $valueFqn . ' $value): self';
    $lines[] = '    {';
    $lines[] = '        return new self(self::MODE_VALUE, $value);';
    $lines[] = '    }';
    $lines[] = '';
    $lines[] = '    public function isAbsent(): bool';
    $lines[] = '    {';
    $lines[] = '        return $this->mode === self::MODE_ABSENT;';
    $lines[] = '    }';
    if ($acceptsNull) {
        $lines[] = '';
        $lines[] = '    public function isNull(): bool';
        $lines[] = '    {';
        $lines[] = '        return $this->mode === self::MODE_NULL;';
        $lines[] = '    }';
    }
    $lines[] = '';
    $lines[] = '    /**';
    $lines[] = '     * The carried value; absent (and explicit null) is a';
    $lines[] = '     * LogicException, never a silent default.';
    $lines[] = '     */';
    $lines[] = '    public function get(): ' . $valueFqn;
    $lines[] = '    {';
    $lines[] = '        if ($this->mode !== self::MODE_VALUE || $this->value === null) {';
    $lines[] = '            throw new \\LogicException(' . $owner . ' . \': no value carried\');';
    $lines[] = '        }';
    $lines[] = '        return $this->value;';
    $lines[] = '    }';
    $lines[] = '';
    $lines[] = '    public function equals(self $other): bool';
    $lines[] = '    {';
    $lines[] = '        if ($this->mode !== $other->mode) {';
    $lines[] = '            return false;';
    $lines[] = '        }';
    $lines[] = '        if ($this->mode !== self::MODE_VALUE) {';
    $lines[] = '            return true;';
    $lines[] = '        }';
    $lines[] = '        ' . $valueEquals;
    $lines[] = '    }';
    $lines[] = '}';
    return implode("\n", $lines) . "\n";
}

// ---------------------------------------------------------------------------
// Structured DTOs and value objects.
// ---------------------------------------------------------------------------

/** The equals conjunct of one field: exact, null-aware, never loose. */
function php_types_field_equals(array $field, array $definitions, string $prefix): string
{
    $left = '$this->' . $field['property'];
    $right = '$other->' . $field['property'];
    if (isset($field['type']['wrapper'])) {
        return $left . '->equals(' . $right . ')';
    }
    if ($field['type']['list']) {
        return $left . '->equals(' . $right . ')';
    }
    $definition = $definitions[$field['type']['leaf']];
    if ($definition['kind'] === 'enum') {
        return $left . ' === ' . $right;
    }
    if ($field['nullable']) {
        // Both null (or both identical) or both present and equal.
        return '(' . $left . ' === ' . $right . ')'
            . ' || (' . $left . ' !== null && ' . $right . ' !== null && ' . $left . '->equals(' . $right . '))';
    }
    return $left . '->equals(' . $right . ')';
}

/** The emitted text of one structured DTO/value-object class. */
function php_types_structured_text(
    array $entry,
    array $definitions,
    string $prefix,
    array $context,
    string $namespace,
    ?string $description,
): string {
    $class = php_types_entry_class($entry);
    $lines = [
        php_types_file_header($context, $namespace, $entry['semanticId'], $description),
        '',
        'final readonly class ' . $class,
        '{',
        '    public function __construct(',
    ];
    foreach ($entry['fields'] as $field) {
        $type = php_types_field_php_type($field, $definitions, $prefix);
        $lines[] = '        public readonly ' . $type . ' $' . $field['property'] . ',';
    }
    $lines[] = '    ) {';
    $lines[] = '    }';
    if ($entry['fields'] !== []) {
        $lines[] = '';
        $lines[] = '    /** Exact value equality over the immutable state. */';
        $lines[] = '    public function equals(self $other): bool';
        $lines[] = '    {';
        $conjuncts = array_map(
            static fn (array $field): string => php_types_field_equals($field, $definitions, $prefix),
            $entry['fields'],
        );
        $lines[] = '        return ' . implode("\n            && ", $conjuncts) . ';';
        $lines[] = '    }';
    }
    $lines[] = '}';
    return implode("\n", $lines) . "\n";
}

// ---------------------------------------------------------------------------
// Codecs.
// ---------------------------------------------------------------------------

/** The emitted text of one structured codec class. */
function php_types_codec_text(
    array $entry,
    array $definitions,
    string $prefix,
    array $context,
    string $namespace,
    ?string $description,
): string {
    $class = php_types_entry_class($entry) . 'Codec';
    $typeFqn = '\\' . $entry['fqn'];
    $owner = php_types_string_literal($entry['semanticId']);
    $members = implode(', ', array_map(
        static fn (array $field): string => php_types_string_literal($field['name']),
        $entry['fields'],
    ));
    $decode = [];
    $encode = [];
    $helpers = [];
    foreach ($entry['fields'] as $field) {
        $decode[] = php_types_field_decode($field, $definitions, $prefix, $entry['semanticId']);
        $encode[] = php_types_field_encode($field, $definitions, $prefix);
        if ($field['type']['list']) {
            $helpers[] = php_types_list_helpers($field, $definitions, $prefix, $entry['semanticId']);
        }
    }
    $indent = static function (string $block): string {
        return implode("\n", array_map(
            static fn (string $line): string => $line === '' ? $line : '        ' . $line,
            explode("\n", $block),
        ));
    };
    $constructorArgs = implode(', ', array_map(
        static fn (array $field): string => '$' . $field['property'],
        $entry['fields'],
    ));
    $lines = [
        php_types_file_header($context, $namespace, $entry['semanticId'], $description),
        '',
        'final readonly class ' . $class,
        '{',
        '    private const MEMBERS = [' . $members . '];',
        '',
        '    /**',
        '     * Decode one wire object into the typed value: the member set is',
        '     * closed, presence is exact, and every primitive is validated.',
        '     */',
        '    public static function decode(mixed $wire): ' . $typeFqn,
        '    {',
        '        if (!is_array($wire)) {',
        '            throw new \\InvalidArgumentException(' . $owner . ' . \': wire value is not an object\');',
        '        }',
        '        foreach (array_keys($wire) as $key) {',
        '            if (!in_array($key, self::MEMBERS, true)) {',
        '                throw new \\InvalidArgumentException(' . $owner . ' . \': unknown wire member `\' . $key . \'`\');',
        '            }',
        '        }',
        "\n" . $indent(implode("\n\n", $decode)),
        '        return new ' . $typeFqn . '(' . $constructorArgs . ');',
        '    }',
        '',
        '    /**',
        '     * Encode the typed value back to the wire shape: verbatim member',
        '     * names, absent optionals omitted, explicit nulls preserved.',
        '     */',
        '    public static function encode(' . $typeFqn . ' $value): array',
        '    {',
        '        $result = [];',
        ($encode === [] ? '' : "\n" . $indent(implode("\n", $encode))),
        '        return $result;',
        '    }',
    ];
    foreach ($helpers as $helper) {
        $lines[] = '';
        $lines[] = $helper;
    }
    $lines[] = '}';
    return implode("\n", $lines) . "\n";
}

/** The PHP return type spelling of one query return expression. */
function php_types_query_return_type(array $entry, array $definitions, string $prefix): string
{
    $expr = $entry['returns'];
    if ($expr['list']) {
        $definition = $definitions[$expr['leaf']];
        $class = php_types_stem_of($expr['leaf'], $definition['kind'])
            . ($expr['nullableElements'] ? 'NullableList' : 'List');
        $type = php_types_fqn_of($prefix, php_types_module_of($expr['leaf']), $class);
    } else {
        $type = php_types_leaf_fqn($definitions, $prefix, $expr['leaf']);
    }
    // Inside the codec file the type spells fully qualified, so the
    // relative namespace resolution can never alias it.
    $type = '\\' . $type;
    return $expr['nullable'] ? '?' . $type : $type;
}

/** The emitted text of one query result codec (a direct-body passthrough). */
function php_types_query_codec_text(
    array $entry,
    array $definitions,
    string $prefix,
    array $context,
    string $namespace,
    ?string $description,
): string {
    $class = php_types_entry_class($entry);
    $expr = $entry['returns'];
    $decodeType = php_types_query_return_type($entry, $definitions, $prefix);
    $leaf = $expr['leaf'];
    $definition = $definitions[$leaf];
    if ($expr['list']) {
        $decodeExpr = 'self::decodeResult($wire)';
        $encodeExpr = 'self::encodeResult($value)';
        $helpers = [php_types_query_list_helper($entry, $definitions, $prefix)];
    } else {
        $decodeExpr = php_types_leaf_decode($definitions, $prefix, $leaf, '$wire');
        $encodeExpr = php_types_leaf_encode($definitions, $prefix, $leaf, '$value');
        $helpers = [];
    }
    $encodeType = $expr['list'] ? 'array' : (($definition['kind'] === 'enum' || $definition['base'] === 'string'
        || $definition['base'] === 'date' || $definition['base'] === 'datetime'
        || $definition['base'] === 'uuid' || $definition['base'] === 'uri') ? 'string' : 'int|float|bool');
    $encodeType = $expr['nullable'] ? ('null|' . $encodeType) : $encodeType;
    $decodeTypeNullable = $expr['nullable'] ? '?' . ltrim($decodeType, '?') : $decodeType;
    $encodeNullGuard = $expr['nullable'] ? '$value === null ? null : ' : '';
    $lines = [
        php_types_file_header($context, $namespace, $entry['semanticId'], $description),
        '',
        'final readonly class ' . $class,
        '{',
        '    /**',
        '     * Decode the direct query output: the declared return type is the',
        '     * body; no envelope exists.',
        '     */',
        '    public static function decode(mixed $wire): ' . $decodeTypeNullable,
        '    {',
        '        return $wire === null ? null : ' . $decodeExpr . ';',
        '    }',
        '',
        '    public static function encode(' . $decodeTypeNullable . ' $value): ' . $encodeType,
        '    {',
        '        return ' . $encodeNullGuard . $encodeExpr . ';',
        '    }',
    ];
    foreach ($helpers as $helper) {
        $lines[] = '';
        $lines[] = $helper;
    }
    $lines[] = '}';
    return implode("\n", $lines) . "\n";
}

/** The list decode/encode helper pair of a list-valued query return. */
function php_types_query_list_helper(array $entry, array $definitions, string $prefix): string
{
    $expr = $entry['returns'];
    $definition = $definitions[$expr['leaf']];
    $class = php_types_stem_of($expr['leaf'], $definition['kind'])
        . ($expr['nullableElements'] ? 'NullableList' : 'List');
    $collection = $prefix . '\\' . ucfirst(php_types_module_of($expr['leaf'])) . '\\' . $class;
    $owner = php_types_string_literal($entry['semanticId']);
    $elementDecode = $expr['nullableElements']
        ? '$element === null ? null : ' . php_types_leaf_decode($definitions, $prefix, $expr['leaf'], '$element')
        : php_types_leaf_decode($definitions, $prefix, $expr['leaf'], '$element');
    $elementEncode = $expr['nullableElements']
        ? '$element === null ? null : ' . php_types_leaf_encode($definitions, $prefix, $expr['leaf'], '$element')
        : php_types_leaf_encode($definitions, $prefix, $expr['leaf'], '$element');

    return implode("\n", [
        '    private static function decodeResult(mixed $raw): \\' . $collection,
        '    {',
        '        if (!is_array($raw) || !array_is_list($raw)) {',
        '            throw new \\InvalidArgumentException(' . $owner . ' . \': query output is not a list\');',
        '        }',
        '        $items = [];',
        '        foreach ($raw as $element) {',
        '            $items[] = ' . $elementDecode . ';',
        '        }',
        '        return \\' . $collection . '::fromList($items);',
        '    }',
        '',
        '    private static function encodeResult(\\' . $collection . ' $value): array',
        '    {',
        '        $items = [];',
        '        foreach ($value->all() as $element) {',
        '            $items[] = ' . $elementEncode . ';',
        '        }',
        '        return $items;',
        '    }',
    ]);
}

// ---------------------------------------------------------------------------
// Class map and sidecar.
// ---------------------------------------------------------------------------

/** The deterministic class map of one generation. */
function php_types_classmap_text(array $artifacts, array $context, string $prefix): string
{
    $entries = [];
    foreach ($artifacts as $artifact) {
        if (in_array($artifact['role'], ['class-map'], true) || $artifact['path'] === 'types.map.json') {
            continue;
        }
        if (str_ends_with($artifact['path'], '.php')) {
            $entries[$artifact['fqn']] = $artifact['path'];
        }
    }
    ksort($entries, SORT_STRING);
    $lines = [
        '<?php',
        '',
        'declare(strict_types=1);',
        '',
        '// Generated by lekalo-target-php-laravel@' . $context['adapterVersion']
            . ' (type generator, issue #58).',
        '// From ' . PHP_TYPES_IR_IDENTITY . ' input ' . $context['irDigest']
            . '. Do not edit: regenerate with `lekalo generate`.',
        '// The deterministic class map of this generation.',
        '',
        'return [',
    ];
    foreach ($entries as $fqn => $path) {
        $lines[] = '    ' . php_types_string_literal($fqn) . ' => __DIR__ . '
            . php_types_string_literal('/' . $path) . ',';
    }
    $lines[] = '];';
    return implode("\n", $lines) . "\n";
}

/**
 * The authoritative mapping sidecar: contract identity, provenance
 * digests, semantic-ID-sorted type entries, and the path-sorted
 * artifact inventory. Internal mapping keys never surface.
 */
function php_types_sidecar_document(string $projectId, array $mapped, array $context, string $root): array
{
    $types = [];
    foreach ($mapped['types'] as $entry) {
        $row = [
            'semanticId' => $entry['semanticId'],
            'kind' => $entry['kind'],
            'fqn' => $entry['fqn'],
            'path' => $entry['path'],
        ];
        if (isset($entry['base'])) {
            $row['base'] = $entry['base'];
        }
        if (isset($entry['values'])) {
            $row['values'] = array_map(
                static fn (array $value): array => ['case' => $value['case'], 'value' => $value['value']],
                $entry['values'],
            );
        }
        if (isset($entry['fields'])) {
            $row['fields'] = array_map(
                static fn (array $field): array => [
                    'name' => $field['name'],
                    'property' => $field['property'],
                    'type' => $field['type'],
                    'presence' => $field['presence'],
                    'nullable' => $field['nullable'],
                ],
                $entry['fields'],
            );
        }
        if (isset($entry['returns'])) {
            $row['returns'] = $entry['returns'];
        }
        $row['codec'] = $entry['codec'];
        $types[] = $row;
    }
    return [
        'schemaVersion' => PHP_TYPES_MAP_SCHEMA_VERSION,
        'identity' => PHP_TYPES_MAP_IDENTITY,
        'adapter' => ['id' => 'lekalo-target-php-laravel', 'version' => $context['adapterVersion']],
        'projectId' => $projectId,
        'custody' => $context['custody'],
        'namespacePrefix' => $mapped['policy']['namespacePrefix'],
        'generatedRoot' => $root,
        'digests' => $mapped['digests'],
        'types' => $types,
        'artifacts' => $mapped['artifacts'],
    ];
}
