<?php

declare(strict_types=1);

// Generated by lekalo-target-php-laravel@0.2.0 (type generator, issue #58).
// From dev.lekalo.ir@0.2.16 input sha256:e1a2173af461cb43cfa58f091bd92a439f8cfa53aba7aea33481d85d6977decd.
// Semantic id: planner.due_date.
// Description: Calendar due date
// Do not edit: regenerate with `lekalo generate`.

namespace Lekalo\Generated\Types\Planner\Optional;

final readonly class OptionalNullableDueDate
{
    private const MODE_ABSENT = 0;
    private const MODE_NULL = 1;
    private const MODE_VALUE = 2;

    private function __construct(
        private readonly int $mode,
        private readonly ?\Lekalo\Generated\Types\Planner\DueDate $value,
    ) {
    }

    /** The absent state: the member is not on the wire. */
    public static function absent(): self
    {
        return new self(self::MODE_ABSENT, null);
    }

    /** The explicit-null state: distinct from absent, never collapsed. */
    public static function ofNull(): self
    {
        return new self(self::MODE_NULL, null);
    }

    /** The carried-value state. */
    public static function of(\Lekalo\Generated\Types\Planner\DueDate $value): self
    {
        return new self(self::MODE_VALUE, $value);
    }

    public function isAbsent(): bool
    {
        return $this->mode === self::MODE_ABSENT;
    }

    public function isNull(): bool
    {
        return $this->mode === self::MODE_NULL;
    }

    /**
     * The carried value; absent (and explicit null) is a
     * LogicException, never a silent default.
     */
    public function get(): \Lekalo\Generated\Types\Planner\DueDate
    {
        if ($this->mode !== self::MODE_VALUE || $this->value === null) {
            throw new \LogicException('planner.due_date' . ': no value carried');
        }
        return $this->value;
    }

    public function equals(self $other): bool
    {
        if ($this->mode !== $other->mode) {
            return false;
        }
        if ($this->mode !== self::MODE_VALUE) {
            return true;
        }
        return $this->value->equals($other->value);
    }
}
