<?php

declare(strict_types=1);

// Generated by lekalo-target-php-laravel@0.2.0 (type generator, issue #58).
// From dev.lekalo.ir@0.2.16 input sha256:e1a2173af461cb43cfa58f091bd92a439f8cfa53aba7aea33481d85d6977decd.
// Semantic id: planner.task.
// Description: A focusable task
// Do not edit: regenerate with `lekalo generate`.

namespace Lekalo\Generated\Types\Planner;

final readonly class TaskDto
{
    public function __construct(
        public readonly \Lekalo\Generated\Types\Planner\TaskId $taskId,
        public readonly \Lekalo\Generated\Types\Planner\Text $title,
        public readonly \Lekalo\Generated\Types\Planner\TaskState $state,
        public readonly \Lekalo\Generated\Types\Planner\Optional\OptionalNullableDueDate $due,
        public readonly \Lekalo\Generated\Types\Planner\Optional\OptionalDueWindowList $window,
    ) {
    }

    /** Exact value equality over the immutable state. */
    public function equals(self $other): bool
    {
        return $this->taskId->equals($other->taskId)
            && $this->title->equals($other->title)
            && $this->state === $other->state
            && $this->due->equals($other->due)
            && $this->window->equals($other->window);
    }
}
