<?php

declare(strict_types=1);

// Generated by lekalo-target-php-laravel@0.2.0 (type generator, issue #58).
// From dev.lekalo.ir@0.2.16 input sha256:e1a2173af461cb43cfa58f091bd92a439f8cfa53aba7aea33481d85d6977decd.
// Semantic id: planner.task_state.
// Description: Task lifecycle state
// Do not edit: regenerate with `lekalo generate`.

namespace Lekalo\Generated\Types\Planner;

enum TaskState: string
{
    case Backlog = 'backlog';
    case Focused = 'focused';
    case Done = 'done';

    /**
     * Decode one wire value: the declared members are the closed
     * vocabulary; anything else refuses.
     */
    public static function fromWire(mixed $raw): self
    {
        $case = is_string($raw) ? self::tryFrom($raw) : null;
        if ($case === null) {
            throw new \InvalidArgumentException('planner.task_state' . ': unknown enum wire value');
        }
        return $case;
    }

    /** The exact declared wire value. */
    public function toWire(): string
    {
        return $this->value;
    }
}
