// Generated by lekalo-target-node-typescript@0.3.2
// (zod-schema-generator) from dev.lekalo.ir@0.2.16 input sha256:76ec6ce5dc6f2dda04baaf82340129c3e6e82459443639704221fbd76dd04d34.
// Do not edit: regenerate with `lekalo generate`. Presence (required)
// and nullability (optional wrapper) are orthogonal axes here:
// `required` governs key presence, the optional wrapper emits
// `.nullable()`. Closed objects mirror the closed model (.strict()).

import * as z from "zod";
import { LekaloDateString, lekaloBrand } from "./runtime";

export const AlphaCountSchema = z.number().finite();
export type AlphaCount = z.infer<typeof AlphaCountSchema>;
export const AlphaCountTasksResultSchema = AlphaCountSchema;
export type AlphaCountTasksResult = z.infer<typeof AlphaCountTasksResultSchema>;
export const AlphaDaySchema = LekaloDateString;
export type AlphaDay = z.infer<typeof AlphaDaySchema>;
export const AlphaTagSchema = z.string();
export type AlphaTag = z.infer<typeof AlphaTagSchema>;
export const AlphaDeepSchema = z.object({
  "deep": z.array(z.array(AlphaTagSchema).nullable()),
}).strict();
export type AlphaDeep = z.infer<typeof AlphaDeepSchema>;
export const AlphaFlagSchema = z.boolean();
export type AlphaFlag = z.infer<typeof AlphaFlagSchema>;
export const AlphaTaskIdSchema = lekaloBrand(z.string().uuid(), "alpha.task_id");
export type AlphaTaskId = z.infer<typeof AlphaTaskIdSchema>;
export const AlphaFocusTaskInputSchema = z.object({
  "task_id": AlphaTaskIdSchema,
}).strict();
export type AlphaFocusTaskInput = z.infer<typeof AlphaFocusTaskInputSchema>;
export const AlphaLinkSchema = z.string().url();
export type AlphaLink = z.infer<typeof AlphaLinkSchema>;
export const AlphaTextSchema = z.string();
export type AlphaText = z.infer<typeof AlphaTextSchema>;
export const AlphaMatrixSchema = z.object({
  "plain": AlphaTextSchema,
  "nullable": AlphaTextSchema.nullable(),
  "optionalKey": AlphaTextSchema.optional(),
  "optionalNullable": AlphaTextSchema.nullable().optional(),
}).strict();
export type AlphaMatrix = z.infer<typeof AlphaMatrixSchema>;
export const AlphaMomentSchema = z.string().datetime({ offset: true });
export type AlphaMoment = z.infer<typeof AlphaMomentSchema>;
export const AlphaStateSchema = z.enum(["backlog", "focused", "done"]);
export type AlphaState = z.infer<typeof AlphaStateSchema>;
export const AlphaTaskSchema = z.object({
  "task_id": AlphaTaskIdSchema,
  "title": AlphaTextSchema,
  "state": AlphaStateSchema,
  "day": AlphaDaySchema,
  "moment": AlphaMomentSchema,
  "link": AlphaLinkSchema,
  "count": AlphaCountSchema,
  "flag": AlphaFlagSchema,
}).strict();
export type AlphaTask = z.infer<typeof AlphaTaskSchema>;
export const AlphaTaskFocusedPayloadSchema = z.object({
  "task_id": AlphaTaskIdSchema,
  "at": AlphaMomentSchema,
}).strict();
export type AlphaTaskFocusedPayload = z.infer<typeof AlphaTaskFocusedPayloadSchema>;
export const BetaReportIdSchema = lekaloBrand(z.string().uuid(), "beta.report_id");
export type BetaReportId = z.infer<typeof BetaReportIdSchema>;
export const BetaReportSchema = z.object({
  "report_id": BetaReportIdSchema,
  "title": AlphaTextSchema,
}).strict();
export type BetaReport = z.infer<typeof BetaReportSchema>;
export const AlphaWithReportSchema = z.object({
  "report": BetaReportSchema,
  "tags": z.array(AlphaTagSchema),
}).strict();
export type AlphaWithReport = z.infer<typeof AlphaWithReportSchema>;
