// Generated by lekalo-target-node-typescript@0.3.2 (zod-schema-generator).
// Adapter-owned runtime helpers shared by every generated module. Content
// depends only on the adapter version, so this file is itself a
// determinism probe: any byte drift means a stale artifact. Do not edit;
// regenerate with `lekalo generate`.
import * as z from "zod";

/** A calendar date string (YYYY-MM-DD): the JSON-faithful date form. */
export const LekaloDateString = z.string().regex(/^\d{4}-\d{2}-\d{2}$/);

/**
 * Brand one schema with its Lekalo semantic id: `z.infer` yields
 * `<base> & z.BRAND<"module.name">`, so raw values cannot masquerade as
 * opaque ids — they must pass `.parse`. The brand applies over the
 * scalar's own declared base schema (uuid, string, number, date, …);
 * branding never tightens validation beyond the base. The two-argument
 * form keeps the emitted files plain-JS executable.
 *
 * @template {{ safeParse: Function }} T
 * @param {T} schema
 * @param {string} semanticId
 * @returns {T}
 */
export function lekaloBrand(schema, semanticId) {
  return schema.brand(semanticId);
}

/**
 * Map raw zod issues to Lekalo semantic ids through the field map of the
 * sibling `<module>.map.json` sidecar. Exact field paths win; otherwise
 * the closest enclosing path wins; otherwise the module owner. Unknown
 * input paths are attributed, never dropped. The issue parameter is the
 * structural shape every zod issue satisfies, so plain JavaScript
 * consumers can call this helper without importing zod.
 *
 * @param {{ path: (string | number)[], code: string }[]} issues
 * @param {Record<string, string>} fields
 * @param {string} owner
 * @returns {{ path: string, semanticId: string, code: string }[]}
 */
export function normalizeIssues(issues, fields, owner) {
  return issues.map((issue) => {
    const path = issue.path.join(".");
    return {
      path,
      semanticId: resolveFieldOwner(fields, path, owner),
      code: issue.code,
    };
  });
}

/**
 * Exact path first, then the closest enclosing mapped path, then the
 * mapped root symbol (the `""` entry), and only then the owner
 * argument — one fallback chain, coherent with the sidecar bytes.
 *
 * @param {Record<string, string>} fields
 * @param {string} path
 * @param {string} owner
 * @returns {string}
 */
function resolveFieldOwner(fields, path, owner) {
  if (Object.prototype.hasOwnProperty.call(fields, path)) {
    return fields[path];
  }
  let prefix = path;
  for (;;) {
    const cut = prefix.lastIndexOf(".");
    if (cut <= 0) break;
    prefix = prefix.slice(0, cut);
    if (Object.prototype.hasOwnProperty.call(fields, prefix)) {
      return fields[prefix];
    }
  }
  if (Object.prototype.hasOwnProperty.call(fields, "")) {
    return fields[""];
  }
  return owner;
}
