#!/usr/bin/env node
/**
 * The orchestration reference adapter (issue #91 fixtures).
 *
 * A dependency-free Node.js adapter implementing the `lekalo.target/v1`
 * handshake for the planner-pipeline end-to-end fixtures: protocol
 * 1.0.0-1.2.0 negotiation, the `node-typescript` target, deterministic
 * create plans under the declared write scope, and honest `validate`
 * and `verify` results. Read scope covers the canonical IR cache home
 * (`.lekalo/cache/ir/**`); the write scope is the adapter's managed
 * root in the target source tree (`src/generated/node-typescript/**`),
 * because ownership-manifest artifacts never live under the runtime
 * home. The read scope covers the canonical IR cache home
 * (`.lekalo/cache/ir/**`).
 *
 * The same deterministic inputs always produce the same plan and bytes,
 * which is what the dry-run/apply cross-check and the byte-stable
 * ownership manifest require.
 */

import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname } from "node:path";

const ADAPTER = {
  id: "node-typescript",
  version: "0.1.0",
  digest: sha256("lekalo orchestration reference adapter v1"),
};

function sha256(text) {
  return "sha256:" + createHash("sha256").update(text).digest("hex");
}

/** Canonical compact JSON: byte-sorted keys, exactly like the core. */
function canonical(value) {
  if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`;
  if (value && typeof value === "object") {
    const body = Object.keys(value)
      .sort()
      .map((key) => `${JSON.stringify(key)}:${canonical(value[key])}`)
      .join(",");
    return `{${body}}`;
  }
  return JSON.stringify(value);
}

function readRequest() {
  const marker = process.argv.indexOf("--lekalo-request-file");
  if (marker !== -1 && process.argv[marker + 1]) {
    return readFileSync(process.argv[marker + 1], "utf8");
  }
  return readFileSync(0, "utf8");
}

function deterministicWrites(request) {
  const target = request.target ?? "node-typescript";
  const profile = request.profile ?? "default";
  const irPath = request.ir_path ?? ".lekalo/cache/ir/planner.json";
  const body =
    `// generated by ${ADAPTER.id}@${ADAPTER.version}\n` +
    `// target: ${target}\n` +
    `// profile: ${profile}\n` +
    `// ir: ${irPath}\n`;
  const path = `src/generated/${ADAPTER.id}/planner.ts`;
  // The staged write scope exposes existing files as empty shape
  // placeholders: existence decides the honest action.
  const action = existsSync(path) ? "replace" : "create";
  const writes = [{ path, action, sha256: sha256(body) }];
  return { body, writes };
}

function capabilities(requestedVersion) {
  const declared = {
    adapter: ADAPTER,
    protocol_versions: ["1.0.0", "1.1.0", "1.2.0"],
    operations: ["describe", "validate", "generate", "verify"],
    targets: ["node-typescript"],
    profiles: ["default"],
    read_scopes: [".lekalo/cache/ir/**"],
    transports: ["stdin", "file"],
    progress: true,
    write_scopes: [`src/generated/${ADAPTER.id}/**`],
  };
  if (requestedVersion !== "1.0.0") {
    declared.ir_versions = ["0.1.0"];
    declared.capabilities = {
      "generate.zod": "full",
      "verify.scenarios": "partial",
    };
    declared.constraints = { max_entries: 1000 };
  }
  return declared;
}

function respond(request, payload) {
  const envelope = {
    protocol: "lekalo.target/v1",
    protocol_version: request.protocol_version,
    operation: request.operation,
    request_id: request.request_id,
    status: "ok",
    evidence: { adapter: ADAPTER },
    ...payload,
  };
  process.stdout.write(canonical(envelope));
}

function fail(request, errorClass, code, message) {
  const envelope = {
    protocol: "lekalo.target/v1",
    protocol_version: request.protocol_version,
    operation: request.operation,
    request_id: request.request_id,
    status: "error",
    evidence: { adapter: ADAPTER },
    error: { class: errorClass, code, message, partial: false },
  };
  process.stdout.write(canonical(envelope));
}

const request = JSON.parse(readRequest());

switch (request.operation) {
  case "describe":
    respond(request, { capabilities: capabilities(request.protocol_version) });
    break;
  case "validate":
    respond(request, { result: { ok: true, findings: [] } });
    break;
  case "verify":
    respond(request, { result: { ok: true, findings: [] } });
    break;
  case "generate": {
    const { body, writes } = deterministicWrites(request);
    const target = `src/generated/${ADAPTER.id}/planner.ts`;
    if (request.dry_run === false) {
      mkdirSync(dirname(target), { recursive: true });
      writeFileSync(target, body);
    }
    respond(request, {
      writes,
      evidence: {
        adapter: ADAPTER,
        plan_id: request.plan_id ?? planId(writes),
      },
      progress: [
        { step: "compile", state: "done" },
        { step: "emit", state: "done" },
      ],
    });
    break;
  }
  default:
    fail(request, "invalid", "fixture-operation", `unknown operation ${request.operation}`);
}

function planId(writes) {
  return "plan-" + sha256(canonical(writes)).slice("sha256:".length);
}
