//! The deterministic ownership-aware merge (issue #46, plan §4.3).
//!
//! [`merge`] is a pure function used identically by the adapter's emit
//! path and by `lekalo openapi check` — merge is verified, not just
//! performed. The merge unit is the JSON pointer
//! (`/paths/<template>/<method>`, `/components/schemas/<Name>`, …):
//!
//! 1. absent pointers insert in canonical position;
//! 2. pointers the existing ownership manifest owns replace their own
//!    bytes — never anyone else's;
//! 3. pointers under manual ownership are left untouched: a bound
//!    manual operation identical to its recomputed fragment is clean,
//!    a differing one reports `openapi.drift`, anything else collides
//!    as `openapi.merge-conflict`;
//! 4. orphan generated pointers (endpoint removed from the attachment)
//!    are removed only when still generator-owned; a manual operation
//!    binding nothing is preserved and reported informationally —
//!    never an error, never deleted.
//!
//! The merged tree serializes deterministically: byte-sorted keys, one
//! canonical JSON form, so the same inputs always produce the same
//! bytes.

use std::collections::BTreeMap;

use serde_json::{Map, Value as Json};

use super::bind::BindingKey;
use super::diagnostic;
use super::fragments::{Fragments, OwnershipManifest};

/// The finished merge: the merged tree plus the typed per-pointer
/// actions and findings.
#[derive(Clone, Debug, Eq, PartialEq, Default)]
pub struct MergeOutcome {
    tree: Json,
    inserted: Vec<String>,
    replaced: Vec<String>,
    removed: Vec<String>,
    /// Generated pointers under manual ownership: `(pointer, owner)`.
    conflicts: Vec<(String, String)>,
    /// Bound manual operations differing from their recomputed
    /// fragment: `(pointer, endpoint id)`.
    drifts: Vec<(String, String)>,
    /// Manual operations binding nothing: `(pointer, detail)` —
    /// informational, preserved.
    manual: Vec<(String, String)>,
}

impl MergeOutcome {
    /// The merged document tree.
    pub fn tree(&self) -> &Json {
        &self.tree
    }

    /// The canonical bytes of the merged tree.
    pub fn canonical_bytes(&self) -> String {
        self.tree.to_string()
    }

    /// Inserted generated pointers.
    pub fn inserted(&self) -> &[String] {
        &self.inserted
    }

    /// Replaced generator-owned pointers.
    pub fn replaced(&self) -> &[String] {
        &self.replaced
    }

    /// Removed orphan generator-owned pointers.
    pub fn removed(&self) -> &[String] {
        &self.removed
    }

    /// Manual collisions: `(pointer, owner)` — never overwritten.
    pub fn conflicts(&self) -> &[(String, String)] {
        &self.conflicts
    }

    /// Drifting bound manual operations: `(pointer, endpoint id)`.
    pub fn drifts(&self) -> &[(String, String)] {
        &self.drifts
    }

    /// Unbound manual operations: `(pointer, detail)`.
    pub fn manual(&self) -> &[(String, String)] {
        &self.manual
    }

    /// Whether the merge hit any fatal condition (a manual collision).
    pub fn is_clean(&self) -> bool {
        self.conflicts.is_empty()
    }

    /// The fatal refusal set for the merge, or the outcome itself when
    /// clean. A collision refuses the run: generated bytes must never
    /// overwrite manual ownership.
    pub fn into_result(self) -> Result<Self, super::diagnostic::DiagnosticSet> {
        match self.conflicts.first() {
            Some((pointer, owner)) => Err(diagnostic::merge_conflict(
                pointer,
                &format!("manual-owner:{}", diagnostic::bounded(owner)),
            )),
            None => Ok(self),
        }
    }
}

/// Merge the recomputed fragments into the existing document tree.
///
/// `generated` is the recomputed ownership manifest (what this run
/// would own); `ownership` is the existing sidecar manifest (the
/// previous run's claims). Both pure data; nothing reads the
/// filesystem.
pub fn merge(
    existing: &Json,
    fragments: &Fragments,
    generated: &OwnershipManifest,
    ownership: &OwnershipManifest,
) -> Result<MergeOutcome, super::diagnostic::DiagnosticSet> {
    let mut tree = existing.clone();
    let mut outcome = MergeOutcome {
        tree: Json::Null,
        ..Default::default()
    };

    // Inventory of the existing operations for the bind check and the
    // manual inventory: pointer → (binding key, value).
    let mut existing_operations: BTreeMap<String, (Option<BindingKey>, Json)> = BTreeMap::new();
    if let Some(paths) = tree.get("paths").and_then(Json::as_object) {
        for (template, item) in paths {
            let Some(item) = item.as_object() else {
                continue;
            };
            for (method, operation) in item {
                if !is_method(method) {
                    continue;
                }
                existing_operations.insert(
                    format!("/paths/{}/{}", super::id::escape_pointer(template), method),
                    (BindingKey::of(operation), operation.clone()),
                );
            }
        }
    }

    // Step 1–3: every generated pointer.
    for (pointer, fragment) in fragments.as_map() {
        match pointer_get(&tree, pointer) {
            None => {
                pointer_insert(&mut tree, pointer, fragment.clone())?;
                outcome.inserted.push(pointer.clone());
            }
            Some(existing_value) => {
                if ownership.owner(pointer).is_some() {
                    // Generator-owned: replace our own bytes.
                    pointer_insert(&mut tree, pointer, fragment.clone())?;
                    outcome.replaced.push(pointer.clone());
                    continue;
                }
                // Manual or unclaimed. The bind check applies to
                // operations: a manual operation bound to this
                // generated endpoint is clean when identical, drift
                // when different, a collision otherwise.
                let owner = generated.owner(pointer);
                if let (Some(owner), Some((binding, _))) = (owner, existing_operations.get(pointer))
                {
                    let fragment_operation_id = fragment
                        .get("operationId")
                        .and_then(Json::as_str)
                        .unwrap_or_default();
                    if binding
                        .as_ref()
                        .is_some_and(|key| key.binds(owner, fragment_operation_id))
                    {
                        if existing_value == fragment {
                            outcome
                                .manual
                                .push((pointer.clone(), "bound-identical".to_owned()));
                        } else {
                            outcome.drifts.push((pointer.clone(), owner.clone()));
                        }
                        continue;
                    }
                }
                let owner = owner.cloned().unwrap_or_default();
                outcome.conflicts.push((pointer.clone(), owner));
            }
        }
    }

    // Step 4: orphan generator-owned pointers (endpoint removed).
    for (pointer, owner) in ownership.pointers() {
        if fragments.get(pointer).is_some() {
            continue;
        }
        let _ = owner;
        if pointer_remove(&mut tree, pointer)? {
            outcome.removed.push(pointer.clone());
        }
    }

    // The manual inventory: every existing operation binding nothing.
    for (pointer, (binding, _)) in &existing_operations {
        if fragments.get(pointer).is_some() {
            // Generated, or classified above (bound-identical, drift,
            // conflict).
            continue;
        }
        if ownership.owner(pointer).is_some() {
            // Generator-owned and removed above (orphan).
            continue;
        }
        match binding {
            Some(_) => outcome
                .manual
                .push((pointer.clone(), "unbound-foreign".to_owned())),
            None => outcome.manual.push((pointer.clone(), "unbound".to_owned())),
        }
    }

    outcome.tree = tree;
    Ok(outcome)
}

/// Whether one path-item member key is an HTTP method slot the merge
/// treats as an operation.
fn is_method(key: &str) -> bool {
    matches!(
        key,
        "get" | "put" | "post" | "delete" | "options" | "head" | "patch" | "trace"
    )
}

/// Resolve one pointer inside the tree.
fn pointer_get<'a>(tree: &'a Json, pointer: &str) -> Option<&'a Json> {
    let mut current = tree;
    for token in pointer_tokens(pointer) {
        current = current.as_object()?.get(&token)?;
    }
    Some(current)
}

/// Insert (or replace) one pointer, creating intermediate objects.
fn pointer_insert(
    tree: &mut Json,
    pointer: &str,
    value: Json,
) -> Result<(), super::diagnostic::DiagnosticSet> {
    let tokens = pointer_tokens(pointer);
    let Some((leaf, parents)) = tokens.split_last() else {
        return Err(diagnostic::input_invalid("pointer-empty"));
    };
    let mut current = tree;
    if !current.is_object() {
        *current = Json::Object(Map::new());
    }
    for token in parents {
        let entry = current
            .as_object_mut()
            .expect("object checked")
            .entry(token.clone())
            .or_insert_with(|| Json::Object(Map::new()));
        if !entry.is_object() {
            return Err(diagnostic::input_invalid("pointer-object"));
        }
        current = entry;
    }
    current
        .as_object_mut()
        .expect("object checked")
        .insert(leaf.clone(), value);
    Ok(())
}

/// Remove one pointer leaf and prune now-empty parent objects (the
/// root always stays an object: OpenAPI requires `paths` even when
/// empty). Returns whether a leaf was removed.
fn pointer_remove(
    tree: &mut Json,
    pointer: &str,
) -> Result<bool, super::diagnostic::DiagnosticSet> {
    let tokens = pointer_tokens(pointer);
    let Some((leaf, parents)) = tokens.split_last() else {
        return Err(diagnostic::input_invalid("pointer-empty"));
    };
    Ok(remove_at(tree, parents, leaf))
}

/// The recursive pointer removal with empty-parent pruning.
fn remove_at(node: &mut Json, parents: &[String], leaf: &str) -> bool {
    let Some(object) = node.as_object_mut() else {
        return false;
    };
    match parents.split_first() {
        None => object.remove(leaf).is_some(),
        Some((head, tail)) => {
            let removed = match object.get_mut(head) {
                Some(child) => remove_at(child, tail, leaf),
                None => false,
            };
            if removed {
                let child_empty = object
                    .get(head)
                    .and_then(Json::as_object)
                    .is_some_and(Map::is_empty);
                if child_empty {
                    object.remove(head);
                }
            }
            removed
        }
    }
}

/// Unescape one RFC 6901 pointer into its tokens.
fn pointer_tokens(pointer: &str) -> Vec<String> {
    pointer
        .split('/')
        .skip(1)
        .map(|token| token.replace("~1", "/").replace("~0", "~"))
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn fragment_set(pairs: &[(&str, Json)]) -> Fragments {
        let mut pointers = BTreeMap::new();
        for (pointer, value) in pairs {
            pointers.insert((*pointer).to_owned(), value.clone());
        }
        Fragments::from_map(pointers)
    }

    fn manifest(entries: &[(&str, &str)]) -> OwnershipManifest {
        OwnershipManifest::from_map(
            ("lekalo-core/openapi".to_owned(), "0.4.0".to_owned()),
            BTreeMap::new(),
            entries
                .iter()
                .map(|(pointer, owner)| ((*pointer).to_owned(), (*owner).to_owned()))
                .collect(),
        )
    }

    const FOCUS: &str = "/paths/~1tasks~1{task_id}~1focus/post";
    const LIST: &str = "/paths/~1tasks/get";

    fn focus_fragment(operation_id: &str) -> Json {
        json!({
            "operationId": operation_id,
            "x-lekalo-endpoint": "planner.endpoint_focus_task",
            "responses": {}
        })
    }

    #[test]
    fn an_absent_pointer_inserts_in_canonical_position() {
        let existing = json!({ "paths": {}, "components": {} });
        let fragments = fragment_set(&[(LIST, focus_fragment("plannerListTasks"))]);
        let outcome = merge(&existing, &fragments, &manifest(&[]), &manifest(&[])).expect("merges");
        assert_eq!(outcome.inserted(), [LIST]);
        assert_eq!(
            outcome.tree()["paths"]["/tasks"]["get"]["operationId"],
            "plannerListTasks"
        );
    }

    #[test]
    fn a_generator_owned_pointer_replaces_its_own_bytes() {
        let existing = json!({
            "paths": { "/tasks/{task_id}/focus": { "post": {
                "operationId": "plannerEndpointFocusTask",
                "x-lekalo-endpoint": "planner.endpoint_focus_task",
                "responses": { "200": { "description": "stale" } }
            } } }
        });
        let fragments = fragment_set(&[(FOCUS, focus_fragment("plannerEndpointFocusTask"))]);
        let ownership = manifest(&[(FOCUS, "planner.endpoint_focus_task")]);
        let outcome = merge(&existing, &fragments, &ownership, &ownership).expect("merges");
        assert_eq!(outcome.replaced(), [FOCUS]);
        assert!(outcome.is_clean());
    }

    #[test]
    fn a_manual_pointer_never_overwrites_and_conflicts() {
        let existing = json!({
            "paths": { "/tasks/{task_id}/focus": { "post": {
                "operationId": "focusTask",
                "description": "hand-written"
            } } }
        });
        let fragments = fragment_set(&[(FOCUS, focus_fragment("plannerEndpointFocusTask"))]);
        let generated = manifest(&[(FOCUS, "planner.endpoint_focus_task")]);
        let outcome = merge(&existing, &fragments, &generated, &manifest(&[]))
            .expect("merge performs; the verdict rides the outcome");
        assert_eq!(
            outcome.conflicts(),
            [(FOCUS.to_owned(), "planner.endpoint_focus_task".to_owned())]
        );
        // Untouched: the manual description survives.
        assert_eq!(
            outcome.tree()["paths"]["/tasks/{task_id}/focus"]["post"]["description"],
            "hand-written"
        );
        assert!(outcome.clone().into_result().is_err());
    }

    #[test]
    fn a_bound_identical_manual_operation_is_clean() {
        let fragment = focus_fragment("plannerEndpointFocusTask");
        let existing = json!({
            "paths": { "/tasks/{task_id}/focus": { "post": fragment.clone() } }
        });
        let fragments = fragment_set(&[(FOCUS, fragment)]);
        let outcome = merge(
            &existing,
            &fragments,
            &manifest(&[(FOCUS, "planner.endpoint_focus_task")]),
            &manifest(&[]),
        )
        .expect("merges");
        assert!(outcome.is_clean());
        assert_eq!(
            outcome.manual(),
            [(FOCUS.to_owned(), "bound-identical".to_owned())]
        );
    }

    #[test]
    fn a_bound_differing_manual_operation_reports_drift() {
        let existing = json!({
            "paths": { "/tasks/{task_id}/focus": { "post": {
                "operationId": "plannerEndpointFocusTask",
                "x-lekalo-endpoint": "planner.endpoint_focus_task",
                "summary": "stale human text"
            } } }
        });
        let fragments = fragment_set(&[(FOCUS, focus_fragment("plannerEndpointFocusTask"))]);
        let outcome = merge(
            &existing,
            &fragments,
            &manifest(&[(FOCUS, "planner.endpoint_focus_task")]),
            &manifest(&[]),
        )
        .expect("merge performs");
        assert_eq!(
            outcome.drifts(),
            [(FOCUS.to_owned(), "planner.endpoint_focus_task".to_owned())]
        );
        // Untouched: drift is a report, never an overwrite.
        assert_eq!(
            outcome.tree()["paths"]["/tasks/{task_id}/focus"]["post"]["summary"],
            "stale human text"
        );
    }

    #[test]
    fn an_orphan_generator_owned_pointer_is_removed() {
        let existing = json!({
            "paths": {
                "/tasks": { "get": { "operationId": "plannerListTasks" } },
                "/gone": { "get": { "operationId": "plannerGone" } }
            }
        });
        let fragments = fragment_set(&[(LIST, focus_fragment("plannerListTasks"))]);
        let ownership = manifest(&[("/paths/~1gone/get", "planner.endpoint_gone")]);
        let outcome = merge(&existing, &fragments, &manifest(&[]), &ownership).expect("merges");
        assert_eq!(outcome.removed(), ["/paths/~1gone/get"]);
        assert!(outcome.tree()["paths"].get("/gone").is_none());
        assert!(outcome.tree()["paths"].get("/tasks").is_some());
    }

    #[test]
    fn an_unbound_manual_operation_is_preserved_informationally() {
        let existing = json!({
            "paths": {
                "/health": { "get": { "operationId": "healthProbe" } }
            }
        });
        let fragments = fragment_set(&[(LIST, focus_fragment("plannerListTasks"))]);
        let outcome = merge(&existing, &fragments, &manifest(&[]), &manifest(&[])).expect("merges");
        assert!(outcome.is_clean());
        assert_eq!(outcome.manual().len(), 1);
        assert_eq!(outcome.manual()[0].0, "/paths/~1health/get");
        assert_eq!(
            outcome.tree()["paths"]["/health"]["get"]["operationId"],
            "healthProbe"
        );
    }

    #[test]
    fn pointer_tokens_unescape_rfc6901() {
        assert_eq!(
            pointer_tokens("/paths/~1tasks~1{id}/get"),
            vec![
                "paths".to_owned(),
                "/tasks/{id}".to_owned(),
                "get".to_owned()
            ]
        );
        assert_eq!(pointer_tokens("/a~0b"), vec!["a~b".to_owned()]);
    }

    #[test]
    fn the_merged_tree_serializes_deterministically() {
        let existing = json!({ "paths": {} });
        let fragments = fragment_set(&[
            (LIST, focus_fragment("plannerListTasks")),
            (FOCUS, focus_fragment("plannerEndpointFocusTask")),
        ]);
        let one = merge(&existing, &fragments, &manifest(&[]), &manifest(&[]))
            .expect("merges")
            .canonical_bytes();
        let two = merge(&existing, &fragments, &manifest(&[]), &manifest(&[]))
            .expect("merges")
            .canonical_bytes();
        assert_eq!(one, two);
    }
}
