#!/usr/bin/env php
<?php
/**
 * Deterministic generator of the committed single-file artifact
 * `adapter.php` (issues #54, #55).
 *
 * The kernel is dependency-free by design, so the build is a fixed-order
 * concatenation: a generated banner, then the bundled module sources in
 * the canonical order (analyzer seam, strict profile, kernel), then the
 * one-shot main. There are no timestamps, absolute paths, environment
 * lookups, or filesystem traversal anywhere in the pipeline, so repeated
 * builds are byte-identical.
 *
 * Issue #55: the adapter-owned Mago toolchain lock
 * (`mago-toolchain.lock.json`) is copied verbatim beside the kernel into
 * the artifact directory layout as a build input — its bytes are part of
 * the bundle, so a changed supported toolchain changes the artifact
 * digest (upgrade custody without touching generated bytes by hand).
 *
 * `build.php --check` rebuilds in memory and compares the bytes to the
 * committed artifact without ever rewriting it.
 */

declare(strict_types=1);

const ADAPTER_ID = 'lekalo-target-php-laravel';
const ADAPTER_VERSION = '0.2.0';

/** The bundled module order: dependencies first, kernel last. */
const BUNDLED_MODULES = [
    'src/analyzer.php',
    'src/strict-profile.php',
    'src/kernel.php',
];

function fail(string $message): never
{
    fwrite(STDERR, $message . "\n");
    exit(1);
}

$adapterRoot = dirname(__FILE__);
$artifactPath = $adapterRoot . '/adapter.php';
$lockPath = $adapterRoot . '/mago-toolchain.lock.json';

$lockBytes = file_get_contents($lockPath);
if ($lockBytes === false || $lockBytes === '') {
    fail('build: mago-toolchain.lock.json is missing or empty');
}

$banner = <<<BANNER
<?php
/**
 * The committed single-file adapter artifact of `{ADAPTER_ID}`
 * (issues #54, #55).
 *
 * GENERATED FILE — regenerate with `php adapters/php-laravel/build.php`;
 * verify with `php adapters/php-laravel/build.php --check`. Never edit.
 *
 * Self-contained: PHP built-ins only (json, hash, SPL), no Composer
 * package, no extension beyond always-compiled basics, so the confined
 * core runtime can copy the interpreter plus exactly this script.
 */

BANNER;
$banner = str_replace('{ADAPTER_ID}', ADAPTER_ID, $banner);

// Each module opens with its own `<?php` declare block; the artifact
// embeds the banner's opening tag once, then every module body minus
// its duplicated opening tag line, in the fixed BUNDLED_MODULES order.
$body = '';
foreach (BUNDLED_MODULES as $module) {
    $source = file_get_contents($adapterRoot . '/' . $module);
    if ($source === false || $source === '') {
        fail("build: bundled module {$module} is missing or empty");
    }
    if (str_starts_with($source, "<?php\n")) {
        $source = substr($source, 6);
    } else {
        fail("build: module {$module} must start with the open tag");
    }
    $body .= $source;
}

$artifact = $banner . $body
    . "\nexit(main());\n";
$digest = 'sha256:' . hash('sha256', $artifact);

$check = in_array('--check', array_slice($_SERVER['argv'] ?? [], 1), true);
if ($check) {
    if (!is_file($artifactPath)) {
        fail('--check: committed artifact is missing');
    }
    $committed = file_get_contents($artifactPath);
    if ($committed !== $artifact) {
        fwrite(STDERR, "--check: committed adapter.php differs from the deterministic rebuild\nrebuild digest: {$digest}\n");
        exit(1);
    }
    fwrite(STDOUT, json_encode([
        'ok' => true,
        'check' => true,
        'digest' => $digest,
        'bytes' => strlen($artifact),
    ], JSON_UNESCAPED_SLASHES) . "\n");
    exit(0);
}

file_put_contents($artifactPath, $artifact);
fwrite(STDOUT, json_encode([
    'ok' => true,
    'written' => 'adapter.php',
    'digest' => $digest,
    'bytes' => strlen($artifact),
    'php' => PHP_VERSION,
], JSON_UNESCAPED_SLASHES) . "\n");
