#!/usr/bin/env php
<?php
/**
 * Deterministic generator of the committed single-file artifact
 * `adapter.php` (issues #54, #55).
 *
 * The kernel is dependency-free by design, so the build is a fixed-order
 * concatenation: a generated banner, then the bundled module sources in
 * the canonical order (analyzer seam, strict profile, kernel), then the
 * one-shot main. There are no timestamps, absolute paths, environment
 * lookups, or filesystem traversal anywhere in the pipeline, so repeated
 * builds are byte-identical.
 *
 * Issue #55: the adapter-owned Mago toolchain lock
 * (`mago-toolchain.lock.json`) is embedded VERBATIM inside the artifact
 * as the `MAGO_TOOLCHAIN_LOCK_BUNDLED` PHP string, parsed from the exact
 * lock bytes and integrity-checked (the parsed lock must carry the exact
 * embedded digest). The lock bytes are therefore part of the artifact:
 * a changed supported toolchain changes the artifact digest (upgrade
 * custody without touching generated bytes by hand), and the deployed
 * single-file package carries its own lock — no sibling file is needed
 * at runtime.
 *
 * `build.php --check` rebuilds in memory and compares the bytes to the
 * committed artifact without ever rewriting it.
 */

declare(strict_types=1);

const ADAPTER_ID = 'lekalo-target-php-laravel';
const ADAPTER_VERSION = '0.2.0';

/** The bundled module order: dependencies first, kernel last. */
const BUNDLED_MODULES = [
    'src/analyzer.php',
    'src/strict-profile.php',
    'src/kernel.php',
];

function fail(string $message): never
{
    fwrite(STDERR, $message . "\n");
    exit(1);
}

$adapterRoot = dirname(__FILE__);
$artifactPath = $adapterRoot . '/adapter.php';
$lockPath = $adapterRoot . '/mago-toolchain.lock.json';
$policyPath = $adapterRoot . '/composer-gates-policy.json';
$scenarioModulePaths = [
    $adapterRoot . '/src/scenario-map.php',
    $adapterRoot . '/src/scenario-emit.php',
    // The type-generator modules ride last, in the fixed order the
    // kernel's `load_type_modules()` names (issue #58).
    $adapterRoot . '/src/type-policy.php',
    $adapterRoot . '/src/type-map.php',
    $adapterRoot . '/src/type-codec.php',
    $adapterRoot . '/src/type-emit.php',
    $adapterRoot . '/src/type-bindings.php',
];
$nativeModulePaths = [$adapterRoot . '/src/native-policy.php', $adapterRoot . '/src/native-plan.php'];

$lockBytes = file_get_contents($lockPath);
if ($lockBytes === false || $lockBytes === '') {
    fail('build: mago-toolchain.lock.json is missing or empty');
}
// The lock must be valid JSON before it can be embedded: the bundle
// never ships unparseable custody bytes.
try {
    json_decode($lockBytes, true, 32, JSON_THROW_ON_ERROR);
} catch (JsonException) {
    fail('build: mago-toolchain.lock.json is not valid JSON');
}

/** The verbatim lock bytes, embedded as a PHP single-quoted string. */
function php_single_quoted(string $bytes): string
{
    return "'" . str_replace(["\\", "'"], ["\\\\", "\\'"], $bytes) . "'";
}

$lockEmbed = "\n// ---- bundled toolchain lock (issue #55) -------------------------\n"
    . "// EMBEDDED BY build.php from mago-toolchain.lock.json. Never edit.\n"
    . "// The exact bytes are part of this artifact, so the artifact digest\n"
    . "// changes whenever the supported toolchain changes (custody binds).\n"
    . "const MAGO_TOOLCHAIN_LOCK_BUNDLED = " . php_single_quoted($lockBytes) . ";\n";

// Issue #61: the checked-in Composer execution policy rides the same
// verbatim-embed custody — the planner verifies confirmations against
// these exact bytes and the artifact digest changes with the policy.
$policyBytes = file_get_contents($policyPath);
if ($policyBytes === false || $policyBytes === '') {
    fail('build: composer-gates-policy.json is missing or empty');
}
try {
    json_decode($policyBytes, true, 64, JSON_THROW_ON_ERROR);
} catch (JsonException) {
    fail('build: composer-gates-policy.json is not valid JSON');
}
$policyEmbed = "\n// ---- bundled Composer gates policy (issue #61) ------------------\n"
    . "// EMBEDDED BY build.php from composer-gates-policy.json. Never edit.\n"
    . "// Confirmation data only — never execution authority. The exact\n"
    . "// bytes are part of this artifact (upgrade custody binds).\n"
    . "const NATIVE_GATES_POLICY_BUNDLED = " . php_single_quoted($policyBytes) . ";\n";

$nativeModules = '';
foreach ($nativeModulePaths as $modulePath) {
    $module = file_get_contents($modulePath);
    if ($module === false || $module === '') {
        fail('build: native module source is missing or empty: ' . basename($modulePath));
    }
    if (!str_starts_with($module, "<?php\n")) {
        fail('build: native module must start with the open tag: ' . basename($modulePath));
    }
    $module = substr($module, 6);
    // The artifact declares strict_types once in the banner; the
    // module-local declare (kept for standalone source loading) is
    // stripped deterministically so the concatenated file stays legal.
    $module = (string) preg_replace('/^declare\(strict_types=1\);\n/m', '', $module, 1);
    $nativeModules .= "\n// ----- native gate module: " . basename($modulePath) . " -----\n\n"
        . $module;
}

$scenarioModules = '';
foreach ($scenarioModulePaths as $modulePath) {
    $module = file_get_contents($modulePath);
    if ($module === false || $module === '') {
        fail('build: scenario module source is missing or empty: ' . basename($modulePath));
    }
    if (!str_starts_with($module, "<?php\n")) {
        fail('build: scenario module must start with the open tag: ' . basename($modulePath));
    }
    $scenarioModules .= "\n// ----- bundled compiler module: " . basename($modulePath) . " -----\n\n"
        . substr($module, 6);
}


$banner = <<<BANNER
<?php
/**
 * The committed single-file adapter artifact of `{ADAPTER_ID}`
 * (issues #54, #55).
 *
 * GENERATED FILE — regenerate with `php adapters/php-laravel/build.php`;
 * verify with `php adapters/php-laravel/build.php --check`. Never edit.
 *
 * Self-contained: PHP built-ins only (json, hash, SPL), no Composer
 * package, no extension beyond always-compiled basics, so the confined
 * core runtime can copy the interpreter plus exactly this script.
 */

declare(strict_types=1);

BANNER;
$banner = str_replace('{ADAPTER_ID}', ADAPTER_ID, $banner);

// Each module opens with its own `<?php` declare block; the artifact
// embeds the banner's opening tag once, then every module body minus
// its duplicated opening tag line, in the fixed BUNDLED_MODULES order.
$body = '';
foreach (BUNDLED_MODULES as $module) {
    $source = file_get_contents($adapterRoot . '/' . $module);
    if ($source === false || $source === '') {
        fail("build: bundled module {$module} is missing or empty");
    }
    if (str_starts_with($source, "<?php\n")) {
        $source = substr($source, 6);
    } else {
        fail("build: module {$module} must start with the open tag");
    }
    // The bundled lock rides immediately before the analyzer module:
    // the analyzer (or any consumer) reads it through the
    // MAGO_TOOLCHAIN_LOCK_BUNDLED constant, never from the filesystem.
    if ($module === 'src/analyzer.php') {
        $body .= $lockEmbed;
    }
    $body .= $source;
}
// The scenario compiler modules ride last, in the same fixed order
// `load_scenario_modules()` names (issue #56); inside the artifact the
// kernel's function_exists guards make the require_once path inert.
$body .= $scenarioModules;
// The bundled Composer execution policy rides with the native gate
// modules (issue #61): one artifact carries its own confirmation
// custody, no sibling file at runtime.
$body .= $policyEmbed;
// The native gate modules ride after the scenario modules in the
// fixed order `load_native_modules()` names (issue #61).
$body .= $nativeModules;

$artifact = $banner . $body
    . "\nexit(main());\n";
$digest = 'sha256:' . hash('sha256', $artifact);

$check = in_array('--check', array_slice($_SERVER['argv'] ?? [], 1), true);
if ($check) {
    if (!is_file($artifactPath)) {
        fail('--check: committed artifact is missing');
    }
    $committed = file_get_contents($artifactPath);
    if ($committed !== $artifact) {
        fwrite(STDERR, "--check: committed adapter.php differs from the deterministic rebuild\nrebuild digest: {$digest}\n");
        exit(1);
    }
    fwrite(STDOUT, json_encode([
        'ok' => true,
        'check' => true,
        'digest' => $digest,
        'bytes' => strlen($artifact),
    ], JSON_UNESCAPED_SLASHES) . "\n");
    exit(0);
}

file_put_contents($artifactPath, $artifact);
fwrite(STDOUT, json_encode([
    'ok' => true,
    'written' => 'adapter.php',
    'digest' => $digest,
    'bytes' => strlen($artifact),
    'php' => PHP_VERSION,
], JSON_UNESCAPED_SLASHES) . "\n");
