<?php
/**
 * Source-mode entry of `lekalo-target-php-laravel`: the exact production
 * process surface. The committed artifact `adapter.php` is generated by
 * `build.php` from the kernel plus its bundled modules in fixed order
 * (the kernel has no runtime dependencies, so the bundle is one file),
 * which keeps shipped bytes and source bytes in a checkable 1:1
 * relation.
 */

declare(strict_types=1);

require __DIR__ . '/src/analyzer.php';
require __DIR__ . '/src/strict-profile.php';
require __DIR__ . '/src/kernel.php';
require __DIR__ . '/src/native-policy.php';
require __DIR__ . '/src/native-plan.php';

exit(main());
