<?php
/**
 * Source-mode entry of `lekalo-target-php-laravel`: the exact production
 * process surface. The committed artifact `adapter.php` is generated by
 * `build.php` from the kernel source alone (the kernel has no runtime
 * dependencies, so the bundle is one file plus a header), which keeps
 * shipped bytes and source bytes in a checkable 1:1 relation.
 */

declare(strict_types=1);

require __DIR__ . '/src/kernel.php';

exit(main());
