#!/usr/bin/env node
/**
 * The hermetic fake target adapter (issue #27).
 *
 * A dependency-free Node.js adapter implementing the full
 * `lekalo.target/v1` handshake: describe negotiation, every v1 operation,
 * deterministic plans, and honest write plans. It exists to prove the
 * protocol is language-neutral and to exercise the core client: an adapter
 * needs nothing but stdin/stdout, JSON, and SHA-256.
 *
 * Fault injection for the contract tests, via LEKALO_FAKE_ADAPTER:
 *   wrong-token   respond with a foreign protocol token
 *   wrong-version respond with an unsupported exact version
 *   garbage       emit non-JSON on stdout
 *   crash         exit non-zero without a response envelope
 *   hang          never respond (deadline enforcement)
 *   noise         write unbounded chatter to stderr
 *   bad-echo      echo a foreign request id
 *   boom          report an in-envelope operation error for any operation
 *   mutate-dry    write during a dry-run generate (must be refused)
 *   extra-write   write an undeclared file during an apply (must be caught)
 *
 * The adapter is deterministic: the same request inputs always produce the
 * same plan and the same bytes, which is what makes the core's
 * dry-run-plan/apply cross-check workable without persisted state.
 */

import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync } from "node:fs";
import { dirname } from "node:path";

const fault = (name) => FAULT.split(",").includes(name);

const faultArg = process.argv.indexOf("--lekalo-fault");
const FAULT =
  faultArg !== -1 && process.argv[faultArg + 1]
    ? process.argv[faultArg + 1]
    : (process.env.LEKALO_FAKE_ADAPTER ?? "");

const ADAPTER = {
  id: "node-typescript",
  version: "0.1.0",
  digest: sha256("lekalo fake target adapter v1"),
};

function sha256(text) {
  return "sha256:" + createHash("sha256").update(text).digest("hex");
}

/** Canonical compact JSON: byte-sorted keys, exactly like the core. */
function canonical(value) {
  if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`;
  if (value && typeof value === "object") {
    const body = Object.keys(value)
      .sort()
      .map((key) => `${JSON.stringify(key)}:${canonical(value[key])}`)
      .join(",");
    return `{${body}}`;
  }
  return JSON.stringify(value);
}

function readRequest() {
  const marker = process.argv.indexOf("--lekalo-request-file");
  if (marker !== -1 && process.argv[marker + 1]) {
    return readFileSync(process.argv[marker + 1], "utf8");
  }
  return readFileSync(0, "utf8");
}

function deterministicWrites(request) {
  const target = request.target ?? "node-typescript";
  const profile = request.profile ?? "default";
  const irPath = request.ir_path ?? ".lekalo/ir/planner.json";
  const body = `// generated by ${ADAPTER.id}@${ADAPTER.version}\n// target: ${target}\n// profile: ${profile}\n// ir: ${irPath}\n`;
  const path = `.lekalo/generated/${ADAPTER.id}/model.ts`;
  const writes = [{ path, action: "create", sha256: sha256(body) }];
  return { body, writes };
}

function planId(writes) {
  return "plan-" + sha256(canonical(writes)).slice("sha256:".length);
}

function capabilities() {
  return {
    adapter: ADAPTER,
    protocol_versions: ["1.0.0"],
    operations: [
      "describe",
      "scan",
      "bind",
      "validate",
      "generate",
      "verify",
      "clean",
      "plan-clean",
    ],
    targets: ["node-typescript"],
    profiles: ["default"],
    read_scopes: [".lekalo/ir/**"],
    write_scopes: [".lekalo/generated/node-typescript/**"],
    transports: ["stdin", "file"],
    progress: true,
  };
}

function respond(request, payload) {
  const envelope = {
    protocol: fault("wrong-token") ? "lekalo.target/v0" : "lekalo.target/v1",
    protocol_version: fault("wrong-version") ? "0.9.0" : request.protocol_version,
    operation: request.operation,
    request_id: fault("bad-echo") ? "req-" + "0".repeat(64) : request.request_id,
    status: "ok",
    evidence: { adapter: ADAPTER },
    ...payload,
  };
  process.stdout.write(canonical(envelope));
}

function fail(request, errorClass, code, message) {
  const envelope = {
    protocol: "lekalo.target/v1",
    protocol_version: request.protocol_version,
    operation: request.operation,
    request_id: request.request_id,
    status: "error",
    evidence: { adapter: ADAPTER },
    error: { class: errorClass, code, message, partial: false },
  };
  process.stdout.write(canonical(envelope));
}

const request = JSON.parse(readRequest());

if (fault("crash")) process.exit(3);
if (fault("garbage")) {
  process.stdout.write("<this is not json>");
  process.exit(0);
}
if (fault("hang")) {
  setTimeout(() => process.exit(0), 60_000);
} else if (fault("noise")) {
  const chatter = "x".repeat(1024);
  const interval = setInterval(() => process.stderr.write(chatter), 1);
  setTimeout(() => {
    clearInterval(interval);
    respond(request, {});
    process.exit(0);
  }, 100);
} else if (fault("boom")) {
  fail(request, "invalid", "fake-invalid", "injected operation failure");
} else {
  switch (request.operation) {
    case "describe":
      respond(request, { capabilities: capabilities() });
      break;
    case "scan":
      respond(request, {
        result: {
          entries: [
            { path: "src/main.ts", kind: "source" },
            { path: "src/util.ts", kind: "source" },
          ],
          truncated: false,
        },
      });
      break;
    case "bind":
      respond(request, {
        result: {
          bindings: [
            { module: "planner", target: request.target, profile: request.profile },
          ],
        },
      });
      break;
    case "validate":
      respond(request, { result: { ok: true, findings: [] } });
      break;
    case "verify":
      respond(request, { result: { ok: true, findings: [] } });
      break;
    case "generate": {
      const { writes } = deterministicWrites(request);
      const target = `.lekalo/generated/${ADAPTER.id}/model.ts`;
      if (request.dry_run === false || fault("mutate-dry")) {
        mkdirSync(dirname(target), { recursive: true });
        writeFileSync(target, deterministicWrites(request).body);
      }
      if (fault("extra-write") && request.dry_run === false) {
        writeFileSync(dirname(target) + "/extra.txt", "undeclared");
      }
      respond(request, {
        writes,
        evidence: { adapter: ADAPTER, plan_id: planId(writes) },
        progress: [
          { step: "compile", state: "done" },
          { step: "emit", state: "done" },
        ],
      });
      break;
    }
    case "plan-clean": {
      const { writes } = deterministicWrites(request);
      const plan = writes.map(({ path }) => ({ path, action: "delete" }));
      respond(request, {
        writes: plan,
        evidence: { adapter: ADAPTER, plan_id: planId(plan) },
      });
      break;
    }
    case "clean": {
      const { writes } = deterministicWrites(request);
      const plan = writes.map(({ path }) => ({ path, action: "delete" }));
      for (const entry of plan) {
        if (existsSync(entry.path)) rmSync(entry.path);
      }
      respond(request, {
        writes: plan,
        evidence: { adapter: ADAPTER, plan_id: planId(plan) },
      });
      break;
    }
    default:
      fail(request, "invalid", "fake-operation", `unknown operation ${request.operation}`);
  }
}
