//! CLI integration tests for `lekalo generate` (issue #21): the read-only
//! drift gate, the preview/confirm clean flow, and the accepted exit
//! envelope. Every test runs the real binary over a sandbox project;
//! temp roots stay under `target/` addressed with relative selectors —
//! the Windows 8.3-alias lesson — and binary invocations go through
//! `alias_free_path`.

use serde_json::{json, Value};
use std::path::{Path, PathBuf};
use std::process::{Command, Output};
use std::sync::atomic::{AtomicU32, Ordering};

use lekalo_core::artifacts::GenerateService;
use lekalo_core::loader::LoadSelection;
use lekalo_core::versioning::plan::sha256_hex;

const REFERENCE_PROJECT: &str = "../../tests/fixtures/artifacts/project";
const ARTIFACT_DIR: &str = "apps/api/src/planner";
const ARTIFACT_NAME: &str = "focus-task.ts";
const ARTIFACT_CONTENT: &str = "export function focusTask() {\n  return planner.createTask();\n}\n";
const ORPHAN_CONTENT: &str = "orphaned generated bytes\n";

// GitHub Windows runners export %TEMP% as C:\Users\RUNNER~1\...; the
// selection policy denies alias spellings, so the real binary is always
// invoked from an alias-free working directory.
fn alias_free_path(path: &Path) -> PathBuf {
    let canonical = path.canonicalize().expect("canonicalize path");
    #[cfg(windows)]
    {
        let text = canonical.to_string_lossy().to_string();
        if let Some(stripped) = text.strip_prefix(r"\\?\") {
            if stripped.as_bytes().get(1) == Some(&b':') {
                return PathBuf::from(stripped);
            }
        }
    }
    canonical
}

fn stdout_text(output: &Output) -> String {
    String::from_utf8(output.stdout.clone()).expect("utf8 stdout")
}

fn stderr_text(output: &Output) -> String {
    String::from_utf8(output.stderr.clone()).expect("utf8 stderr")
}

fn exit_code(output: &Output) -> i32 {
    output.status.code().expect("exit code")
}

fn lekalo_in(dir: &Path, args: &[&str]) -> Output {
    Command::new(env!("CARGO_BIN_EXE_lekalo"))
        .args(args)
        .current_dir(alias_free_path(dir))
        .env_remove("LEKALO_PROJECT")
        .output()
        .expect("run the real lekalo binary")
}

static NEXT_SANDBOX: AtomicU32 = AtomicU32::new(0);

fn copy_dir(from: &Path, to: &Path) {
    std::fs::create_dir_all(to).expect("create sandbox dir");
    for entry in std::fs::read_dir(from).expect("read reference") {
        let entry = entry.expect("reference entry");
        let target = to.join(entry.file_name());
        if entry.file_type().expect("entry type").is_dir() {
            copy_dir(&entry.path(), &target);
        } else {
            std::fs::copy(entry.path(), &target).expect("copy reference file");
        }
    }
}

struct Sandbox {
    root: PathBuf,
    selector: String,
}

impl Drop for Sandbox {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.root);
    }
}

fn with_sandbox(name: &str, body: impl FnOnce(&Sandbox)) {
    let id = NEXT_SANDBOX.fetch_add(1, Ordering::SeqCst);
    let relative = format!("target/generate-tests/{name}-{}-{id}", std::process::id());
    // The test process cwd is the crate dir, and the core selection APIs
    // resolve relative selectors from it: keep the sandbox under the
    // (git-ignored) crate-local target tree so both agree.
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(&relative);
    let _ = std::fs::remove_dir_all(&root);
    copy_dir(Path::new(REFERENCE_PROJECT), &root);
    let sandbox = Sandbox {
        selector: relative.replace('\\', "/"),
        root,
    };
    body(&sandbox);
    // Drop removes the tree even when the test panics, so a failed run
    // can never leak a sandbox project into other suites' scans.
    drop(sandbox);
}

impl Sandbox {
    fn selection(&self) -> LoadSelection {
        LoadSelection {
            project: Some(self.selector.clone()),
        }
    }

    fn create_lock(&self) {
        let output = lekalo_in(&self.root, &["lock"]);
        assert_eq!(exit_code(&output), 0, "{}", stderr_text(&output));
    }

    fn write_artifact(&self, name: &str, content: &str) {
        let dir = self.root.join(ARTIFACT_DIR);
        std::fs::create_dir_all(&dir).expect("artifact dir");
        std::fs::write(dir.join(name), content).expect("artifact bytes");
    }

    fn write_orphan(&self) -> String {
        let path = self.root.join(".lekalo/generated/scratch.txt");
        std::fs::create_dir_all(path.parent().expect("generated parent")).expect("dir");
        std::fs::write(&path, ORPHAN_CONTENT).expect("orphan bytes");
        ".lekalo/generated/scratch.txt".to_owned()
    }

    fn author_manifest(&self, artifacts: Vec<Value>) {
        let inputs = GenerateService::inputs(&self.selection()).expect("inputs receipt");
        let mut document = json!({
            "schema_version": "lekalo/artifact-manifest/v1.0.0",
            "identity": "dev.lekalo.artifact-manifest@1.0.0",
            "project_ref": "planner",
            "lock_ref": {
                "schema_version": "lekalo/lock/v1.0.0",
                "digest": inputs.lock_digest,
            },
            "inputs": {
                "model": {"version": inputs.model_version, "digest": inputs.model_digest},
                "ir": {"version": inputs.ir_version, "digest": inputs.ir_digest},
            },
            "artifacts": artifacts,
            "source_maps": [],
        });
        let mut draft = document.clone();
        draft
            .as_object_mut()
            .expect("object")
            .remove("manifest_digest");
        document["manifest_digest"] = json!(format!(
            "sha256:{}",
            sha256_hex(&serde_json::to_vec(&draft).expect("wire"))
        ));
        let path = self.root.join(".lekalo/generated/manifests/ownership.json");
        std::fs::create_dir_all(path.parent().expect("manifest parent")).expect("manifest dir");
        std::fs::write(
            &path,
            serde_json::to_vec(&document).expect("canonical wire"),
        )
        .expect("manifest bytes");
    }

    /// A full directory snapshot: sorted (relative path, size, sha256)
    /// lines. Read-only commands must never change it.
    fn snapshot(&self) -> String {
        let mut lines = Vec::new();
        fn walk(dir: &Path, base: &Path, lines: &mut Vec<String>) {
            for entry in std::fs::read_dir(dir).expect("read dir") {
                let entry = entry.expect("entry");
                let path = entry.path();
                let relative = path
                    .strip_prefix(base)
                    .expect("relative")
                    .to_string_lossy()
                    .replace('\\', "/");
                if path.is_dir() {
                    walk(&path, base, lines);
                } else {
                    let bytes = std::fs::read(&path).expect("read");
                    lines.push(format!(
                        "{} {} {}",
                        relative,
                        bytes.len(),
                        sha256_hex(&bytes)
                    ));
                }
            }
        }
        walk(&self.root, &self.root, &mut lines);
        lines.sort();
        lines.join("\n")
    }
}

fn artifact_value(owner: &str, path: &str, content: &str) -> Value {
    json!({
        "semantic_owner": owner,
        "path": path,
        "artifact_kind": "source",
        "lifecycle": "generated",
        "content": {
            "algorithm": "sha256",
            "digest": format!("sha256:{}", sha256_hex(content.as_bytes())),
            "canonicalization": "exact-file-bytes",
        },
        "input_refs": [owner],
        "regeneration_policy": "on-input-change",
    })
}

// ---------------------------------------------------------------------------
// The read-only drift gate.
// ---------------------------------------------------------------------------

#[test]
fn check_on_a_bound_manifest_is_clean_in_both_projections_and_deterministic() {
    with_sandbox("clean", |sandbox| {
        sandbox.create_lock();
        sandbox.write_artifact(ARTIFACT_NAME, ARTIFACT_CONTENT);
        sandbox.author_manifest(vec![artifact_value(
            "planner.create_task",
            "apps/api/src/planner/focus-task.ts",
            ARTIFACT_CONTENT,
        )]);
        let first = lekalo_in(&sandbox.root, &["generate", "--check"]);
        assert_eq!(exit_code(&first), 0, "{}", stderr_text(&first));
        let second = lekalo_in(&sandbox.root, &["generate", "--check"]);
        assert_eq!(stdout_text(&first), stdout_text(&second));
        // The human projection is one stable line.
        assert!(stdout_text(&first).starts_with("generate check clean manifest sha256:"));
        // The JSON projection carries the same verdict and counts.
        let json = lekalo_in(&sandbox.root, &["--json", "generate", "--check"]);
        assert_eq!(exit_code(&json), 0);
        let document: Value = serde_json::from_str(stdout_text(&json).trim()).expect("envelope");
        assert_eq!(document["status"], "valid");
        assert_eq!(document["mode"], "check");
        assert_eq!(document["verdict"], "clean");
        assert_eq!(document["counts"]["artifacts"], 1);
        assert_eq!(document["counts"]["clean"], 1);
    });
}

#[test]
fn check_writes_nothing_to_the_project_tree() {
    with_sandbox("readonly", |sandbox| {
        sandbox.create_lock();
        sandbox.write_artifact(ARTIFACT_NAME, ARTIFACT_CONTENT);
        sandbox.author_manifest(vec![artifact_value(
            "planner.create_task",
            "apps/api/src/planner/focus-task.ts",
            ARTIFACT_CONTENT,
        )]);
        let before = sandbox.snapshot();
        let output = lekalo_in(&sandbox.root, &["generate", "--check"]);
        assert_eq!(exit_code(&output), 0, "{}", stderr_text(&output));
        assert_eq!(sandbox.snapshot(), before, "generate --check wrote nothing");
    });
}

#[test]
fn manual_drift_blocks_with_exit_one_and_the_stable_rule_on_stderr() {
    with_sandbox("drift", |sandbox| {
        sandbox.create_lock();
        sandbox.write_artifact(ARTIFACT_NAME, ARTIFACT_CONTENT);
        sandbox.author_manifest(vec![artifact_value(
            "planner.create_task",
            "apps/api/src/planner/focus-task.ts",
            ARTIFACT_CONTENT,
        )]);
        sandbox.write_artifact(ARTIFACT_NAME, "export const drifted = true;\n");
        let human = lekalo_in(&sandbox.root, &["generate", "--check"]);
        assert_eq!(exit_code(&human), 1);
        assert!(stderr_text(&human).starts_with("invalid error [LEK-LOCK-018] lock.source-changed"));
        assert!(!stdout_text(&human).contains("LEK-LOCK-018"));
        let json = lekalo_in(&sandbox.root, &["--json", "generate", "--check"]);
        assert_eq!(exit_code(&json), 1);
        assert!(stderr_text(&json).contains("\"id\": \"lock.source-changed\""));
    });
}

#[test]
fn absent_lock_and_bare_generate_map_to_the_stable_failures() {
    with_sandbox("usage", |sandbox| {
        // A bare generate selects no mode: stable usage failure.
        let output = lekalo_in(&sandbox.root, &["generate"]);
        assert_eq!(exit_code(&output), 1);
        assert!(stderr_text(&output).contains("cli.usage"));
        // Mutually exclusive modes never fall through to clap's exit.
        let output = lekalo_in(&sandbox.root, &["generate", "--check", "--clean"]);
        assert_eq!(exit_code(&output), 1);
        assert!(stderr_text(&output).contains("cli.usage"));
        // The manifest binds the exact lock revision: no lock, no check.
        let output = lekalo_in(&sandbox.root, &["generate", "--check"]);
        assert_eq!(exit_code(&output), 1);
        assert!(stderr_text(&output).contains("lock.missing"));
    });
}

#[test]
fn an_unsupported_manifest_discriminator_maps_to_exit_five() {
    with_sandbox("future", |sandbox| {
        sandbox.create_lock();
        let path = sandbox
            .root
            .join(".lekalo/generated/manifests/ownership.json");
        std::fs::create_dir_all(path.parent().expect("parent")).expect("dir");
        std::fs::write(
            &path,
            "{\"schema_version\":\"lekalo/artifact-manifest/v9.0.0\"}\n",
        )
        .expect("future manifest");
        let output = lekalo_in(&sandbox.root, &["generate", "--check"]);
        assert_eq!(exit_code(&output), 5);
        assert!(stderr_text(&output).starts_with("unsupported-version error [LEK-LOCK-020]"));
    });
}

// ---------------------------------------------------------------------------
// The confirmed clean flow.
// ---------------------------------------------------------------------------

#[test]
fn clean_requires_a_bound_preview_and_applies_exactly_that_plan() {
    with_sandbox("cleanspan", |sandbox| {
        sandbox.create_lock();
        sandbox.write_artifact(ARTIFACT_NAME, ARTIFACT_CONTENT);
        sandbox.author_manifest(vec![artifact_value(
            "planner.create_task",
            "apps/api/src/planner/focus-task.ts",
            ARTIFACT_CONTENT,
        )]);
        let orphan = sandbox.write_orphan();

        // A mutating clean without a bound preview is refused.
        let output = lekalo_in(&sandbox.root, &["generate", "--clean"]);
        assert_eq!(exit_code(&output), 1);
        assert!(stderr_text(&output).contains("lock.preview-required"));

        // The preview deletes nothing and prints the plan identity.
        let preview = lekalo_in(
            &sandbox.root,
            &["--json", "generate", "--clean", "--dry-run"],
        );
        assert_eq!(exit_code(&preview), 0, "{}", stderr_text(&preview));
        assert!(
            sandbox.root.join(&orphan).is_file(),
            "preview wrote nothing"
        );
        let document: Value =
            serde_json::from_str(stdout_text(&preview).trim()).expect("plan wire");
        assert_eq!(document["mode"], "preview");
        assert_eq!(document["count"], 1);
        assert_eq!(document["files"][0]["path"], orphan);
        let plan_id = document["planId"].as_str().expect("plan id").to_owned();

        // A wrong confirmation deletes nothing.
        let wrong = lekalo_in(
            &sandbox.root,
            &[
                "generate",
                "--clean",
                "--confirm",
                "sha256:0000000000000000000000000000000000000000000000000000000000000000",
            ],
        );
        assert_eq!(exit_code(&wrong), 1);
        assert!(sandbox.root.join(&orphan).is_file(), "zero deletes");

        // The exact confirmation applies the plan.
        let apply = lekalo_in(
            &sandbox.root,
            &["generate", "--clean", "--confirm", &plan_id],
        );
        assert_eq!(exit_code(&apply), 0, "{}", stderr_text(&apply));
        assert!(!sandbox.root.join(&orphan).exists());
        assert!(stdout_text(&apply).starts_with("generate applied plan"));
    });
}

#[test]
fn a_changed_orphan_yields_plan_changed_with_zero_deletes() {
    with_sandbox("race", |sandbox| {
        sandbox.create_lock();
        let orphan = sandbox.write_orphan();
        let preview = lekalo_in(
            &sandbox.root,
            &["--json", "generate", "--clean", "--dry-run"],
        );
        assert_eq!(exit_code(&preview), 0);
        let document: Value =
            serde_json::from_str(stdout_text(&preview).trim()).expect("plan wire");
        let plan_id = document["planId"].as_str().expect("plan id").to_owned();
        // Swap the orphan's bytes between preview and apply.
        std::fs::write(sandbox.root.join(&orphan), b"changed").expect("alter");
        let output = lekalo_in(
            &sandbox.root,
            &["generate", "--clean", "--confirm", &plan_id],
        );
        assert_eq!(exit_code(&output), 1);
        assert!(stderr_text(&output).contains("lock.source-changed"));
        assert!(sandbox.root.join(&orphan).is_file(), "zero deletes");
    });
}

#[test]
fn the_vacuous_clean_is_an_unchanged_receipt() {
    with_sandbox("vacuum", |sandbox| {
        sandbox.create_lock();
        let preview = lekalo_in(
            &sandbox.root,
            &["--json", "generate", "--clean", "--dry-run"],
        );
        assert_eq!(exit_code(&preview), 0);
        let document: Value =
            serde_json::from_str(stdout_text(&preview).trim()).expect("plan wire");
        assert_eq!(document["count"], 0);
        let plan_id = document["planId"].as_str().expect("plan id").to_owned();
        let apply = lekalo_in(
            &sandbox.root,
            &["generate", "--clean", "--confirm", &plan_id],
        );
        assert_eq!(exit_code(&apply), 0);
        assert!(stdout_text(&apply).starts_with("generate unchanged plan"));
    });
}
