#!/usr/bin/env node
/**
 * Deterministic generator of the committed single-file artifact
 * `adapter.mjs` (issue #44, plan §1).
 *
 * The build bundles the TypeScript compiler API (exact pin from
 * package-lock.json) plus every `lib.*.d.ts` standard-library file of
 * the SAME pin as an embedded sorted string map, together with the
 * maintained kernel source (src/kernel.mjs), into one physical ESM file.
 * The artifact therefore never resolves `typescript` from the project,
 * NODE_PATH, or ambient node_modules at runtime.
 *
 * Determinism contract:
 * - fixed working directory and source order (no filesystem traversal
 *   order leaks into the output);
 * - no absolute build paths, no timestamps, no nondeterministic
 *   metadata; lib.d.ts text is embedded sorted by file name;
 * - the bundler itself is the exact esbuild pin, run in-memory and
 *   written byte-stable;
 * - `node build.mjs --check` rebuilds in memory and compares the bytes
 *   to the committed artifact without ever rewriting it.
 *
 * Legal attribution for the vendored compiler and bundler is embedded
 * in the artifact header comment and THIRD_PARTY_NOTICES.md.
 *
 * This script is a development/CI provisioning consumer only. It never
 * runs as part of a scan, a fixture execution, or the adapter itself.
 */
import { build } from "esbuild";
import { createHash } from "node:crypto";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { createRequire } from "node:module";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const adapterRoot = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(adapterRoot, "..", "..");
const artifactPath = join(adapterRoot, "adapter.mjs");
const kernelPath = join(adapterRoot, "src", "kernel.mjs");
const scannerPath = join(adapterRoot, "src", "scanner.mjs");
const workspacePath = join(adapterRoot, "src", "workspace.mjs");
const nativePlanPath = join(adapterRoot, "src", "native-plan.mjs");
const nativeContractPath = join(adapterRoot, "src", "native-contract.mjs");
const libsPath = join(adapterRoot, "src", "libs.mjs");
const scratchRoot = join(adapterRoot, ".build");

const require = createRequire(import.meta.url);
const esbuildPackageJson = require("esbuild/package.json");
const typescriptPackageJson = require("typescript/package.json");

const stripShebang = (text) => text.startsWith(String.fromCharCode(35) + String.fromCharCode(33)) ? text.slice(text.indexOf(String.fromCharCode(10)) + 1) : text;
const ESBUILD_VERSION = esbuildPackageJson.version;
const TYPESCRIPT_VERSION = typescriptPackageJson.version;
if (ESBUILD_VERSION !== "0.25.12") {
  process.stderr.write(
    `esbuild pin violation: expected 0.25.12, found ${ESBUILD_VERSION}\n`,
  );
  process.exit(1);
}
if (TYPESCRIPT_VERSION !== "5.9.3") {
  process.stderr.write(
    `typescript pin violation: expected 5.9.3, found ${TYPESCRIPT_VERSION}\n`,
  );
  process.exit(1);
}

/**
 * Locate the installed esbuild platform binary without ever launching a
 * package-manager fallback install or network fetch. A missing binary is
 * a build refusal: provisioning (`npm ci --ignore-scripts`) owns it.
 */
function esbuildBinaryPath() {
  const platformDir = `@esbuild/${process.platform}-${process.arch}`;
  const binaryName = process.platform === "win32" ? "esbuild.exe" : "esbuild";
  for (const base of [join(adapterRoot, "node_modules")]) {
    const candidate = join(base, platformDir, binaryName);
    if (existsSync(candidate)) {
      return candidate;
    }
  }
  process.stderr.write(
    `esbuild platform binary missing (${platformDir}); run ` +
      "`npm ci --prefix adapters/node-typescript --ignore-scripts --no-audit --no-fund`\n",
  );
  process.exit(1);
}

/** Every standard-library declaration file of the exact compiler pin. */
function collectLibFiles() {
  const libDir = dirname(require.resolve("typescript/package.json"));
  const dir = join(libDir, "lib");
  const names = readdirSync(dir)
    .filter((name) => /^lib(\..+)?\.d\.ts$/.test(name))
    .sort((left, right) => (left < right ? -1 : left > right ? 1 : 0));
  if (names.length === 0) {
    process.stderr.write("no lib.*.d.ts files found in the pinned typescript\n");
    process.exit(1);
  }
  return names.map((name) => ({ name, text: readFileSync(join(dir, name), "utf8") }));
}

/**
 * The generated virtual module with the embedded declarations. Text is
 * JSON-stringified (deterministic escaping) into a sorted map.
 */
function libsModuleText(libFiles) {
  const entries = libFiles.map(
    ({ name, text }) => `[${JSON.stringify(name)},${JSON.stringify(text)}]`,
  );
  return `// Generated by build.mjs — embedded TypeScript ${TYPESCRIPT_VERSION} standard libraries (sorted).\nexport const LIB_FILES = new Map([${entries.join(",")}]);\n`;
}

/** The public bundle entry of the artifact. */
const entryText = `// Generated by build.mjs — the entry wires the vendored compiler to the kernel.
import { LIB_FILES } from "./libs.mjs";
import * as ts from "typescript";
import * as kernel from "./kernel.mjs";
import * as scanner from "./scanner.mjs";
import * as workspace from "./workspace.mjs";
import * as nativePlan from "./native-plan.mjs";

kernel.__setCompilerMetadata({
  vendored: true,
  typescript: ${JSON.stringify(TYPESCRIPT_VERSION)},
  esbuild: ${JSON.stringify(ESBUILD_VERSION)},
});
kernel.__attachVendoredCompiler(ts, LIB_FILES);
kernel.__setLaunchExtensions([
  {
    id: "typescript-symbol-scanner",
    version: "0.3.1",
    operations: ["scan"],
    namedCapabilities: { "scan.symbols": "full" },
    // The scan operation consumes no IR, but the production scan
    // service's selection preflight requires the adapter to declare
    // compatibility with the core IR contract version; declaring it is
    // a negotiation fact, not an IR read.
    acceptedIrVersions: ["0.2.16"],
    invoke: (context) => scanner.scanOperation(context),
  },
]);
export const compilerHostApi = ts;
export const __lekaloKernel = kernel;
export const __lekaloScanner = scanner;
await kernel.runIfEntry(import.meta.url);
`;

const banner = `#!/usr/bin/env node
/**
 * The committed single-file adapter artifact of
 * \`lekalo-target-node-typescript\` (issues #43/#44).
 *
 * GENERATED FILE — regenerate with \`node adapters/node-typescript/build.mjs\`;
 * verify with \`node adapters/node-typescript/build.mjs --check\`. Never edit.
 *
 * This artifact embeds the TypeScript ${TYPESCRIPT_VERSION} compiler API and its
 * standard-library declarations (Apache-2.0, (c) Microsoft Corporation)
 * bundled by esbuild ${ESBUILD_VERSION} (MIT, (c) Evan Wallace); see
 * THIRD_PARTY_NOTICES.md. It resolves no package at runtime: the compiler,
 * its declarations, and the kernel live in this one physical file, so the
 * confined core runtime can copy the executable plus exactly this script.
 */

`;

/** Build once in memory; returns the exact artifact bytes (string). */
async function buildArtifact() {
  // Fresh scratch: fixed layout, fixed order, no traversal noise.
  rmSync(scratchRoot, { recursive: true, force: true });
  mkdirSync(join(scratchRoot, "src"), { recursive: true });
  const libFiles = collectLibFiles();
  writeFileSync(libsPath, libsModuleText(libFiles));
  writeFileSync(join(scratchRoot, "src", "libs.mjs"), libsModuleText(libFiles));
  const kernelSource = readFileSync(kernelPath, "utf8").replace(/^#![^\n]*\n/, "");
  writeFileSync(join(scratchRoot, "src", "kernel.mjs"), kernelSource);
  const scannerSource = readFileSync(scannerPath, "utf8").replace(stripShebang, "");
  writeFileSync(join(scratchRoot, "src", "scanner.mjs"), scannerSource);
  writeFileSync(join(scratchRoot, "src", "workspace.mjs"), readFileSync(workspacePath, "utf8").replace(stripShebang, ""));
  writeFileSync(join(scratchRoot, "src", "native-plan.mjs"), readFileSync(nativePlanPath, "utf8").replace(stripShebang, ""));
  writeFileSync(join(scratchRoot, "src", "native-contract.mjs"), readFileSync(nativeContractPath, "utf8").replace(stripShebang, ""));
  writeFileSync(join(scratchRoot, "src", "main.mjs"), entryText);
  // The exact compiler pin must resolve from the adapter's own provisioning.
  const tsPackageDir = dirname(require.resolve("typescript/package.json"));
  writeFileSync(
    join(scratchRoot, "package.json"),
    JSON.stringify({ name: "lekalo-adapter-build", type: "module", private: true }),
  );

  const result = await build({
    entryPoints: [join(scratchRoot, "src", "main.mjs")],
    bundle: true,
    platform: "node",
    format: "esm",
    target: "node18",
    splitting: false,
    sourcemap: false,
    write: false,
    metafile: false,
    logLevel: "silent",
    absWorkingDir: scratchRoot,
    nodePaths: [],
    alias: {
      typescript: join(tsPackageDir, "lib", "typescript.js"),
    },
    banner: {
      // Node built-in require for the compiler's optional built-in probes,
      // plus module-local __filename/__dirname compatibility (the compiler
      // checks `__filename.endsWith("sys.js")` to detect its lib layout).
      js:
        'import { createRequire as __lekaloCreateRequire } from "node:module";' +
        'var require = __lekaloCreateRequire(import.meta.url);' +
        'var __filename = import.meta.url;' +
        'var __dirname = __filename.slice(0, __filename.lastIndexOf("/"));',
    },
    define: {
      "process.env.NODE_ENV": '"production"',
      "process.env.TYPESCRIPT_VERSION": JSON.stringify(TYPESCRIPT_VERSION),
    },
    footer: {
      js: "",
    },
  });
  const raw = new TextDecoder().decode(result.outputFiles[0].contents);
  // Strip esbuild's trailing `//# sourceMappingURL` style comments (none in
  // this configuration) and normalize a single trailing newline.
  const body = raw.replace(/\n*$/, "\n");
  return banner + body;
}

const check = process.argv.slice(2).includes("--check");
const artifact = await buildArtifact();
const digest = "sha256:" + createHash("sha256").update(artifact, "utf8").digest("hex");

if (check) {
  if (!existsSync(artifactPath)) {
    process.stderr.write("--check: committed artifact is missing\n");
    process.exit(1);
  }
  const committed = readFileSync(artifactPath, "utf8");
  if (committed !== artifact) {
    process.stderr.write(
      `--check: committed adapter.mjs differs from the deterministic rebuild\n` +
        `rebuild digest: ${digest}\n`,
    );
    process.exit(1);
  }
  process.stdout.write(
    JSON.stringify({ ok: true, check: true, digest, bytes: Buffer.byteLength(artifact) }) + "\n",
  );
} else {
  writeFileSync(artifactPath, artifact);
  process.stdout.write(
    JSON.stringify({
      ok: true,
      written: artifactPath,
      digest,
      bytes: Buffer.byteLength(artifact),
      typescript: TYPESCRIPT_VERSION,
      esbuild: ESBUILD_VERSION,
      esbuildBinary: esbuildBinaryPath(),
    }) + "\n",
  );
}
